// Generated by jextract

package io.github.kingg22.godot;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef void (*GDExtensionClassMethodValidatedCall)(void *, GDExtensionClassInstancePtr, const GDExtensionConstVariantPtr *, GDExtensionVariantPtr)
 * }
 */
public final class GDExtensionClassMethodValidatedCall {

    private GDExtensionClassMethodValidatedCall() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        void apply(MemorySegment method_userdata, MemorySegment p_instance, MemorySegment p_args, MemorySegment r_return);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
        gdextension_interface_h.C_POINTER,
        gdextension_interface_h.C_POINTER,
        gdextension_interface_h.C_POINTER,
        gdextension_interface_h.C_POINTER
    );

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = gdextension_interface_h.upcallHandle(GDExtensionClassMethodValidatedCall.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(GDExtensionClassMethodValidatedCall.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static void invoke(MemorySegment funcPtr, MemorySegment method_userdata, MemorySegment p_instance, MemorySegment p_args, MemorySegment r_return) {
        try {
             DOWN$MH.invokeExact(funcPtr, method_userdata, p_instance, p_args, r_return);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

