// Generated by jextract

package io.github.kingg22.godot;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     void *callable_userdata;
 *     void *token;
 *     GDObjectInstanceID object_id;
 *     GDExtensionCallableCustomCall call_func;
 *     GDExtensionCallableCustomIsValid is_valid_func;
 *     GDExtensionCallableCustomFree free_func;
 *     GDExtensionCallableCustomHash hash_func;
 *     GDExtensionCallableCustomEqual equal_func;
 *     GDExtensionCallableCustomLessThan less_than_func;
 *     GDExtensionCallableCustomToString to_string_func;
 *     GDExtensionCallableCustomGetArgumentCount get_argument_count_func;
 * }
 * }
 */
public class GDExtensionCallableCustomInfo2 {

    GDExtensionCallableCustomInfo2() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        gdextension_interface_h.C_POINTER.withName("callable_userdata"),
        gdextension_interface_h.C_POINTER.withName("token"),
        gdextension_interface_h.C_LONG.withName("object_id"),
        gdextension_interface_h.C_POINTER.withName("call_func"),
        gdextension_interface_h.C_POINTER.withName("is_valid_func"),
        gdextension_interface_h.C_POINTER.withName("free_func"),
        gdextension_interface_h.C_POINTER.withName("hash_func"),
        gdextension_interface_h.C_POINTER.withName("equal_func"),
        gdextension_interface_h.C_POINTER.withName("less_than_func"),
        gdextension_interface_h.C_POINTER.withName("to_string_func"),
        gdextension_interface_h.C_POINTER.withName("get_argument_count_func")
    ).withName("$anon$525:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout callable_userdata$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("callable_userdata"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void *callable_userdata
     * }
     */
    public static final AddressLayout callable_userdata$layout() {
        return callable_userdata$LAYOUT;
    }

    private static final long callable_userdata$OFFSET = $LAYOUT.byteOffset(groupElement("callable_userdata"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void *callable_userdata
     * }
     */
    public static final long callable_userdata$offset() {
        return callable_userdata$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void *callable_userdata
     * }
     */
    public static MemorySegment callable_userdata(MemorySegment struct) {
        return struct.get(callable_userdata$LAYOUT, callable_userdata$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void *callable_userdata
     * }
     */
    public static void callable_userdata(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(callable_userdata$LAYOUT, callable_userdata$OFFSET, fieldValue);
    }

    private static final AddressLayout token$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("token"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void *token
     * }
     */
    public static final AddressLayout token$layout() {
        return token$LAYOUT;
    }

    private static final long token$OFFSET = $LAYOUT.byteOffset(groupElement("token"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void *token
     * }
     */
    public static final long token$offset() {
        return token$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void *token
     * }
     */
    public static MemorySegment token(MemorySegment struct) {
        return struct.get(token$LAYOUT, token$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void *token
     * }
     */
    public static void token(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(token$LAYOUT, token$OFFSET, fieldValue);
    }

    private static final OfLong object_id$LAYOUT = (OfLong)$LAYOUT.select(groupElement("object_id"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * GDObjectInstanceID object_id
     * }
     */
    public static final OfLong object_id$layout() {
        return object_id$LAYOUT;
    }

    private static final long object_id$OFFSET = $LAYOUT.byteOffset(groupElement("object_id"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * GDObjectInstanceID object_id
     * }
     */
    public static final long object_id$offset() {
        return object_id$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * GDObjectInstanceID object_id
     * }
     */
    public static long object_id(MemorySegment struct) {
        return struct.get(object_id$LAYOUT, object_id$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * GDObjectInstanceID object_id
     * }
     */
    public static void object_id(MemorySegment struct, long fieldValue) {
        struct.set(object_id$LAYOUT, object_id$OFFSET, fieldValue);
    }

    private static final AddressLayout call_func$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("call_func"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * GDExtensionCallableCustomCall call_func
     * }
     */
    public static final AddressLayout call_func$layout() {
        return call_func$LAYOUT;
    }

    private static final long call_func$OFFSET = $LAYOUT.byteOffset(groupElement("call_func"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * GDExtensionCallableCustomCall call_func
     * }
     */
    public static final long call_func$offset() {
        return call_func$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * GDExtensionCallableCustomCall call_func
     * }
     */
    public static MemorySegment call_func(MemorySegment struct) {
        return struct.get(call_func$LAYOUT, call_func$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * GDExtensionCallableCustomCall call_func
     * }
     */
    public static void call_func(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(call_func$LAYOUT, call_func$OFFSET, fieldValue);
    }

    private static final AddressLayout is_valid_func$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("is_valid_func"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * GDExtensionCallableCustomIsValid is_valid_func
     * }
     */
    public static final AddressLayout is_valid_func$layout() {
        return is_valid_func$LAYOUT;
    }

    private static final long is_valid_func$OFFSET = $LAYOUT.byteOffset(groupElement("is_valid_func"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * GDExtensionCallableCustomIsValid is_valid_func
     * }
     */
    public static final long is_valid_func$offset() {
        return is_valid_func$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * GDExtensionCallableCustomIsValid is_valid_func
     * }
     */
    public static MemorySegment is_valid_func(MemorySegment struct) {
        return struct.get(is_valid_func$LAYOUT, is_valid_func$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * GDExtensionCallableCustomIsValid is_valid_func
     * }
     */
    public static void is_valid_func(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(is_valid_func$LAYOUT, is_valid_func$OFFSET, fieldValue);
    }

    private static final AddressLayout free_func$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("free_func"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * GDExtensionCallableCustomFree free_func
     * }
     */
    public static final AddressLayout free_func$layout() {
        return free_func$LAYOUT;
    }

    private static final long free_func$OFFSET = $LAYOUT.byteOffset(groupElement("free_func"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * GDExtensionCallableCustomFree free_func
     * }
     */
    public static final long free_func$offset() {
        return free_func$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * GDExtensionCallableCustomFree free_func
     * }
     */
    public static MemorySegment free_func(MemorySegment struct) {
        return struct.get(free_func$LAYOUT, free_func$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * GDExtensionCallableCustomFree free_func
     * }
     */
    public static void free_func(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(free_func$LAYOUT, free_func$OFFSET, fieldValue);
    }

    private static final AddressLayout hash_func$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("hash_func"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * GDExtensionCallableCustomHash hash_func
     * }
     */
    public static final AddressLayout hash_func$layout() {
        return hash_func$LAYOUT;
    }

    private static final long hash_func$OFFSET = $LAYOUT.byteOffset(groupElement("hash_func"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * GDExtensionCallableCustomHash hash_func
     * }
     */
    public static final long hash_func$offset() {
        return hash_func$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * GDExtensionCallableCustomHash hash_func
     * }
     */
    public static MemorySegment hash_func(MemorySegment struct) {
        return struct.get(hash_func$LAYOUT, hash_func$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * GDExtensionCallableCustomHash hash_func
     * }
     */
    public static void hash_func(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(hash_func$LAYOUT, hash_func$OFFSET, fieldValue);
    }

    private static final AddressLayout equal_func$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("equal_func"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * GDExtensionCallableCustomEqual equal_func
     * }
     */
    public static final AddressLayout equal_func$layout() {
        return equal_func$LAYOUT;
    }

    private static final long equal_func$OFFSET = $LAYOUT.byteOffset(groupElement("equal_func"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * GDExtensionCallableCustomEqual equal_func
     * }
     */
    public static final long equal_func$offset() {
        return equal_func$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * GDExtensionCallableCustomEqual equal_func
     * }
     */
    public static MemorySegment equal_func(MemorySegment struct) {
        return struct.get(equal_func$LAYOUT, equal_func$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * GDExtensionCallableCustomEqual equal_func
     * }
     */
    public static void equal_func(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(equal_func$LAYOUT, equal_func$OFFSET, fieldValue);
    }

    private static final AddressLayout less_than_func$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("less_than_func"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * GDExtensionCallableCustomLessThan less_than_func
     * }
     */
    public static final AddressLayout less_than_func$layout() {
        return less_than_func$LAYOUT;
    }

    private static final long less_than_func$OFFSET = $LAYOUT.byteOffset(groupElement("less_than_func"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * GDExtensionCallableCustomLessThan less_than_func
     * }
     */
    public static final long less_than_func$offset() {
        return less_than_func$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * GDExtensionCallableCustomLessThan less_than_func
     * }
     */
    public static MemorySegment less_than_func(MemorySegment struct) {
        return struct.get(less_than_func$LAYOUT, less_than_func$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * GDExtensionCallableCustomLessThan less_than_func
     * }
     */
    public static void less_than_func(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(less_than_func$LAYOUT, less_than_func$OFFSET, fieldValue);
    }

    private static final AddressLayout to_string_func$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("to_string_func"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * GDExtensionCallableCustomToString to_string_func
     * }
     */
    public static final AddressLayout to_string_func$layout() {
        return to_string_func$LAYOUT;
    }

    private static final long to_string_func$OFFSET = $LAYOUT.byteOffset(groupElement("to_string_func"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * GDExtensionCallableCustomToString to_string_func
     * }
     */
    public static final long to_string_func$offset() {
        return to_string_func$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * GDExtensionCallableCustomToString to_string_func
     * }
     */
    public static MemorySegment to_string_func(MemorySegment struct) {
        return struct.get(to_string_func$LAYOUT, to_string_func$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * GDExtensionCallableCustomToString to_string_func
     * }
     */
    public static void to_string_func(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(to_string_func$LAYOUT, to_string_func$OFFSET, fieldValue);
    }

    private static final AddressLayout get_argument_count_func$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("get_argument_count_func"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * GDExtensionCallableCustomGetArgumentCount get_argument_count_func
     * }
     */
    public static final AddressLayout get_argument_count_func$layout() {
        return get_argument_count_func$LAYOUT;
    }

    private static final long get_argument_count_func$OFFSET = $LAYOUT.byteOffset(groupElement("get_argument_count_func"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * GDExtensionCallableCustomGetArgumentCount get_argument_count_func
     * }
     */
    public static final long get_argument_count_func$offset() {
        return get_argument_count_func$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * GDExtensionCallableCustomGetArgumentCount get_argument_count_func
     * }
     */
    public static MemorySegment get_argument_count_func(MemorySegment struct) {
        return struct.get(get_argument_count_func$LAYOUT, get_argument_count_func$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * GDExtensionCallableCustomGetArgumentCount get_argument_count_func
     * }
     */
    public static void get_argument_count_func(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(get_argument_count_func$LAYOUT, get_argument_count_func$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

