// Generated by jextract

package io.github.kingg22.godot;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     GDExtensionStringNamePtr name;
 *     void *method_userdata;
 *     GDExtensionClassMethodCall call_func;
 *     GDExtensionClassMethodPtrCall ptrcall_func;
 *     uint32_t method_flags;
 *     GDExtensionBool has_return_value;
 *     GDExtensionPropertyInfo *return_value_info;
 *     GDExtensionClassMethodArgumentMetadata return_value_metadata;
 *     uint32_t argument_count;
 *     GDExtensionPropertyInfo *arguments_info;
 *     GDExtensionClassMethodArgumentMetadata *arguments_metadata;
 *     uint32_t default_argument_count;
 *     GDExtensionVariantPtr *default_arguments;
 * }
 * }
 */
public class GDExtensionClassMethodInfo {

    GDExtensionClassMethodInfo() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        gdextension_interface_h.C_POINTER.withName("name"),
        gdextension_interface_h.C_POINTER.withName("method_userdata"),
        gdextension_interface_h.C_POINTER.withName("call_func"),
        gdextension_interface_h.C_POINTER.withName("ptrcall_func"),
        gdextension_interface_h.C_INT.withName("method_flags"),
        gdextension_interface_h.C_CHAR.withName("has_return_value"),
        MemoryLayout.paddingLayout(3),
        gdextension_interface_h.C_POINTER.withName("return_value_info"),
        gdextension_interface_h.C_INT.withName("return_value_metadata"),
        gdextension_interface_h.C_INT.withName("argument_count"),
        gdextension_interface_h.C_POINTER.withName("arguments_info"),
        gdextension_interface_h.C_POINTER.withName("arguments_metadata"),
        gdextension_interface_h.C_INT.withName("default_argument_count"),
        MemoryLayout.paddingLayout(4),
        gdextension_interface_h.C_POINTER.withName("default_arguments")
    ).withName("$anon$441:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout name$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("name"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * GDExtensionStringNamePtr name
     * }
     */
    public static final AddressLayout name$layout() {
        return name$LAYOUT;
    }

    private static final long name$OFFSET = $LAYOUT.byteOffset(groupElement("name"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * GDExtensionStringNamePtr name
     * }
     */
    public static final long name$offset() {
        return name$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * GDExtensionStringNamePtr name
     * }
     */
    public static MemorySegment name(MemorySegment struct) {
        return struct.get(name$LAYOUT, name$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * GDExtensionStringNamePtr name
     * }
     */
    public static void name(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(name$LAYOUT, name$OFFSET, fieldValue);
    }

    private static final AddressLayout method_userdata$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("method_userdata"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void *method_userdata
     * }
     */
    public static final AddressLayout method_userdata$layout() {
        return method_userdata$LAYOUT;
    }

    private static final long method_userdata$OFFSET = $LAYOUT.byteOffset(groupElement("method_userdata"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void *method_userdata
     * }
     */
    public static final long method_userdata$offset() {
        return method_userdata$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void *method_userdata
     * }
     */
    public static MemorySegment method_userdata(MemorySegment struct) {
        return struct.get(method_userdata$LAYOUT, method_userdata$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void *method_userdata
     * }
     */
    public static void method_userdata(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(method_userdata$LAYOUT, method_userdata$OFFSET, fieldValue);
    }

    private static final AddressLayout call_func$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("call_func"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * GDExtensionClassMethodCall call_func
     * }
     */
    public static final AddressLayout call_func$layout() {
        return call_func$LAYOUT;
    }

    private static final long call_func$OFFSET = $LAYOUT.byteOffset(groupElement("call_func"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * GDExtensionClassMethodCall call_func
     * }
     */
    public static final long call_func$offset() {
        return call_func$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * GDExtensionClassMethodCall call_func
     * }
     */
    public static MemorySegment call_func(MemorySegment struct) {
        return struct.get(call_func$LAYOUT, call_func$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * GDExtensionClassMethodCall call_func
     * }
     */
    public static void call_func(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(call_func$LAYOUT, call_func$OFFSET, fieldValue);
    }

    private static final AddressLayout ptrcall_func$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("ptrcall_func"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * GDExtensionClassMethodPtrCall ptrcall_func
     * }
     */
    public static final AddressLayout ptrcall_func$layout() {
        return ptrcall_func$LAYOUT;
    }

    private static final long ptrcall_func$OFFSET = $LAYOUT.byteOffset(groupElement("ptrcall_func"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * GDExtensionClassMethodPtrCall ptrcall_func
     * }
     */
    public static final long ptrcall_func$offset() {
        return ptrcall_func$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * GDExtensionClassMethodPtrCall ptrcall_func
     * }
     */
    public static MemorySegment ptrcall_func(MemorySegment struct) {
        return struct.get(ptrcall_func$LAYOUT, ptrcall_func$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * GDExtensionClassMethodPtrCall ptrcall_func
     * }
     */
    public static void ptrcall_func(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(ptrcall_func$LAYOUT, ptrcall_func$OFFSET, fieldValue);
    }

    private static final OfInt method_flags$LAYOUT = (OfInt)$LAYOUT.select(groupElement("method_flags"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t method_flags
     * }
     */
    public static final OfInt method_flags$layout() {
        return method_flags$LAYOUT;
    }

    private static final long method_flags$OFFSET = $LAYOUT.byteOffset(groupElement("method_flags"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t method_flags
     * }
     */
    public static final long method_flags$offset() {
        return method_flags$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t method_flags
     * }
     */
    public static int method_flags(MemorySegment struct) {
        return struct.get(method_flags$LAYOUT, method_flags$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t method_flags
     * }
     */
    public static void method_flags(MemorySegment struct, int fieldValue) {
        struct.set(method_flags$LAYOUT, method_flags$OFFSET, fieldValue);
    }

    private static final OfByte has_return_value$LAYOUT = (OfByte)$LAYOUT.select(groupElement("has_return_value"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * GDExtensionBool has_return_value
     * }
     */
    public static final OfByte has_return_value$layout() {
        return has_return_value$LAYOUT;
    }

    private static final long has_return_value$OFFSET = $LAYOUT.byteOffset(groupElement("has_return_value"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * GDExtensionBool has_return_value
     * }
     */
    public static final long has_return_value$offset() {
        return has_return_value$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * GDExtensionBool has_return_value
     * }
     */
    public static byte has_return_value(MemorySegment struct) {
        return struct.get(has_return_value$LAYOUT, has_return_value$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * GDExtensionBool has_return_value
     * }
     */
    public static void has_return_value(MemorySegment struct, byte fieldValue) {
        struct.set(has_return_value$LAYOUT, has_return_value$OFFSET, fieldValue);
    }

    private static final AddressLayout return_value_info$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("return_value_info"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * GDExtensionPropertyInfo *return_value_info
     * }
     */
    public static final AddressLayout return_value_info$layout() {
        return return_value_info$LAYOUT;
    }

    private static final long return_value_info$OFFSET = $LAYOUT.byteOffset(groupElement("return_value_info"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * GDExtensionPropertyInfo *return_value_info
     * }
     */
    public static final long return_value_info$offset() {
        return return_value_info$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * GDExtensionPropertyInfo *return_value_info
     * }
     */
    public static MemorySegment return_value_info(MemorySegment struct) {
        return struct.get(return_value_info$LAYOUT, return_value_info$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * GDExtensionPropertyInfo *return_value_info
     * }
     */
    public static void return_value_info(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(return_value_info$LAYOUT, return_value_info$OFFSET, fieldValue);
    }

    private static final OfInt return_value_metadata$LAYOUT = (OfInt)$LAYOUT.select(groupElement("return_value_metadata"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * GDExtensionClassMethodArgumentMetadata return_value_metadata
     * }
     */
    public static final OfInt return_value_metadata$layout() {
        return return_value_metadata$LAYOUT;
    }

    private static final long return_value_metadata$OFFSET = $LAYOUT.byteOffset(groupElement("return_value_metadata"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * GDExtensionClassMethodArgumentMetadata return_value_metadata
     * }
     */
    public static final long return_value_metadata$offset() {
        return return_value_metadata$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * GDExtensionClassMethodArgumentMetadata return_value_metadata
     * }
     */
    public static int return_value_metadata(MemorySegment struct) {
        return struct.get(return_value_metadata$LAYOUT, return_value_metadata$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * GDExtensionClassMethodArgumentMetadata return_value_metadata
     * }
     */
    public static void return_value_metadata(MemorySegment struct, int fieldValue) {
        struct.set(return_value_metadata$LAYOUT, return_value_metadata$OFFSET, fieldValue);
    }

    private static final OfInt argument_count$LAYOUT = (OfInt)$LAYOUT.select(groupElement("argument_count"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t argument_count
     * }
     */
    public static final OfInt argument_count$layout() {
        return argument_count$LAYOUT;
    }

    private static final long argument_count$OFFSET = $LAYOUT.byteOffset(groupElement("argument_count"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t argument_count
     * }
     */
    public static final long argument_count$offset() {
        return argument_count$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t argument_count
     * }
     */
    public static int argument_count(MemorySegment struct) {
        return struct.get(argument_count$LAYOUT, argument_count$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t argument_count
     * }
     */
    public static void argument_count(MemorySegment struct, int fieldValue) {
        struct.set(argument_count$LAYOUT, argument_count$OFFSET, fieldValue);
    }

    private static final AddressLayout arguments_info$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("arguments_info"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * GDExtensionPropertyInfo *arguments_info
     * }
     */
    public static final AddressLayout arguments_info$layout() {
        return arguments_info$LAYOUT;
    }

    private static final long arguments_info$OFFSET = $LAYOUT.byteOffset(groupElement("arguments_info"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * GDExtensionPropertyInfo *arguments_info
     * }
     */
    public static final long arguments_info$offset() {
        return arguments_info$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * GDExtensionPropertyInfo *arguments_info
     * }
     */
    public static MemorySegment arguments_info(MemorySegment struct) {
        return struct.get(arguments_info$LAYOUT, arguments_info$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * GDExtensionPropertyInfo *arguments_info
     * }
     */
    public static void arguments_info(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(arguments_info$LAYOUT, arguments_info$OFFSET, fieldValue);
    }

    private static final AddressLayout arguments_metadata$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("arguments_metadata"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * GDExtensionClassMethodArgumentMetadata *arguments_metadata
     * }
     */
    public static final AddressLayout arguments_metadata$layout() {
        return arguments_metadata$LAYOUT;
    }

    private static final long arguments_metadata$OFFSET = $LAYOUT.byteOffset(groupElement("arguments_metadata"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * GDExtensionClassMethodArgumentMetadata *arguments_metadata
     * }
     */
    public static final long arguments_metadata$offset() {
        return arguments_metadata$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * GDExtensionClassMethodArgumentMetadata *arguments_metadata
     * }
     */
    public static MemorySegment arguments_metadata(MemorySegment struct) {
        return struct.get(arguments_metadata$LAYOUT, arguments_metadata$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * GDExtensionClassMethodArgumentMetadata *arguments_metadata
     * }
     */
    public static void arguments_metadata(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(arguments_metadata$LAYOUT, arguments_metadata$OFFSET, fieldValue);
    }

    private static final OfInt default_argument_count$LAYOUT = (OfInt)$LAYOUT.select(groupElement("default_argument_count"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t default_argument_count
     * }
     */
    public static final OfInt default_argument_count$layout() {
        return default_argument_count$LAYOUT;
    }

    private static final long default_argument_count$OFFSET = $LAYOUT.byteOffset(groupElement("default_argument_count"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t default_argument_count
     * }
     */
    public static final long default_argument_count$offset() {
        return default_argument_count$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t default_argument_count
     * }
     */
    public static int default_argument_count(MemorySegment struct) {
        return struct.get(default_argument_count$LAYOUT, default_argument_count$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t default_argument_count
     * }
     */
    public static void default_argument_count(MemorySegment struct, int fieldValue) {
        struct.set(default_argument_count$LAYOUT, default_argument_count$OFFSET, fieldValue);
    }

    private static final AddressLayout default_arguments$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("default_arguments"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * GDExtensionVariantPtr *default_arguments
     * }
     */
    public static final AddressLayout default_arguments$layout() {
        return default_arguments$LAYOUT;
    }

    private static final long default_arguments$OFFSET = $LAYOUT.byteOffset(groupElement("default_arguments"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * GDExtensionVariantPtr *default_arguments
     * }
     */
    public static final long default_arguments$offset() {
        return default_arguments$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * GDExtensionVariantPtr *default_arguments
     * }
     */
    public static MemorySegment default_arguments(MemorySegment struct) {
        return struct.get(default_arguments$LAYOUT, default_arguments$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * GDExtensionVariantPtr *default_arguments
     * }
     */
    public static void default_arguments(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(default_arguments$LAYOUT, default_arguments$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

