// Generated by jextract

package io.github.kingg22.godot;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef GDExtensionInt (*GDExtensionCallableCustomGetArgumentCount)(void *, GDExtensionBool *)
 * }
 */
public final class GDExtensionCallableCustomGetArgumentCount {

    private GDExtensionCallableCustomGetArgumentCount() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        long apply(MemorySegment callable_userdata, MemorySegment r_is_valid);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
        gdextension_interface_h.C_LONG,
        gdextension_interface_h.C_POINTER,
        gdextension_interface_h.C_POINTER
    );

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = gdextension_interface_h.upcallHandle(GDExtensionCallableCustomGetArgumentCount.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(GDExtensionCallableCustomGetArgumentCount.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static long invoke(MemorySegment funcPtr, MemorySegment callable_userdata, MemorySegment r_is_valid) {
        try {
            return (long) DOWN$MH.invokeExact(funcPtr, callable_userdata, r_is_valid);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

