// Generated by jextract

package io.github.kingg22.godot;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     GDExtensionScriptInstanceSet set_func;
 *     GDExtensionScriptInstanceGet get_func;
 *     GDExtensionScriptInstanceGetPropertyList get_property_list_func;
 *     GDExtensionScriptInstanceFreePropertyList2 free_property_list_func;
 *     GDExtensionScriptInstanceGetClassCategory get_class_category_func;
 *     GDExtensionScriptInstancePropertyCanRevert property_can_revert_func;
 *     GDExtensionScriptInstancePropertyGetRevert property_get_revert_func;
 *     GDExtensionScriptInstanceGetOwner get_owner_func;
 *     GDExtensionScriptInstanceGetPropertyState get_property_state_func;
 *     GDExtensionScriptInstanceGetMethodList get_method_list_func;
 *     GDExtensionScriptInstanceFreeMethodList2 free_method_list_func;
 *     GDExtensionScriptInstanceGetPropertyType get_property_type_func;
 *     GDExtensionScriptInstanceValidateProperty validate_property_func;
 *     GDExtensionScriptInstanceHasMethod has_method_func;
 *     GDExtensionScriptInstanceGetMethodArgumentCount get_method_argument_count_func;
 *     GDExtensionScriptInstanceCall call_func;
 *     GDExtensionScriptInstanceNotification2 notification_func;
 *     GDExtensionScriptInstanceToString to_string_func;
 *     GDExtensionScriptInstanceRefCountIncremented refcount_incremented_func;
 *     GDExtensionScriptInstanceRefCountDecremented refcount_decremented_func;
 *     GDExtensionScriptInstanceGetScript get_script_func;
 *     GDExtensionScriptInstanceIsPlaceholder is_placeholder_func;
 *     GDExtensionScriptInstanceSet set_fallback_func;
 *     GDExtensionScriptInstanceGet get_fallback_func;
 *     GDExtensionScriptInstanceGetLanguage get_language_func;
 *     GDExtensionScriptInstanceFree free_func;
 * }
 * }
 */
public class GDExtensionScriptInstanceInfo3 {

    GDExtensionScriptInstanceInfo3() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        gdextension_interface_h.C_POINTER.withName("set_func"),
        gdextension_interface_h.C_POINTER.withName("get_func"),
        gdextension_interface_h.C_POINTER.withName("get_property_list_func"),
        gdextension_interface_h.C_POINTER.withName("free_property_list_func"),
        gdextension_interface_h.C_POINTER.withName("get_class_category_func"),
        gdextension_interface_h.C_POINTER.withName("property_can_revert_func"),
        gdextension_interface_h.C_POINTER.withName("property_get_revert_func"),
        gdextension_interface_h.C_POINTER.withName("get_owner_func"),
        gdextension_interface_h.C_POINTER.withName("get_property_state_func"),
        gdextension_interface_h.C_POINTER.withName("get_method_list_func"),
        gdextension_interface_h.C_POINTER.withName("free_method_list_func"),
        gdextension_interface_h.C_POINTER.withName("get_property_type_func"),
        gdextension_interface_h.C_POINTER.withName("validate_property_func"),
        gdextension_interface_h.C_POINTER.withName("has_method_func"),
        gdextension_interface_h.C_POINTER.withName("get_method_argument_count_func"),
        gdextension_interface_h.C_POINTER.withName("call_func"),
        gdextension_interface_h.C_POINTER.withName("notification_func"),
        gdextension_interface_h.C_POINTER.withName("to_string_func"),
        gdextension_interface_h.C_POINTER.withName("refcount_incremented_func"),
        gdextension_interface_h.C_POINTER.withName("refcount_decremented_func"),
        gdextension_interface_h.C_POINTER.withName("get_script_func"),
        gdextension_interface_h.C_POINTER.withName("is_placeholder_func"),
        gdextension_interface_h.C_POINTER.withName("set_fallback_func"),
        gdextension_interface_h.C_POINTER.withName("get_fallback_func"),
        gdextension_interface_h.C_POINTER.withName("get_language_func"),
        gdextension_interface_h.C_POINTER.withName("free_func")
    ).withName("$anon$686:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout set_func$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("set_func"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceSet set_func
     * }
     */
    public static final AddressLayout set_func$layout() {
        return set_func$LAYOUT;
    }

    private static final long set_func$OFFSET = $LAYOUT.byteOffset(groupElement("set_func"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceSet set_func
     * }
     */
    public static final long set_func$offset() {
        return set_func$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceSet set_func
     * }
     */
    public static MemorySegment set_func(MemorySegment struct) {
        return struct.get(set_func$LAYOUT, set_func$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceSet set_func
     * }
     */
    public static void set_func(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(set_func$LAYOUT, set_func$OFFSET, fieldValue);
    }

    private static final AddressLayout get_func$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("get_func"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceGet get_func
     * }
     */
    public static final AddressLayout get_func$layout() {
        return get_func$LAYOUT;
    }

    private static final long get_func$OFFSET = $LAYOUT.byteOffset(groupElement("get_func"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceGet get_func
     * }
     */
    public static final long get_func$offset() {
        return get_func$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceGet get_func
     * }
     */
    public static MemorySegment get_func(MemorySegment struct) {
        return struct.get(get_func$LAYOUT, get_func$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceGet get_func
     * }
     */
    public static void get_func(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(get_func$LAYOUT, get_func$OFFSET, fieldValue);
    }

    private static final AddressLayout get_property_list_func$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("get_property_list_func"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceGetPropertyList get_property_list_func
     * }
     */
    public static final AddressLayout get_property_list_func$layout() {
        return get_property_list_func$LAYOUT;
    }

    private static final long get_property_list_func$OFFSET = $LAYOUT.byteOffset(groupElement("get_property_list_func"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceGetPropertyList get_property_list_func
     * }
     */
    public static final long get_property_list_func$offset() {
        return get_property_list_func$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceGetPropertyList get_property_list_func
     * }
     */
    public static MemorySegment get_property_list_func(MemorySegment struct) {
        return struct.get(get_property_list_func$LAYOUT, get_property_list_func$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceGetPropertyList get_property_list_func
     * }
     */
    public static void get_property_list_func(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(get_property_list_func$LAYOUT, get_property_list_func$OFFSET, fieldValue);
    }

    private static final AddressLayout free_property_list_func$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("free_property_list_func"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceFreePropertyList2 free_property_list_func
     * }
     */
    public static final AddressLayout free_property_list_func$layout() {
        return free_property_list_func$LAYOUT;
    }

    private static final long free_property_list_func$OFFSET = $LAYOUT.byteOffset(groupElement("free_property_list_func"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceFreePropertyList2 free_property_list_func
     * }
     */
    public static final long free_property_list_func$offset() {
        return free_property_list_func$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceFreePropertyList2 free_property_list_func
     * }
     */
    public static MemorySegment free_property_list_func(MemorySegment struct) {
        return struct.get(free_property_list_func$LAYOUT, free_property_list_func$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceFreePropertyList2 free_property_list_func
     * }
     */
    public static void free_property_list_func(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(free_property_list_func$LAYOUT, free_property_list_func$OFFSET, fieldValue);
    }

    private static final AddressLayout get_class_category_func$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("get_class_category_func"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceGetClassCategory get_class_category_func
     * }
     */
    public static final AddressLayout get_class_category_func$layout() {
        return get_class_category_func$LAYOUT;
    }

    private static final long get_class_category_func$OFFSET = $LAYOUT.byteOffset(groupElement("get_class_category_func"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceGetClassCategory get_class_category_func
     * }
     */
    public static final long get_class_category_func$offset() {
        return get_class_category_func$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceGetClassCategory get_class_category_func
     * }
     */
    public static MemorySegment get_class_category_func(MemorySegment struct) {
        return struct.get(get_class_category_func$LAYOUT, get_class_category_func$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceGetClassCategory get_class_category_func
     * }
     */
    public static void get_class_category_func(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(get_class_category_func$LAYOUT, get_class_category_func$OFFSET, fieldValue);
    }

    private static final AddressLayout property_can_revert_func$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("property_can_revert_func"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstancePropertyCanRevert property_can_revert_func
     * }
     */
    public static final AddressLayout property_can_revert_func$layout() {
        return property_can_revert_func$LAYOUT;
    }

    private static final long property_can_revert_func$OFFSET = $LAYOUT.byteOffset(groupElement("property_can_revert_func"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstancePropertyCanRevert property_can_revert_func
     * }
     */
    public static final long property_can_revert_func$offset() {
        return property_can_revert_func$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstancePropertyCanRevert property_can_revert_func
     * }
     */
    public static MemorySegment property_can_revert_func(MemorySegment struct) {
        return struct.get(property_can_revert_func$LAYOUT, property_can_revert_func$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstancePropertyCanRevert property_can_revert_func
     * }
     */
    public static void property_can_revert_func(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(property_can_revert_func$LAYOUT, property_can_revert_func$OFFSET, fieldValue);
    }

    private static final AddressLayout property_get_revert_func$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("property_get_revert_func"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstancePropertyGetRevert property_get_revert_func
     * }
     */
    public static final AddressLayout property_get_revert_func$layout() {
        return property_get_revert_func$LAYOUT;
    }

    private static final long property_get_revert_func$OFFSET = $LAYOUT.byteOffset(groupElement("property_get_revert_func"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstancePropertyGetRevert property_get_revert_func
     * }
     */
    public static final long property_get_revert_func$offset() {
        return property_get_revert_func$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstancePropertyGetRevert property_get_revert_func
     * }
     */
    public static MemorySegment property_get_revert_func(MemorySegment struct) {
        return struct.get(property_get_revert_func$LAYOUT, property_get_revert_func$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstancePropertyGetRevert property_get_revert_func
     * }
     */
    public static void property_get_revert_func(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(property_get_revert_func$LAYOUT, property_get_revert_func$OFFSET, fieldValue);
    }

    private static final AddressLayout get_owner_func$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("get_owner_func"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceGetOwner get_owner_func
     * }
     */
    public static final AddressLayout get_owner_func$layout() {
        return get_owner_func$LAYOUT;
    }

    private static final long get_owner_func$OFFSET = $LAYOUT.byteOffset(groupElement("get_owner_func"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceGetOwner get_owner_func
     * }
     */
    public static final long get_owner_func$offset() {
        return get_owner_func$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceGetOwner get_owner_func
     * }
     */
    public static MemorySegment get_owner_func(MemorySegment struct) {
        return struct.get(get_owner_func$LAYOUT, get_owner_func$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceGetOwner get_owner_func
     * }
     */
    public static void get_owner_func(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(get_owner_func$LAYOUT, get_owner_func$OFFSET, fieldValue);
    }

    private static final AddressLayout get_property_state_func$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("get_property_state_func"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceGetPropertyState get_property_state_func
     * }
     */
    public static final AddressLayout get_property_state_func$layout() {
        return get_property_state_func$LAYOUT;
    }

    private static final long get_property_state_func$OFFSET = $LAYOUT.byteOffset(groupElement("get_property_state_func"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceGetPropertyState get_property_state_func
     * }
     */
    public static final long get_property_state_func$offset() {
        return get_property_state_func$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceGetPropertyState get_property_state_func
     * }
     */
    public static MemorySegment get_property_state_func(MemorySegment struct) {
        return struct.get(get_property_state_func$LAYOUT, get_property_state_func$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceGetPropertyState get_property_state_func
     * }
     */
    public static void get_property_state_func(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(get_property_state_func$LAYOUT, get_property_state_func$OFFSET, fieldValue);
    }

    private static final AddressLayout get_method_list_func$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("get_method_list_func"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceGetMethodList get_method_list_func
     * }
     */
    public static final AddressLayout get_method_list_func$layout() {
        return get_method_list_func$LAYOUT;
    }

    private static final long get_method_list_func$OFFSET = $LAYOUT.byteOffset(groupElement("get_method_list_func"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceGetMethodList get_method_list_func
     * }
     */
    public static final long get_method_list_func$offset() {
        return get_method_list_func$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceGetMethodList get_method_list_func
     * }
     */
    public static MemorySegment get_method_list_func(MemorySegment struct) {
        return struct.get(get_method_list_func$LAYOUT, get_method_list_func$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceGetMethodList get_method_list_func
     * }
     */
    public static void get_method_list_func(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(get_method_list_func$LAYOUT, get_method_list_func$OFFSET, fieldValue);
    }

    private static final AddressLayout free_method_list_func$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("free_method_list_func"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceFreeMethodList2 free_method_list_func
     * }
     */
    public static final AddressLayout free_method_list_func$layout() {
        return free_method_list_func$LAYOUT;
    }

    private static final long free_method_list_func$OFFSET = $LAYOUT.byteOffset(groupElement("free_method_list_func"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceFreeMethodList2 free_method_list_func
     * }
     */
    public static final long free_method_list_func$offset() {
        return free_method_list_func$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceFreeMethodList2 free_method_list_func
     * }
     */
    public static MemorySegment free_method_list_func(MemorySegment struct) {
        return struct.get(free_method_list_func$LAYOUT, free_method_list_func$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceFreeMethodList2 free_method_list_func
     * }
     */
    public static void free_method_list_func(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(free_method_list_func$LAYOUT, free_method_list_func$OFFSET, fieldValue);
    }

    private static final AddressLayout get_property_type_func$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("get_property_type_func"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceGetPropertyType get_property_type_func
     * }
     */
    public static final AddressLayout get_property_type_func$layout() {
        return get_property_type_func$LAYOUT;
    }

    private static final long get_property_type_func$OFFSET = $LAYOUT.byteOffset(groupElement("get_property_type_func"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceGetPropertyType get_property_type_func
     * }
     */
    public static final long get_property_type_func$offset() {
        return get_property_type_func$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceGetPropertyType get_property_type_func
     * }
     */
    public static MemorySegment get_property_type_func(MemorySegment struct) {
        return struct.get(get_property_type_func$LAYOUT, get_property_type_func$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceGetPropertyType get_property_type_func
     * }
     */
    public static void get_property_type_func(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(get_property_type_func$LAYOUT, get_property_type_func$OFFSET, fieldValue);
    }

    private static final AddressLayout validate_property_func$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("validate_property_func"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceValidateProperty validate_property_func
     * }
     */
    public static final AddressLayout validate_property_func$layout() {
        return validate_property_func$LAYOUT;
    }

    private static final long validate_property_func$OFFSET = $LAYOUT.byteOffset(groupElement("validate_property_func"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceValidateProperty validate_property_func
     * }
     */
    public static final long validate_property_func$offset() {
        return validate_property_func$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceValidateProperty validate_property_func
     * }
     */
    public static MemorySegment validate_property_func(MemorySegment struct) {
        return struct.get(validate_property_func$LAYOUT, validate_property_func$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceValidateProperty validate_property_func
     * }
     */
    public static void validate_property_func(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(validate_property_func$LAYOUT, validate_property_func$OFFSET, fieldValue);
    }

    private static final AddressLayout has_method_func$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("has_method_func"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceHasMethod has_method_func
     * }
     */
    public static final AddressLayout has_method_func$layout() {
        return has_method_func$LAYOUT;
    }

    private static final long has_method_func$OFFSET = $LAYOUT.byteOffset(groupElement("has_method_func"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceHasMethod has_method_func
     * }
     */
    public static final long has_method_func$offset() {
        return has_method_func$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceHasMethod has_method_func
     * }
     */
    public static MemorySegment has_method_func(MemorySegment struct) {
        return struct.get(has_method_func$LAYOUT, has_method_func$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceHasMethod has_method_func
     * }
     */
    public static void has_method_func(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(has_method_func$LAYOUT, has_method_func$OFFSET, fieldValue);
    }

    private static final AddressLayout get_method_argument_count_func$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("get_method_argument_count_func"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceGetMethodArgumentCount get_method_argument_count_func
     * }
     */
    public static final AddressLayout get_method_argument_count_func$layout() {
        return get_method_argument_count_func$LAYOUT;
    }

    private static final long get_method_argument_count_func$OFFSET = $LAYOUT.byteOffset(groupElement("get_method_argument_count_func"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceGetMethodArgumentCount get_method_argument_count_func
     * }
     */
    public static final long get_method_argument_count_func$offset() {
        return get_method_argument_count_func$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceGetMethodArgumentCount get_method_argument_count_func
     * }
     */
    public static MemorySegment get_method_argument_count_func(MemorySegment struct) {
        return struct.get(get_method_argument_count_func$LAYOUT, get_method_argument_count_func$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceGetMethodArgumentCount get_method_argument_count_func
     * }
     */
    public static void get_method_argument_count_func(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(get_method_argument_count_func$LAYOUT, get_method_argument_count_func$OFFSET, fieldValue);
    }

    private static final AddressLayout call_func$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("call_func"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceCall call_func
     * }
     */
    public static final AddressLayout call_func$layout() {
        return call_func$LAYOUT;
    }

    private static final long call_func$OFFSET = $LAYOUT.byteOffset(groupElement("call_func"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceCall call_func
     * }
     */
    public static final long call_func$offset() {
        return call_func$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceCall call_func
     * }
     */
    public static MemorySegment call_func(MemorySegment struct) {
        return struct.get(call_func$LAYOUT, call_func$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceCall call_func
     * }
     */
    public static void call_func(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(call_func$LAYOUT, call_func$OFFSET, fieldValue);
    }

    private static final AddressLayout notification_func$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("notification_func"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceNotification2 notification_func
     * }
     */
    public static final AddressLayout notification_func$layout() {
        return notification_func$LAYOUT;
    }

    private static final long notification_func$OFFSET = $LAYOUT.byteOffset(groupElement("notification_func"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceNotification2 notification_func
     * }
     */
    public static final long notification_func$offset() {
        return notification_func$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceNotification2 notification_func
     * }
     */
    public static MemorySegment notification_func(MemorySegment struct) {
        return struct.get(notification_func$LAYOUT, notification_func$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceNotification2 notification_func
     * }
     */
    public static void notification_func(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(notification_func$LAYOUT, notification_func$OFFSET, fieldValue);
    }

    private static final AddressLayout to_string_func$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("to_string_func"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceToString to_string_func
     * }
     */
    public static final AddressLayout to_string_func$layout() {
        return to_string_func$LAYOUT;
    }

    private static final long to_string_func$OFFSET = $LAYOUT.byteOffset(groupElement("to_string_func"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceToString to_string_func
     * }
     */
    public static final long to_string_func$offset() {
        return to_string_func$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceToString to_string_func
     * }
     */
    public static MemorySegment to_string_func(MemorySegment struct) {
        return struct.get(to_string_func$LAYOUT, to_string_func$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceToString to_string_func
     * }
     */
    public static void to_string_func(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(to_string_func$LAYOUT, to_string_func$OFFSET, fieldValue);
    }

    private static final AddressLayout refcount_incremented_func$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("refcount_incremented_func"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceRefCountIncremented refcount_incremented_func
     * }
     */
    public static final AddressLayout refcount_incremented_func$layout() {
        return refcount_incremented_func$LAYOUT;
    }

    private static final long refcount_incremented_func$OFFSET = $LAYOUT.byteOffset(groupElement("refcount_incremented_func"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceRefCountIncremented refcount_incremented_func
     * }
     */
    public static final long refcount_incremented_func$offset() {
        return refcount_incremented_func$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceRefCountIncremented refcount_incremented_func
     * }
     */
    public static MemorySegment refcount_incremented_func(MemorySegment struct) {
        return struct.get(refcount_incremented_func$LAYOUT, refcount_incremented_func$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceRefCountIncremented refcount_incremented_func
     * }
     */
    public static void refcount_incremented_func(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(refcount_incremented_func$LAYOUT, refcount_incremented_func$OFFSET, fieldValue);
    }

    private static final AddressLayout refcount_decremented_func$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("refcount_decremented_func"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceRefCountDecremented refcount_decremented_func
     * }
     */
    public static final AddressLayout refcount_decremented_func$layout() {
        return refcount_decremented_func$LAYOUT;
    }

    private static final long refcount_decremented_func$OFFSET = $LAYOUT.byteOffset(groupElement("refcount_decremented_func"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceRefCountDecremented refcount_decremented_func
     * }
     */
    public static final long refcount_decremented_func$offset() {
        return refcount_decremented_func$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceRefCountDecremented refcount_decremented_func
     * }
     */
    public static MemorySegment refcount_decremented_func(MemorySegment struct) {
        return struct.get(refcount_decremented_func$LAYOUT, refcount_decremented_func$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceRefCountDecremented refcount_decremented_func
     * }
     */
    public static void refcount_decremented_func(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(refcount_decremented_func$LAYOUT, refcount_decremented_func$OFFSET, fieldValue);
    }

    private static final AddressLayout get_script_func$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("get_script_func"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceGetScript get_script_func
     * }
     */
    public static final AddressLayout get_script_func$layout() {
        return get_script_func$LAYOUT;
    }

    private static final long get_script_func$OFFSET = $LAYOUT.byteOffset(groupElement("get_script_func"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceGetScript get_script_func
     * }
     */
    public static final long get_script_func$offset() {
        return get_script_func$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceGetScript get_script_func
     * }
     */
    public static MemorySegment get_script_func(MemorySegment struct) {
        return struct.get(get_script_func$LAYOUT, get_script_func$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceGetScript get_script_func
     * }
     */
    public static void get_script_func(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(get_script_func$LAYOUT, get_script_func$OFFSET, fieldValue);
    }

    private static final AddressLayout is_placeholder_func$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("is_placeholder_func"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceIsPlaceholder is_placeholder_func
     * }
     */
    public static final AddressLayout is_placeholder_func$layout() {
        return is_placeholder_func$LAYOUT;
    }

    private static final long is_placeholder_func$OFFSET = $LAYOUT.byteOffset(groupElement("is_placeholder_func"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceIsPlaceholder is_placeholder_func
     * }
     */
    public static final long is_placeholder_func$offset() {
        return is_placeholder_func$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceIsPlaceholder is_placeholder_func
     * }
     */
    public static MemorySegment is_placeholder_func(MemorySegment struct) {
        return struct.get(is_placeholder_func$LAYOUT, is_placeholder_func$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceIsPlaceholder is_placeholder_func
     * }
     */
    public static void is_placeholder_func(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(is_placeholder_func$LAYOUT, is_placeholder_func$OFFSET, fieldValue);
    }

    private static final AddressLayout set_fallback_func$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("set_fallback_func"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceSet set_fallback_func
     * }
     */
    public static final AddressLayout set_fallback_func$layout() {
        return set_fallback_func$LAYOUT;
    }

    private static final long set_fallback_func$OFFSET = $LAYOUT.byteOffset(groupElement("set_fallback_func"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceSet set_fallback_func
     * }
     */
    public static final long set_fallback_func$offset() {
        return set_fallback_func$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceSet set_fallback_func
     * }
     */
    public static MemorySegment set_fallback_func(MemorySegment struct) {
        return struct.get(set_fallback_func$LAYOUT, set_fallback_func$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceSet set_fallback_func
     * }
     */
    public static void set_fallback_func(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(set_fallback_func$LAYOUT, set_fallback_func$OFFSET, fieldValue);
    }

    private static final AddressLayout get_fallback_func$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("get_fallback_func"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceGet get_fallback_func
     * }
     */
    public static final AddressLayout get_fallback_func$layout() {
        return get_fallback_func$LAYOUT;
    }

    private static final long get_fallback_func$OFFSET = $LAYOUT.byteOffset(groupElement("get_fallback_func"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceGet get_fallback_func
     * }
     */
    public static final long get_fallback_func$offset() {
        return get_fallback_func$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceGet get_fallback_func
     * }
     */
    public static MemorySegment get_fallback_func(MemorySegment struct) {
        return struct.get(get_fallback_func$LAYOUT, get_fallback_func$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceGet get_fallback_func
     * }
     */
    public static void get_fallback_func(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(get_fallback_func$LAYOUT, get_fallback_func$OFFSET, fieldValue);
    }

    private static final AddressLayout get_language_func$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("get_language_func"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceGetLanguage get_language_func
     * }
     */
    public static final AddressLayout get_language_func$layout() {
        return get_language_func$LAYOUT;
    }

    private static final long get_language_func$OFFSET = $LAYOUT.byteOffset(groupElement("get_language_func"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceGetLanguage get_language_func
     * }
     */
    public static final long get_language_func$offset() {
        return get_language_func$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceGetLanguage get_language_func
     * }
     */
    public static MemorySegment get_language_func(MemorySegment struct) {
        return struct.get(get_language_func$LAYOUT, get_language_func$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceGetLanguage get_language_func
     * }
     */
    public static void get_language_func(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(get_language_func$LAYOUT, get_language_func$OFFSET, fieldValue);
    }

    private static final AddressLayout free_func$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("free_func"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceFree free_func
     * }
     */
    public static final AddressLayout free_func$layout() {
        return free_func$LAYOUT;
    }

    private static final long free_func$OFFSET = $LAYOUT.byteOffset(groupElement("free_func"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceFree free_func
     * }
     */
    public static final long free_func$offset() {
        return free_func$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceFree free_func
     * }
     */
    public static MemorySegment free_func(MemorySegment struct) {
        return struct.get(free_func$LAYOUT, free_func$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * GDExtensionScriptInstanceFree free_func
     * }
     */
    public static void free_func(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(free_func$LAYOUT, free_func$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

