// Generated by jextract

package io.github.kingg22.godot;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef GDExtensionInt (*GDExtensionInterfaceStringNewWithUtf16CharsAndLen2)(GDExtensionUninitializedStringPtr, const char16_t *, GDExtensionInt, GDExtensionBool)
 * }
 */
public final class GDExtensionInterfaceStringNewWithUtf16CharsAndLen2 {

    private GDExtensionInterfaceStringNewWithUtf16CharsAndLen2() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        long apply(MemorySegment r_dest, MemorySegment p_contents, long p_char_count, byte p_default_little_endian);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
        gdextension_interface_h.C_LONG,
        gdextension_interface_h.C_POINTER,
        gdextension_interface_h.C_POINTER,
        gdextension_interface_h.C_LONG,
        gdextension_interface_h.C_CHAR
    );

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = gdextension_interface_h.upcallHandle(GDExtensionInterfaceStringNewWithUtf16CharsAndLen2.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(GDExtensionInterfaceStringNewWithUtf16CharsAndLen2.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static long invoke(MemorySegment funcPtr, MemorySegment r_dest, MemorySegment p_contents, long p_char_count, byte p_default_little_endian) {
        try {
            return (long) DOWN$MH.invokeExact(funcPtr, r_dest, p_contents, p_char_count, p_default_little_endian);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

