// Generated by jextract

package io.github.kingg22.godot;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

public class gdextension_interface_h extends gdextension_interface_h$shared {

    gdextension_interface_h() {
        // Should not be called directly
    }

    static final Arena LIBRARY_ARENA = Arena.ofAuto();

    static final SymbolLookup SYMBOL_LOOKUP = SymbolLookup.loaderLookup()
            .or(Linker.nativeLinker().defaultLookup());

    private static final int _STDINT_H = (int)1L;
    /**
     * {@snippet lang=c :
     * #define _STDINT_H 1
     * }
     */
    public static int _STDINT_H() {
        return _STDINT_H;
    }
    private static final int _FEATURES_H = (int)1L;
    /**
     * {@snippet lang=c :
     * #define _FEATURES_H 1
     * }
     */
    public static int _FEATURES_H() {
        return _FEATURES_H;
    }
    private static final int _DEFAULT_SOURCE = (int)1L;
    /**
     * {@snippet lang=c :
     * #define _DEFAULT_SOURCE 1
     * }
     */
    public static int _DEFAULT_SOURCE() {
        return _DEFAULT_SOURCE;
    }
    private static final int __GLIBC_USE_ISOC2X = (int)0L;
    /**
     * {@snippet lang=c :
     * #define __GLIBC_USE_ISOC2X 0
     * }
     */
    public static int __GLIBC_USE_ISOC2X() {
        return __GLIBC_USE_ISOC2X;
    }
    private static final int __USE_ISOC11 = (int)1L;
    /**
     * {@snippet lang=c :
     * #define __USE_ISOC11 1
     * }
     */
    public static int __USE_ISOC11() {
        return __USE_ISOC11;
    }
    private static final int __USE_ISOC99 = (int)1L;
    /**
     * {@snippet lang=c :
     * #define __USE_ISOC99 1
     * }
     */
    public static int __USE_ISOC99() {
        return __USE_ISOC99;
    }
    private static final int __USE_ISOC95 = (int)1L;
    /**
     * {@snippet lang=c :
     * #define __USE_ISOC95 1
     * }
     */
    public static int __USE_ISOC95() {
        return __USE_ISOC95;
    }
    private static final int __USE_POSIX_IMPLICITLY = (int)1L;
    /**
     * {@snippet lang=c :
     * #define __USE_POSIX_IMPLICITLY 1
     * }
     */
    public static int __USE_POSIX_IMPLICITLY() {
        return __USE_POSIX_IMPLICITLY;
    }
    private static final int _POSIX_SOURCE = (int)1L;
    /**
     * {@snippet lang=c :
     * #define _POSIX_SOURCE 1
     * }
     */
    public static int _POSIX_SOURCE() {
        return _POSIX_SOURCE;
    }
    private static final int __USE_POSIX = (int)1L;
    /**
     * {@snippet lang=c :
     * #define __USE_POSIX 1
     * }
     */
    public static int __USE_POSIX() {
        return __USE_POSIX;
    }
    private static final int __USE_POSIX2 = (int)1L;
    /**
     * {@snippet lang=c :
     * #define __USE_POSIX2 1
     * }
     */
    public static int __USE_POSIX2() {
        return __USE_POSIX2;
    }
    private static final int __USE_POSIX199309 = (int)1L;
    /**
     * {@snippet lang=c :
     * #define __USE_POSIX199309 1
     * }
     */
    public static int __USE_POSIX199309() {
        return __USE_POSIX199309;
    }
    private static final int __USE_POSIX199506 = (int)1L;
    /**
     * {@snippet lang=c :
     * #define __USE_POSIX199506 1
     * }
     */
    public static int __USE_POSIX199506() {
        return __USE_POSIX199506;
    }
    private static final int __USE_XOPEN2K = (int)1L;
    /**
     * {@snippet lang=c :
     * #define __USE_XOPEN2K 1
     * }
     */
    public static int __USE_XOPEN2K() {
        return __USE_XOPEN2K;
    }
    private static final int __USE_XOPEN2K8 = (int)1L;
    /**
     * {@snippet lang=c :
     * #define __USE_XOPEN2K8 1
     * }
     */
    public static int __USE_XOPEN2K8() {
        return __USE_XOPEN2K8;
    }
    private static final int _ATFILE_SOURCE = (int)1L;
    /**
     * {@snippet lang=c :
     * #define _ATFILE_SOURCE 1
     * }
     */
    public static int _ATFILE_SOURCE() {
        return _ATFILE_SOURCE;
    }
    private static final int __WORDSIZE = (int)64L;
    /**
     * {@snippet lang=c :
     * #define __WORDSIZE 64
     * }
     */
    public static int __WORDSIZE() {
        return __WORDSIZE;
    }
    private static final int __WORDSIZE_TIME64_COMPAT32 = (int)1L;
    /**
     * {@snippet lang=c :
     * #define __WORDSIZE_TIME64_COMPAT32 1
     * }
     */
    public static int __WORDSIZE_TIME64_COMPAT32() {
        return __WORDSIZE_TIME64_COMPAT32;
    }
    private static final int __SYSCALL_WORDSIZE = (int)64L;
    /**
     * {@snippet lang=c :
     * #define __SYSCALL_WORDSIZE 64
     * }
     */
    public static int __SYSCALL_WORDSIZE() {
        return __SYSCALL_WORDSIZE;
    }
    private static final int __USE_MISC = (int)1L;
    /**
     * {@snippet lang=c :
     * #define __USE_MISC 1
     * }
     */
    public static int __USE_MISC() {
        return __USE_MISC;
    }
    private static final int __USE_ATFILE = (int)1L;
    /**
     * {@snippet lang=c :
     * #define __USE_ATFILE 1
     * }
     */
    public static int __USE_ATFILE() {
        return __USE_ATFILE;
    }
    private static final int __USE_FORTIFY_LEVEL = (int)0L;
    /**
     * {@snippet lang=c :
     * #define __USE_FORTIFY_LEVEL 0
     * }
     */
    public static int __USE_FORTIFY_LEVEL() {
        return __USE_FORTIFY_LEVEL;
    }
    private static final int __GLIBC_USE_DEPRECATED_GETS = (int)0L;
    /**
     * {@snippet lang=c :
     * #define __GLIBC_USE_DEPRECATED_GETS 0
     * }
     */
    public static int __GLIBC_USE_DEPRECATED_GETS() {
        return __GLIBC_USE_DEPRECATED_GETS;
    }
    private static final int __GLIBC_USE_DEPRECATED_SCANF = (int)0L;
    /**
     * {@snippet lang=c :
     * #define __GLIBC_USE_DEPRECATED_SCANF 0
     * }
     */
    public static int __GLIBC_USE_DEPRECATED_SCANF() {
        return __GLIBC_USE_DEPRECATED_SCANF;
    }
    private static final int __GLIBC_USE_C2X_STRTOL = (int)0L;
    /**
     * {@snippet lang=c :
     * #define __GLIBC_USE_C2X_STRTOL 0
     * }
     */
    public static int __GLIBC_USE_C2X_STRTOL() {
        return __GLIBC_USE_C2X_STRTOL;
    }
    private static final int _STDC_PREDEF_H = (int)1L;
    /**
     * {@snippet lang=c :
     * #define _STDC_PREDEF_H 1
     * }
     */
    public static int _STDC_PREDEF_H() {
        return _STDC_PREDEF_H;
    }
    private static final int __STDC_IEC_559__ = (int)1L;
    /**
     * {@snippet lang=c :
     * #define __STDC_IEC_559__ 1
     * }
     */
    public static int __STDC_IEC_559__() {
        return __STDC_IEC_559__;
    }
    private static final int __STDC_IEC_559_COMPLEX__ = (int)1L;
    /**
     * {@snippet lang=c :
     * #define __STDC_IEC_559_COMPLEX__ 1
     * }
     */
    public static int __STDC_IEC_559_COMPLEX__() {
        return __STDC_IEC_559_COMPLEX__;
    }
    private static final int __GNU_LIBRARY__ = (int)6L;
    /**
     * {@snippet lang=c :
     * #define __GNU_LIBRARY__ 6
     * }
     */
    public static int __GNU_LIBRARY__() {
        return __GNU_LIBRARY__;
    }
    private static final int __GLIBC__ = (int)2L;
    /**
     * {@snippet lang=c :
     * #define __GLIBC__ 2
     * }
     */
    public static int __GLIBC__() {
        return __GLIBC__;
    }
    private static final int __GLIBC_MINOR__ = (int)39L;
    /**
     * {@snippet lang=c :
     * #define __GLIBC_MINOR__ 39
     * }
     */
    public static int __GLIBC_MINOR__() {
        return __GLIBC_MINOR__;
    }
    private static final int _SYS_CDEFS_H = (int)1L;
    /**
     * {@snippet lang=c :
     * #define _SYS_CDEFS_H 1
     * }
     */
    public static int _SYS_CDEFS_H() {
        return _SYS_CDEFS_H;
    }
    private static final int __glibc_c99_flexarr_available = (int)1L;
    /**
     * {@snippet lang=c :
     * #define __glibc_c99_flexarr_available 1
     * }
     */
    public static int __glibc_c99_flexarr_available() {
        return __glibc_c99_flexarr_available;
    }
    private static final int __LDOUBLE_REDIRECTS_TO_FLOAT128_ABI = (int)0L;
    /**
     * {@snippet lang=c :
     * #define __LDOUBLE_REDIRECTS_TO_FLOAT128_ABI 0
     * }
     */
    public static int __LDOUBLE_REDIRECTS_TO_FLOAT128_ABI() {
        return __LDOUBLE_REDIRECTS_TO_FLOAT128_ABI;
    }
    private static final int __HAVE_GENERIC_SELECTION = (int)1L;
    /**
     * {@snippet lang=c :
     * #define __HAVE_GENERIC_SELECTION 1
     * }
     */
    public static int __HAVE_GENERIC_SELECTION() {
        return __HAVE_GENERIC_SELECTION;
    }
    private static final int __GLIBC_USE_LIB_EXT2 = (int)0L;
    /**
     * {@snippet lang=c :
     * #define __GLIBC_USE_LIB_EXT2 0
     * }
     */
    public static int __GLIBC_USE_LIB_EXT2() {
        return __GLIBC_USE_LIB_EXT2;
    }
    private static final int __GLIBC_USE_IEC_60559_BFP_EXT = (int)0L;
    /**
     * {@snippet lang=c :
     * #define __GLIBC_USE_IEC_60559_BFP_EXT 0
     * }
     */
    public static int __GLIBC_USE_IEC_60559_BFP_EXT() {
        return __GLIBC_USE_IEC_60559_BFP_EXT;
    }
    private static final int __GLIBC_USE_IEC_60559_BFP_EXT_C2X = (int)0L;
    /**
     * {@snippet lang=c :
     * #define __GLIBC_USE_IEC_60559_BFP_EXT_C2X 0
     * }
     */
    public static int __GLIBC_USE_IEC_60559_BFP_EXT_C2X() {
        return __GLIBC_USE_IEC_60559_BFP_EXT_C2X;
    }
    private static final int __GLIBC_USE_IEC_60559_EXT = (int)0L;
    /**
     * {@snippet lang=c :
     * #define __GLIBC_USE_IEC_60559_EXT 0
     * }
     */
    public static int __GLIBC_USE_IEC_60559_EXT() {
        return __GLIBC_USE_IEC_60559_EXT;
    }
    private static final int __GLIBC_USE_IEC_60559_FUNCS_EXT = (int)0L;
    /**
     * {@snippet lang=c :
     * #define __GLIBC_USE_IEC_60559_FUNCS_EXT 0
     * }
     */
    public static int __GLIBC_USE_IEC_60559_FUNCS_EXT() {
        return __GLIBC_USE_IEC_60559_FUNCS_EXT;
    }
    private static final int __GLIBC_USE_IEC_60559_FUNCS_EXT_C2X = (int)0L;
    /**
     * {@snippet lang=c :
     * #define __GLIBC_USE_IEC_60559_FUNCS_EXT_C2X 0
     * }
     */
    public static int __GLIBC_USE_IEC_60559_FUNCS_EXT_C2X() {
        return __GLIBC_USE_IEC_60559_FUNCS_EXT_C2X;
    }
    private static final int __GLIBC_USE_IEC_60559_TYPES_EXT = (int)0L;
    /**
     * {@snippet lang=c :
     * #define __GLIBC_USE_IEC_60559_TYPES_EXT 0
     * }
     */
    public static int __GLIBC_USE_IEC_60559_TYPES_EXT() {
        return __GLIBC_USE_IEC_60559_TYPES_EXT;
    }
    private static final int _BITS_TYPES_H = (int)1L;
    /**
     * {@snippet lang=c :
     * #define _BITS_TYPES_H 1
     * }
     */
    public static int _BITS_TYPES_H() {
        return _BITS_TYPES_H;
    }
    private static final int _BITS_TYPESIZES_H = (int)1L;
    /**
     * {@snippet lang=c :
     * #define _BITS_TYPESIZES_H 1
     * }
     */
    public static int _BITS_TYPESIZES_H() {
        return _BITS_TYPESIZES_H;
    }
    private static final int __OFF_T_MATCHES_OFF64_T = (int)1L;
    /**
     * {@snippet lang=c :
     * #define __OFF_T_MATCHES_OFF64_T 1
     * }
     */
    public static int __OFF_T_MATCHES_OFF64_T() {
        return __OFF_T_MATCHES_OFF64_T;
    }
    private static final int __INO_T_MATCHES_INO64_T = (int)1L;
    /**
     * {@snippet lang=c :
     * #define __INO_T_MATCHES_INO64_T 1
     * }
     */
    public static int __INO_T_MATCHES_INO64_T() {
        return __INO_T_MATCHES_INO64_T;
    }
    private static final int __RLIM_T_MATCHES_RLIM64_T = (int)1L;
    /**
     * {@snippet lang=c :
     * #define __RLIM_T_MATCHES_RLIM64_T 1
     * }
     */
    public static int __RLIM_T_MATCHES_RLIM64_T() {
        return __RLIM_T_MATCHES_RLIM64_T;
    }
    private static final int __STATFS_MATCHES_STATFS64 = (int)1L;
    /**
     * {@snippet lang=c :
     * #define __STATFS_MATCHES_STATFS64 1
     * }
     */
    public static int __STATFS_MATCHES_STATFS64() {
        return __STATFS_MATCHES_STATFS64;
    }
    private static final int __KERNEL_OLD_TIMEVAL_MATCHES_TIMEVAL64 = (int)1L;
    /**
     * {@snippet lang=c :
     * #define __KERNEL_OLD_TIMEVAL_MATCHES_TIMEVAL64 1
     * }
     */
    public static int __KERNEL_OLD_TIMEVAL_MATCHES_TIMEVAL64() {
        return __KERNEL_OLD_TIMEVAL_MATCHES_TIMEVAL64;
    }
    private static final int __FD_SETSIZE = (int)1024L;
    /**
     * {@snippet lang=c :
     * #define __FD_SETSIZE 1024
     * }
     */
    public static int __FD_SETSIZE() {
        return __FD_SETSIZE;
    }
    private static final int _BITS_TIME64_H = (int)1L;
    /**
     * {@snippet lang=c :
     * #define _BITS_TIME64_H 1
     * }
     */
    public static int _BITS_TIME64_H() {
        return _BITS_TIME64_H;
    }
    private static final int _BITS_WCHAR_H = (int)1L;
    /**
     * {@snippet lang=c :
     * #define _BITS_WCHAR_H 1
     * }
     */
    public static int _BITS_WCHAR_H() {
        return _BITS_WCHAR_H;
    }
    private static final int _BITS_STDINT_INTN_H = (int)1L;
    /**
     * {@snippet lang=c :
     * #define _BITS_STDINT_INTN_H 1
     * }
     */
    public static int _BITS_STDINT_INTN_H() {
        return _BITS_STDINT_INTN_H;
    }
    private static final int _BITS_STDINT_UINTN_H = (int)1L;
    /**
     * {@snippet lang=c :
     * #define _BITS_STDINT_UINTN_H 1
     * }
     */
    public static int _BITS_STDINT_UINTN_H() {
        return _BITS_STDINT_UINTN_H;
    }
    private static final int _BITS_STDINT_LEAST_H = (int)1L;
    /**
     * {@snippet lang=c :
     * #define _BITS_STDINT_LEAST_H 1
     * }
     */
    public static int _BITS_STDINT_LEAST_H() {
        return _BITS_STDINT_LEAST_H;
    }
    /**
     * {@snippet lang=c :
     * typedef long ptrdiff_t
     * }
     */
    public static final OfLong ptrdiff_t = gdextension_interface_h.C_LONG;
    /**
     * {@snippet lang=c :
     * typedef unsigned long size_t
     * }
     */
    public static final OfLong size_t = gdextension_interface_h.C_LONG;
    /**
     * {@snippet lang=c :
     * typedef int wchar_t
     * }
     */
    public static final OfInt wchar_t = gdextension_interface_h.C_INT;
    /**
     * {@snippet lang=c :
     * typedef unsigned char __u_char
     * }
     */
    public static final OfByte __u_char = gdextension_interface_h.C_CHAR;
    /**
     * {@snippet lang=c :
     * typedef unsigned short __u_short
     * }
     */
    public static final OfShort __u_short = gdextension_interface_h.C_SHORT;
    /**
     * {@snippet lang=c :
     * typedef unsigned int __u_int
     * }
     */
    public static final OfInt __u_int = gdextension_interface_h.C_INT;
    /**
     * {@snippet lang=c :
     * typedef unsigned long __u_long
     * }
     */
    public static final OfLong __u_long = gdextension_interface_h.C_LONG;
    /**
     * {@snippet lang=c :
     * typedef signed char __int8_t
     * }
     */
    public static final OfByte __int8_t = gdextension_interface_h.C_CHAR;
    /**
     * {@snippet lang=c :
     * typedef unsigned char __uint8_t
     * }
     */
    public static final OfByte __uint8_t = gdextension_interface_h.C_CHAR;
    /**
     * {@snippet lang=c :
     * typedef short __int16_t
     * }
     */
    public static final OfShort __int16_t = gdextension_interface_h.C_SHORT;
    /**
     * {@snippet lang=c :
     * typedef unsigned short __uint16_t
     * }
     */
    public static final OfShort __uint16_t = gdextension_interface_h.C_SHORT;
    /**
     * {@snippet lang=c :
     * typedef int __int32_t
     * }
     */
    public static final OfInt __int32_t = gdextension_interface_h.C_INT;
    /**
     * {@snippet lang=c :
     * typedef unsigned int __uint32_t
     * }
     */
    public static final OfInt __uint32_t = gdextension_interface_h.C_INT;
    /**
     * {@snippet lang=c :
     * typedef long __int64_t
     * }
     */
    public static final OfLong __int64_t = gdextension_interface_h.C_LONG;
    /**
     * {@snippet lang=c :
     * typedef unsigned long __uint64_t
     * }
     */
    public static final OfLong __uint64_t = gdextension_interface_h.C_LONG;
    /**
     * {@snippet lang=c :
     * typedef __int8_t __int_least8_t
     * }
     */
    public static final OfByte __int_least8_t = gdextension_interface_h.C_CHAR;
    /**
     * {@snippet lang=c :
     * typedef __uint8_t __uint_least8_t
     * }
     */
    public static final OfByte __uint_least8_t = gdextension_interface_h.C_CHAR;
    /**
     * {@snippet lang=c :
     * typedef __int16_t __int_least16_t
     * }
     */
    public static final OfShort __int_least16_t = gdextension_interface_h.C_SHORT;
    /**
     * {@snippet lang=c :
     * typedef __uint16_t __uint_least16_t
     * }
     */
    public static final OfShort __uint_least16_t = gdextension_interface_h.C_SHORT;
    /**
     * {@snippet lang=c :
     * typedef __int32_t __int_least32_t
     * }
     */
    public static final OfInt __int_least32_t = gdextension_interface_h.C_INT;
    /**
     * {@snippet lang=c :
     * typedef __uint32_t __uint_least32_t
     * }
     */
    public static final OfInt __uint_least32_t = gdextension_interface_h.C_INT;
    /**
     * {@snippet lang=c :
     * typedef __int64_t __int_least64_t
     * }
     */
    public static final OfLong __int_least64_t = gdextension_interface_h.C_LONG;
    /**
     * {@snippet lang=c :
     * typedef __uint64_t __uint_least64_t
     * }
     */
    public static final OfLong __uint_least64_t = gdextension_interface_h.C_LONG;
    /**
     * {@snippet lang=c :
     * typedef long __quad_t
     * }
     */
    public static final OfLong __quad_t = gdextension_interface_h.C_LONG;
    /**
     * {@snippet lang=c :
     * typedef unsigned long __u_quad_t
     * }
     */
    public static final OfLong __u_quad_t = gdextension_interface_h.C_LONG;
    /**
     * {@snippet lang=c :
     * typedef long __intmax_t
     * }
     */
    public static final OfLong __intmax_t = gdextension_interface_h.C_LONG;
    /**
     * {@snippet lang=c :
     * typedef unsigned long __uintmax_t
     * }
     */
    public static final OfLong __uintmax_t = gdextension_interface_h.C_LONG;
    /**
     * {@snippet lang=c :
     * typedef unsigned long __dev_t
     * }
     */
    public static final OfLong __dev_t = gdextension_interface_h.C_LONG;
    /**
     * {@snippet lang=c :
     * typedef unsigned int __uid_t
     * }
     */
    public static final OfInt __uid_t = gdextension_interface_h.C_INT;
    /**
     * {@snippet lang=c :
     * typedef unsigned int __gid_t
     * }
     */
    public static final OfInt __gid_t = gdextension_interface_h.C_INT;
    /**
     * {@snippet lang=c :
     * typedef unsigned long __ino_t
     * }
     */
    public static final OfLong __ino_t = gdextension_interface_h.C_LONG;
    /**
     * {@snippet lang=c :
     * typedef unsigned long __ino64_t
     * }
     */
    public static final OfLong __ino64_t = gdextension_interface_h.C_LONG;
    /**
     * {@snippet lang=c :
     * typedef unsigned int __mode_t
     * }
     */
    public static final OfInt __mode_t = gdextension_interface_h.C_INT;
    /**
     * {@snippet lang=c :
     * typedef unsigned long __nlink_t
     * }
     */
    public static final OfLong __nlink_t = gdextension_interface_h.C_LONG;
    /**
     * {@snippet lang=c :
     * typedef long __off_t
     * }
     */
    public static final OfLong __off_t = gdextension_interface_h.C_LONG;
    /**
     * {@snippet lang=c :
     * typedef long __off64_t
     * }
     */
    public static final OfLong __off64_t = gdextension_interface_h.C_LONG;
    /**
     * {@snippet lang=c :
     * typedef int __pid_t
     * }
     */
    public static final OfInt __pid_t = gdextension_interface_h.C_INT;
    /**
     * {@snippet lang=c :
     * typedef long __clock_t
     * }
     */
    public static final OfLong __clock_t = gdextension_interface_h.C_LONG;
    /**
     * {@snippet lang=c :
     * typedef unsigned long __rlim_t
     * }
     */
    public static final OfLong __rlim_t = gdextension_interface_h.C_LONG;
    /**
     * {@snippet lang=c :
     * typedef unsigned long __rlim64_t
     * }
     */
    public static final OfLong __rlim64_t = gdextension_interface_h.C_LONG;
    /**
     * {@snippet lang=c :
     * typedef unsigned int __id_t
     * }
     */
    public static final OfInt __id_t = gdextension_interface_h.C_INT;
    /**
     * {@snippet lang=c :
     * typedef long __time_t
     * }
     */
    public static final OfLong __time_t = gdextension_interface_h.C_LONG;
    /**
     * {@snippet lang=c :
     * typedef unsigned int __useconds_t
     * }
     */
    public static final OfInt __useconds_t = gdextension_interface_h.C_INT;
    /**
     * {@snippet lang=c :
     * typedef long __suseconds_t
     * }
     */
    public static final OfLong __suseconds_t = gdextension_interface_h.C_LONG;
    /**
     * {@snippet lang=c :
     * typedef long __suseconds64_t
     * }
     */
    public static final OfLong __suseconds64_t = gdextension_interface_h.C_LONG;
    /**
     * {@snippet lang=c :
     * typedef int __daddr_t
     * }
     */
    public static final OfInt __daddr_t = gdextension_interface_h.C_INT;
    /**
     * {@snippet lang=c :
     * typedef int __key_t
     * }
     */
    public static final OfInt __key_t = gdextension_interface_h.C_INT;
    /**
     * {@snippet lang=c :
     * typedef int __clockid_t
     * }
     */
    public static final OfInt __clockid_t = gdextension_interface_h.C_INT;
    /**
     * {@snippet lang=c :
     * typedef void *__timer_t
     * }
     */
    public static final AddressLayout __timer_t = gdextension_interface_h.C_POINTER;
    /**
     * {@snippet lang=c :
     * typedef long __blksize_t
     * }
     */
    public static final OfLong __blksize_t = gdextension_interface_h.C_LONG;
    /**
     * {@snippet lang=c :
     * typedef long __blkcnt_t
     * }
     */
    public static final OfLong __blkcnt_t = gdextension_interface_h.C_LONG;
    /**
     * {@snippet lang=c :
     * typedef long __blkcnt64_t
     * }
     */
    public static final OfLong __blkcnt64_t = gdextension_interface_h.C_LONG;
    /**
     * {@snippet lang=c :
     * typedef unsigned long __fsblkcnt_t
     * }
     */
    public static final OfLong __fsblkcnt_t = gdextension_interface_h.C_LONG;
    /**
     * {@snippet lang=c :
     * typedef unsigned long __fsblkcnt64_t
     * }
     */
    public static final OfLong __fsblkcnt64_t = gdextension_interface_h.C_LONG;
    /**
     * {@snippet lang=c :
     * typedef unsigned long __fsfilcnt_t
     * }
     */
    public static final OfLong __fsfilcnt_t = gdextension_interface_h.C_LONG;
    /**
     * {@snippet lang=c :
     * typedef unsigned long __fsfilcnt64_t
     * }
     */
    public static final OfLong __fsfilcnt64_t = gdextension_interface_h.C_LONG;
    /**
     * {@snippet lang=c :
     * typedef long __fsword_t
     * }
     */
    public static final OfLong __fsword_t = gdextension_interface_h.C_LONG;
    /**
     * {@snippet lang=c :
     * typedef long __ssize_t
     * }
     */
    public static final OfLong __ssize_t = gdextension_interface_h.C_LONG;
    /**
     * {@snippet lang=c :
     * typedef long __syscall_slong_t
     * }
     */
    public static final OfLong __syscall_slong_t = gdextension_interface_h.C_LONG;
    /**
     * {@snippet lang=c :
     * typedef unsigned long __syscall_ulong_t
     * }
     */
    public static final OfLong __syscall_ulong_t = gdextension_interface_h.C_LONG;
    /**
     * {@snippet lang=c :
     * typedef __off64_t __loff_t
     * }
     */
    public static final OfLong __loff_t = gdextension_interface_h.C_LONG;
    /**
     * {@snippet lang=c :
     * typedef char *__caddr_t
     * }
     */
    public static final AddressLayout __caddr_t = gdextension_interface_h.C_POINTER;
    /**
     * {@snippet lang=c :
     * typedef long __intptr_t
     * }
     */
    public static final OfLong __intptr_t = gdextension_interface_h.C_LONG;
    /**
     * {@snippet lang=c :
     * typedef unsigned int __socklen_t
     * }
     */
    public static final OfInt __socklen_t = gdextension_interface_h.C_INT;
    /**
     * {@snippet lang=c :
     * typedef int __sig_atomic_t
     * }
     */
    public static final OfInt __sig_atomic_t = gdextension_interface_h.C_INT;
    /**
     * {@snippet lang=c :
     * typedef __int8_t int8_t
     * }
     */
    public static final OfByte int8_t = gdextension_interface_h.C_CHAR;
    /**
     * {@snippet lang=c :
     * typedef __int16_t int16_t
     * }
     */
    public static final OfShort int16_t = gdextension_interface_h.C_SHORT;
    /**
     * {@snippet lang=c :
     * typedef __int32_t int32_t
     * }
     */
    public static final OfInt int32_t = gdextension_interface_h.C_INT;
    /**
     * {@snippet lang=c :
     * typedef __int64_t int64_t
     * }
     */
    public static final OfLong int64_t = gdextension_interface_h.C_LONG;
    /**
     * {@snippet lang=c :
     * typedef __uint8_t uint8_t
     * }
     */
    public static final OfByte uint8_t = gdextension_interface_h.C_CHAR;
    /**
     * {@snippet lang=c :
     * typedef __uint16_t uint16_t
     * }
     */
    public static final OfShort uint16_t = gdextension_interface_h.C_SHORT;
    /**
     * {@snippet lang=c :
     * typedef __uint32_t uint32_t
     * }
     */
    public static final OfInt uint32_t = gdextension_interface_h.C_INT;
    /**
     * {@snippet lang=c :
     * typedef __uint64_t uint64_t
     * }
     */
    public static final OfLong uint64_t = gdextension_interface_h.C_LONG;
    /**
     * {@snippet lang=c :
     * typedef __int_least8_t int_least8_t
     * }
     */
    public static final OfByte int_least8_t = gdextension_interface_h.C_CHAR;
    /**
     * {@snippet lang=c :
     * typedef __int_least16_t int_least16_t
     * }
     */
    public static final OfShort int_least16_t = gdextension_interface_h.C_SHORT;
    /**
     * {@snippet lang=c :
     * typedef __int_least32_t int_least32_t
     * }
     */
    public static final OfInt int_least32_t = gdextension_interface_h.C_INT;
    /**
     * {@snippet lang=c :
     * typedef __int_least64_t int_least64_t
     * }
     */
    public static final OfLong int_least64_t = gdextension_interface_h.C_LONG;
    /**
     * {@snippet lang=c :
     * typedef __uint_least8_t uint_least8_t
     * }
     */
    public static final OfByte uint_least8_t = gdextension_interface_h.C_CHAR;
    /**
     * {@snippet lang=c :
     * typedef __uint_least16_t uint_least16_t
     * }
     */
    public static final OfShort uint_least16_t = gdextension_interface_h.C_SHORT;
    /**
     * {@snippet lang=c :
     * typedef __uint_least32_t uint_least32_t
     * }
     */
    public static final OfInt uint_least32_t = gdextension_interface_h.C_INT;
    /**
     * {@snippet lang=c :
     * typedef __uint_least64_t uint_least64_t
     * }
     */
    public static final OfLong uint_least64_t = gdextension_interface_h.C_LONG;
    /**
     * {@snippet lang=c :
     * typedef signed char int_fast8_t
     * }
     */
    public static final OfByte int_fast8_t = gdextension_interface_h.C_CHAR;
    /**
     * {@snippet lang=c :
     * typedef long int_fast16_t
     * }
     */
    public static final OfLong int_fast16_t = gdextension_interface_h.C_LONG;
    /**
     * {@snippet lang=c :
     * typedef long int_fast32_t
     * }
     */
    public static final OfLong int_fast32_t = gdextension_interface_h.C_LONG;
    /**
     * {@snippet lang=c :
     * typedef long int_fast64_t
     * }
     */
    public static final OfLong int_fast64_t = gdextension_interface_h.C_LONG;
    /**
     * {@snippet lang=c :
     * typedef unsigned char uint_fast8_t
     * }
     */
    public static final OfByte uint_fast8_t = gdextension_interface_h.C_CHAR;
    /**
     * {@snippet lang=c :
     * typedef unsigned long uint_fast16_t
     * }
     */
    public static final OfLong uint_fast16_t = gdextension_interface_h.C_LONG;
    /**
     * {@snippet lang=c :
     * typedef unsigned long uint_fast32_t
     * }
     */
    public static final OfLong uint_fast32_t = gdextension_interface_h.C_LONG;
    /**
     * {@snippet lang=c :
     * typedef unsigned long uint_fast64_t
     * }
     */
    public static final OfLong uint_fast64_t = gdextension_interface_h.C_LONG;
    /**
     * {@snippet lang=c :
     * typedef long intptr_t
     * }
     */
    public static final OfLong intptr_t = gdextension_interface_h.C_LONG;
    /**
     * {@snippet lang=c :
     * typedef unsigned long uintptr_t
     * }
     */
    public static final OfLong uintptr_t = gdextension_interface_h.C_LONG;
    /**
     * {@snippet lang=c :
     * typedef __intmax_t intmax_t
     * }
     */
    public static final OfLong intmax_t = gdextension_interface_h.C_LONG;
    /**
     * {@snippet lang=c :
     * typedef __uintmax_t uintmax_t
     * }
     */
    public static final OfLong uintmax_t = gdextension_interface_h.C_LONG;
    /**
     * {@snippet lang=c :
     * typedef uint32_t char32_t
     * }
     */
    public static final OfInt char32_t = gdextension_interface_h.C_INT;
    /**
     * {@snippet lang=c :
     * typedef uint16_t char16_t
     * }
     */
    public static final OfShort char16_t = gdextension_interface_h.C_SHORT;
    private static final int GDEXTENSION_VARIANT_TYPE_NIL = (int)0L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_VARIANT_TYPE_NIL = 0
     * }
     */
    public static int GDEXTENSION_VARIANT_TYPE_NIL() {
        return GDEXTENSION_VARIANT_TYPE_NIL;
    }
    private static final int GDEXTENSION_VARIANT_TYPE_BOOL = (int)1L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_VARIANT_TYPE_BOOL = 1
     * }
     */
    public static int GDEXTENSION_VARIANT_TYPE_BOOL() {
        return GDEXTENSION_VARIANT_TYPE_BOOL;
    }
    private static final int GDEXTENSION_VARIANT_TYPE_INT = (int)2L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_VARIANT_TYPE_INT = 2
     * }
     */
    public static int GDEXTENSION_VARIANT_TYPE_INT() {
        return GDEXTENSION_VARIANT_TYPE_INT;
    }
    private static final int GDEXTENSION_VARIANT_TYPE_FLOAT = (int)3L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_VARIANT_TYPE_FLOAT = 3
     * }
     */
    public static int GDEXTENSION_VARIANT_TYPE_FLOAT() {
        return GDEXTENSION_VARIANT_TYPE_FLOAT;
    }
    private static final int GDEXTENSION_VARIANT_TYPE_STRING = (int)4L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_VARIANT_TYPE_STRING = 4
     * }
     */
    public static int GDEXTENSION_VARIANT_TYPE_STRING() {
        return GDEXTENSION_VARIANT_TYPE_STRING;
    }
    private static final int GDEXTENSION_VARIANT_TYPE_VECTOR2 = (int)5L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_VARIANT_TYPE_VECTOR2 = 5
     * }
     */
    public static int GDEXTENSION_VARIANT_TYPE_VECTOR2() {
        return GDEXTENSION_VARIANT_TYPE_VECTOR2;
    }
    private static final int GDEXTENSION_VARIANT_TYPE_VECTOR2I = (int)6L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_VARIANT_TYPE_VECTOR2I = 6
     * }
     */
    public static int GDEXTENSION_VARIANT_TYPE_VECTOR2I() {
        return GDEXTENSION_VARIANT_TYPE_VECTOR2I;
    }
    private static final int GDEXTENSION_VARIANT_TYPE_RECT2 = (int)7L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_VARIANT_TYPE_RECT2 = 7
     * }
     */
    public static int GDEXTENSION_VARIANT_TYPE_RECT2() {
        return GDEXTENSION_VARIANT_TYPE_RECT2;
    }
    private static final int GDEXTENSION_VARIANT_TYPE_RECT2I = (int)8L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_VARIANT_TYPE_RECT2I = 8
     * }
     */
    public static int GDEXTENSION_VARIANT_TYPE_RECT2I() {
        return GDEXTENSION_VARIANT_TYPE_RECT2I;
    }
    private static final int GDEXTENSION_VARIANT_TYPE_VECTOR3 = (int)9L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_VARIANT_TYPE_VECTOR3 = 9
     * }
     */
    public static int GDEXTENSION_VARIANT_TYPE_VECTOR3() {
        return GDEXTENSION_VARIANT_TYPE_VECTOR3;
    }
    private static final int GDEXTENSION_VARIANT_TYPE_VECTOR3I = (int)10L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_VARIANT_TYPE_VECTOR3I = 10
     * }
     */
    public static int GDEXTENSION_VARIANT_TYPE_VECTOR3I() {
        return GDEXTENSION_VARIANT_TYPE_VECTOR3I;
    }
    private static final int GDEXTENSION_VARIANT_TYPE_TRANSFORM2D = (int)11L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_VARIANT_TYPE_TRANSFORM2D = 11
     * }
     */
    public static int GDEXTENSION_VARIANT_TYPE_TRANSFORM2D() {
        return GDEXTENSION_VARIANT_TYPE_TRANSFORM2D;
    }
    private static final int GDEXTENSION_VARIANT_TYPE_VECTOR4 = (int)12L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_VARIANT_TYPE_VECTOR4 = 12
     * }
     */
    public static int GDEXTENSION_VARIANT_TYPE_VECTOR4() {
        return GDEXTENSION_VARIANT_TYPE_VECTOR4;
    }
    private static final int GDEXTENSION_VARIANT_TYPE_VECTOR4I = (int)13L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_VARIANT_TYPE_VECTOR4I = 13
     * }
     */
    public static int GDEXTENSION_VARIANT_TYPE_VECTOR4I() {
        return GDEXTENSION_VARIANT_TYPE_VECTOR4I;
    }
    private static final int GDEXTENSION_VARIANT_TYPE_PLANE = (int)14L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_VARIANT_TYPE_PLANE = 14
     * }
     */
    public static int GDEXTENSION_VARIANT_TYPE_PLANE() {
        return GDEXTENSION_VARIANT_TYPE_PLANE;
    }
    private static final int GDEXTENSION_VARIANT_TYPE_QUATERNION = (int)15L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_VARIANT_TYPE_QUATERNION = 15
     * }
     */
    public static int GDEXTENSION_VARIANT_TYPE_QUATERNION() {
        return GDEXTENSION_VARIANT_TYPE_QUATERNION;
    }
    private static final int GDEXTENSION_VARIANT_TYPE_AABB = (int)16L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_VARIANT_TYPE_AABB = 16
     * }
     */
    public static int GDEXTENSION_VARIANT_TYPE_AABB() {
        return GDEXTENSION_VARIANT_TYPE_AABB;
    }
    private static final int GDEXTENSION_VARIANT_TYPE_BASIS = (int)17L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_VARIANT_TYPE_BASIS = 17
     * }
     */
    public static int GDEXTENSION_VARIANT_TYPE_BASIS() {
        return GDEXTENSION_VARIANT_TYPE_BASIS;
    }
    private static final int GDEXTENSION_VARIANT_TYPE_TRANSFORM3D = (int)18L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_VARIANT_TYPE_TRANSFORM3D = 18
     * }
     */
    public static int GDEXTENSION_VARIANT_TYPE_TRANSFORM3D() {
        return GDEXTENSION_VARIANT_TYPE_TRANSFORM3D;
    }
    private static final int GDEXTENSION_VARIANT_TYPE_PROJECTION = (int)19L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_VARIANT_TYPE_PROJECTION = 19
     * }
     */
    public static int GDEXTENSION_VARIANT_TYPE_PROJECTION() {
        return GDEXTENSION_VARIANT_TYPE_PROJECTION;
    }
    private static final int GDEXTENSION_VARIANT_TYPE_COLOR = (int)20L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_VARIANT_TYPE_COLOR = 20
     * }
     */
    public static int GDEXTENSION_VARIANT_TYPE_COLOR() {
        return GDEXTENSION_VARIANT_TYPE_COLOR;
    }
    private static final int GDEXTENSION_VARIANT_TYPE_STRING_NAME = (int)21L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_VARIANT_TYPE_STRING_NAME = 21
     * }
     */
    public static int GDEXTENSION_VARIANT_TYPE_STRING_NAME() {
        return GDEXTENSION_VARIANT_TYPE_STRING_NAME;
    }
    private static final int GDEXTENSION_VARIANT_TYPE_NODE_PATH = (int)22L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_VARIANT_TYPE_NODE_PATH = 22
     * }
     */
    public static int GDEXTENSION_VARIANT_TYPE_NODE_PATH() {
        return GDEXTENSION_VARIANT_TYPE_NODE_PATH;
    }
    private static final int GDEXTENSION_VARIANT_TYPE_RID = (int)23L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_VARIANT_TYPE_RID = 23
     * }
     */
    public static int GDEXTENSION_VARIANT_TYPE_RID() {
        return GDEXTENSION_VARIANT_TYPE_RID;
    }
    private static final int GDEXTENSION_VARIANT_TYPE_OBJECT = (int)24L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_VARIANT_TYPE_OBJECT = 24
     * }
     */
    public static int GDEXTENSION_VARIANT_TYPE_OBJECT() {
        return GDEXTENSION_VARIANT_TYPE_OBJECT;
    }
    private static final int GDEXTENSION_VARIANT_TYPE_CALLABLE = (int)25L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_VARIANT_TYPE_CALLABLE = 25
     * }
     */
    public static int GDEXTENSION_VARIANT_TYPE_CALLABLE() {
        return GDEXTENSION_VARIANT_TYPE_CALLABLE;
    }
    private static final int GDEXTENSION_VARIANT_TYPE_SIGNAL = (int)26L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_VARIANT_TYPE_SIGNAL = 26
     * }
     */
    public static int GDEXTENSION_VARIANT_TYPE_SIGNAL() {
        return GDEXTENSION_VARIANT_TYPE_SIGNAL;
    }
    private static final int GDEXTENSION_VARIANT_TYPE_DICTIONARY = (int)27L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_VARIANT_TYPE_DICTIONARY = 27
     * }
     */
    public static int GDEXTENSION_VARIANT_TYPE_DICTIONARY() {
        return GDEXTENSION_VARIANT_TYPE_DICTIONARY;
    }
    private static final int GDEXTENSION_VARIANT_TYPE_ARRAY = (int)28L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_VARIANT_TYPE_ARRAY = 28
     * }
     */
    public static int GDEXTENSION_VARIANT_TYPE_ARRAY() {
        return GDEXTENSION_VARIANT_TYPE_ARRAY;
    }
    private static final int GDEXTENSION_VARIANT_TYPE_PACKED_BYTE_ARRAY = (int)29L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_VARIANT_TYPE_PACKED_BYTE_ARRAY = 29
     * }
     */
    public static int GDEXTENSION_VARIANT_TYPE_PACKED_BYTE_ARRAY() {
        return GDEXTENSION_VARIANT_TYPE_PACKED_BYTE_ARRAY;
    }
    private static final int GDEXTENSION_VARIANT_TYPE_PACKED_INT32_ARRAY = (int)30L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_VARIANT_TYPE_PACKED_INT32_ARRAY = 30
     * }
     */
    public static int GDEXTENSION_VARIANT_TYPE_PACKED_INT32_ARRAY() {
        return GDEXTENSION_VARIANT_TYPE_PACKED_INT32_ARRAY;
    }
    private static final int GDEXTENSION_VARIANT_TYPE_PACKED_INT64_ARRAY = (int)31L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_VARIANT_TYPE_PACKED_INT64_ARRAY = 31
     * }
     */
    public static int GDEXTENSION_VARIANT_TYPE_PACKED_INT64_ARRAY() {
        return GDEXTENSION_VARIANT_TYPE_PACKED_INT64_ARRAY;
    }
    private static final int GDEXTENSION_VARIANT_TYPE_PACKED_FLOAT32_ARRAY = (int)32L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_VARIANT_TYPE_PACKED_FLOAT32_ARRAY = 32
     * }
     */
    public static int GDEXTENSION_VARIANT_TYPE_PACKED_FLOAT32_ARRAY() {
        return GDEXTENSION_VARIANT_TYPE_PACKED_FLOAT32_ARRAY;
    }
    private static final int GDEXTENSION_VARIANT_TYPE_PACKED_FLOAT64_ARRAY = (int)33L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_VARIANT_TYPE_PACKED_FLOAT64_ARRAY = 33
     * }
     */
    public static int GDEXTENSION_VARIANT_TYPE_PACKED_FLOAT64_ARRAY() {
        return GDEXTENSION_VARIANT_TYPE_PACKED_FLOAT64_ARRAY;
    }
    private static final int GDEXTENSION_VARIANT_TYPE_PACKED_STRING_ARRAY = (int)34L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_VARIANT_TYPE_PACKED_STRING_ARRAY = 34
     * }
     */
    public static int GDEXTENSION_VARIANT_TYPE_PACKED_STRING_ARRAY() {
        return GDEXTENSION_VARIANT_TYPE_PACKED_STRING_ARRAY;
    }
    private static final int GDEXTENSION_VARIANT_TYPE_PACKED_VECTOR2_ARRAY = (int)35L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_VARIANT_TYPE_PACKED_VECTOR2_ARRAY = 35
     * }
     */
    public static int GDEXTENSION_VARIANT_TYPE_PACKED_VECTOR2_ARRAY() {
        return GDEXTENSION_VARIANT_TYPE_PACKED_VECTOR2_ARRAY;
    }
    private static final int GDEXTENSION_VARIANT_TYPE_PACKED_VECTOR3_ARRAY = (int)36L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_VARIANT_TYPE_PACKED_VECTOR3_ARRAY = 36
     * }
     */
    public static int GDEXTENSION_VARIANT_TYPE_PACKED_VECTOR3_ARRAY() {
        return GDEXTENSION_VARIANT_TYPE_PACKED_VECTOR3_ARRAY;
    }
    private static final int GDEXTENSION_VARIANT_TYPE_PACKED_COLOR_ARRAY = (int)37L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_VARIANT_TYPE_PACKED_COLOR_ARRAY = 37
     * }
     */
    public static int GDEXTENSION_VARIANT_TYPE_PACKED_COLOR_ARRAY() {
        return GDEXTENSION_VARIANT_TYPE_PACKED_COLOR_ARRAY;
    }
    private static final int GDEXTENSION_VARIANT_TYPE_PACKED_VECTOR4_ARRAY = (int)38L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_VARIANT_TYPE_PACKED_VECTOR4_ARRAY = 38
     * }
     */
    public static int GDEXTENSION_VARIANT_TYPE_PACKED_VECTOR4_ARRAY() {
        return GDEXTENSION_VARIANT_TYPE_PACKED_VECTOR4_ARRAY;
    }
    private static final int GDEXTENSION_VARIANT_TYPE_VARIANT_MAX = (int)39L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_VARIANT_TYPE_VARIANT_MAX = 39
     * }
     */
    public static int GDEXTENSION_VARIANT_TYPE_VARIANT_MAX() {
        return GDEXTENSION_VARIANT_TYPE_VARIANT_MAX;
    }
    private static final int GDEXTENSION_VARIANT_OP_EQUAL = (int)0L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_VARIANT_OP_EQUAL = 0
     * }
     */
    public static int GDEXTENSION_VARIANT_OP_EQUAL() {
        return GDEXTENSION_VARIANT_OP_EQUAL;
    }
    private static final int GDEXTENSION_VARIANT_OP_NOT_EQUAL = (int)1L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_VARIANT_OP_NOT_EQUAL = 1
     * }
     */
    public static int GDEXTENSION_VARIANT_OP_NOT_EQUAL() {
        return GDEXTENSION_VARIANT_OP_NOT_EQUAL;
    }
    private static final int GDEXTENSION_VARIANT_OP_LESS = (int)2L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_VARIANT_OP_LESS = 2
     * }
     */
    public static int GDEXTENSION_VARIANT_OP_LESS() {
        return GDEXTENSION_VARIANT_OP_LESS;
    }
    private static final int GDEXTENSION_VARIANT_OP_LESS_EQUAL = (int)3L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_VARIANT_OP_LESS_EQUAL = 3
     * }
     */
    public static int GDEXTENSION_VARIANT_OP_LESS_EQUAL() {
        return GDEXTENSION_VARIANT_OP_LESS_EQUAL;
    }
    private static final int GDEXTENSION_VARIANT_OP_GREATER = (int)4L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_VARIANT_OP_GREATER = 4
     * }
     */
    public static int GDEXTENSION_VARIANT_OP_GREATER() {
        return GDEXTENSION_VARIANT_OP_GREATER;
    }
    private static final int GDEXTENSION_VARIANT_OP_GREATER_EQUAL = (int)5L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_VARIANT_OP_GREATER_EQUAL = 5
     * }
     */
    public static int GDEXTENSION_VARIANT_OP_GREATER_EQUAL() {
        return GDEXTENSION_VARIANT_OP_GREATER_EQUAL;
    }
    private static final int GDEXTENSION_VARIANT_OP_ADD = (int)6L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_VARIANT_OP_ADD = 6
     * }
     */
    public static int GDEXTENSION_VARIANT_OP_ADD() {
        return GDEXTENSION_VARIANT_OP_ADD;
    }
    private static final int GDEXTENSION_VARIANT_OP_SUBTRACT = (int)7L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_VARIANT_OP_SUBTRACT = 7
     * }
     */
    public static int GDEXTENSION_VARIANT_OP_SUBTRACT() {
        return GDEXTENSION_VARIANT_OP_SUBTRACT;
    }
    private static final int GDEXTENSION_VARIANT_OP_MULTIPLY = (int)8L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_VARIANT_OP_MULTIPLY = 8
     * }
     */
    public static int GDEXTENSION_VARIANT_OP_MULTIPLY() {
        return GDEXTENSION_VARIANT_OP_MULTIPLY;
    }
    private static final int GDEXTENSION_VARIANT_OP_DIVIDE = (int)9L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_VARIANT_OP_DIVIDE = 9
     * }
     */
    public static int GDEXTENSION_VARIANT_OP_DIVIDE() {
        return GDEXTENSION_VARIANT_OP_DIVIDE;
    }
    private static final int GDEXTENSION_VARIANT_OP_NEGATE = (int)10L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_VARIANT_OP_NEGATE = 10
     * }
     */
    public static int GDEXTENSION_VARIANT_OP_NEGATE() {
        return GDEXTENSION_VARIANT_OP_NEGATE;
    }
    private static final int GDEXTENSION_VARIANT_OP_POSITIVE = (int)11L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_VARIANT_OP_POSITIVE = 11
     * }
     */
    public static int GDEXTENSION_VARIANT_OP_POSITIVE() {
        return GDEXTENSION_VARIANT_OP_POSITIVE;
    }
    private static final int GDEXTENSION_VARIANT_OP_MODULE = (int)12L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_VARIANT_OP_MODULE = 12
     * }
     */
    public static int GDEXTENSION_VARIANT_OP_MODULE() {
        return GDEXTENSION_VARIANT_OP_MODULE;
    }
    private static final int GDEXTENSION_VARIANT_OP_POWER = (int)13L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_VARIANT_OP_POWER = 13
     * }
     */
    public static int GDEXTENSION_VARIANT_OP_POWER() {
        return GDEXTENSION_VARIANT_OP_POWER;
    }
    private static final int GDEXTENSION_VARIANT_OP_SHIFT_LEFT = (int)14L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_VARIANT_OP_SHIFT_LEFT = 14
     * }
     */
    public static int GDEXTENSION_VARIANT_OP_SHIFT_LEFT() {
        return GDEXTENSION_VARIANT_OP_SHIFT_LEFT;
    }
    private static final int GDEXTENSION_VARIANT_OP_SHIFT_RIGHT = (int)15L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_VARIANT_OP_SHIFT_RIGHT = 15
     * }
     */
    public static int GDEXTENSION_VARIANT_OP_SHIFT_RIGHT() {
        return GDEXTENSION_VARIANT_OP_SHIFT_RIGHT;
    }
    private static final int GDEXTENSION_VARIANT_OP_BIT_AND = (int)16L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_VARIANT_OP_BIT_AND = 16
     * }
     */
    public static int GDEXTENSION_VARIANT_OP_BIT_AND() {
        return GDEXTENSION_VARIANT_OP_BIT_AND;
    }
    private static final int GDEXTENSION_VARIANT_OP_BIT_OR = (int)17L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_VARIANT_OP_BIT_OR = 17
     * }
     */
    public static int GDEXTENSION_VARIANT_OP_BIT_OR() {
        return GDEXTENSION_VARIANT_OP_BIT_OR;
    }
    private static final int GDEXTENSION_VARIANT_OP_BIT_XOR = (int)18L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_VARIANT_OP_BIT_XOR = 18
     * }
     */
    public static int GDEXTENSION_VARIANT_OP_BIT_XOR() {
        return GDEXTENSION_VARIANT_OP_BIT_XOR;
    }
    private static final int GDEXTENSION_VARIANT_OP_BIT_NEGATE = (int)19L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_VARIANT_OP_BIT_NEGATE = 19
     * }
     */
    public static int GDEXTENSION_VARIANT_OP_BIT_NEGATE() {
        return GDEXTENSION_VARIANT_OP_BIT_NEGATE;
    }
    private static final int GDEXTENSION_VARIANT_OP_AND = (int)20L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_VARIANT_OP_AND = 20
     * }
     */
    public static int GDEXTENSION_VARIANT_OP_AND() {
        return GDEXTENSION_VARIANT_OP_AND;
    }
    private static final int GDEXTENSION_VARIANT_OP_OR = (int)21L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_VARIANT_OP_OR = 21
     * }
     */
    public static int GDEXTENSION_VARIANT_OP_OR() {
        return GDEXTENSION_VARIANT_OP_OR;
    }
    private static final int GDEXTENSION_VARIANT_OP_XOR = (int)22L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_VARIANT_OP_XOR = 22
     * }
     */
    public static int GDEXTENSION_VARIANT_OP_XOR() {
        return GDEXTENSION_VARIANT_OP_XOR;
    }
    private static final int GDEXTENSION_VARIANT_OP_NOT = (int)23L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_VARIANT_OP_NOT = 23
     * }
     */
    public static int GDEXTENSION_VARIANT_OP_NOT() {
        return GDEXTENSION_VARIANT_OP_NOT;
    }
    private static final int GDEXTENSION_VARIANT_OP_IN = (int)24L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_VARIANT_OP_IN = 24
     * }
     */
    public static int GDEXTENSION_VARIANT_OP_IN() {
        return GDEXTENSION_VARIANT_OP_IN;
    }
    private static final int GDEXTENSION_VARIANT_OP_MAX = (int)25L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_VARIANT_OP_MAX = 25
     * }
     */
    public static int GDEXTENSION_VARIANT_OP_MAX() {
        return GDEXTENSION_VARIANT_OP_MAX;
    }
    /**
     * {@snippet lang=c :
     * typedef void *GDExtensionVariantPtr
     * }
     */
    public static final AddressLayout GDExtensionVariantPtr = gdextension_interface_h.C_POINTER;
    /**
     * {@snippet lang=c :
     * typedef const void *GDExtensionConstVariantPtr
     * }
     */
    public static final AddressLayout GDExtensionConstVariantPtr = gdextension_interface_h.C_POINTER;
    /**
     * {@snippet lang=c :
     * typedef void *GDExtensionUninitializedVariantPtr
     * }
     */
    public static final AddressLayout GDExtensionUninitializedVariantPtr = gdextension_interface_h.C_POINTER;
    /**
     * {@snippet lang=c :
     * typedef void *GDExtensionStringNamePtr
     * }
     */
    public static final AddressLayout GDExtensionStringNamePtr = gdextension_interface_h.C_POINTER;
    /**
     * {@snippet lang=c :
     * typedef const void *GDExtensionConstStringNamePtr
     * }
     */
    public static final AddressLayout GDExtensionConstStringNamePtr = gdextension_interface_h.C_POINTER;
    /**
     * {@snippet lang=c :
     * typedef void *GDExtensionUninitializedStringNamePtr
     * }
     */
    public static final AddressLayout GDExtensionUninitializedStringNamePtr = gdextension_interface_h.C_POINTER;
    /**
     * {@snippet lang=c :
     * typedef void *GDExtensionStringPtr
     * }
     */
    public static final AddressLayout GDExtensionStringPtr = gdextension_interface_h.C_POINTER;
    /**
     * {@snippet lang=c :
     * typedef const void *GDExtensionConstStringPtr
     * }
     */
    public static final AddressLayout GDExtensionConstStringPtr = gdextension_interface_h.C_POINTER;
    /**
     * {@snippet lang=c :
     * typedef void *GDExtensionUninitializedStringPtr
     * }
     */
    public static final AddressLayout GDExtensionUninitializedStringPtr = gdextension_interface_h.C_POINTER;
    /**
     * {@snippet lang=c :
     * typedef void *GDExtensionObjectPtr
     * }
     */
    public static final AddressLayout GDExtensionObjectPtr = gdextension_interface_h.C_POINTER;
    /**
     * {@snippet lang=c :
     * typedef const void *GDExtensionConstObjectPtr
     * }
     */
    public static final AddressLayout GDExtensionConstObjectPtr = gdextension_interface_h.C_POINTER;
    /**
     * {@snippet lang=c :
     * typedef void *GDExtensionUninitializedObjectPtr
     * }
     */
    public static final AddressLayout GDExtensionUninitializedObjectPtr = gdextension_interface_h.C_POINTER;
    /**
     * {@snippet lang=c :
     * typedef void *GDExtensionTypePtr
     * }
     */
    public static final AddressLayout GDExtensionTypePtr = gdextension_interface_h.C_POINTER;
    /**
     * {@snippet lang=c :
     * typedef const void *GDExtensionConstTypePtr
     * }
     */
    public static final AddressLayout GDExtensionConstTypePtr = gdextension_interface_h.C_POINTER;
    /**
     * {@snippet lang=c :
     * typedef void *GDExtensionUninitializedTypePtr
     * }
     */
    public static final AddressLayout GDExtensionUninitializedTypePtr = gdextension_interface_h.C_POINTER;
    /**
     * {@snippet lang=c :
     * typedef const void *GDExtensionMethodBindPtr
     * }
     */
    public static final AddressLayout GDExtensionMethodBindPtr = gdextension_interface_h.C_POINTER;
    /**
     * {@snippet lang=c :
     * typedef int64_t GDExtensionInt
     * }
     */
    public static final OfLong GDExtensionInt = gdextension_interface_h.C_LONG;
    /**
     * {@snippet lang=c :
     * typedef uint8_t GDExtensionBool
     * }
     */
    public static final OfByte GDExtensionBool = gdextension_interface_h.C_CHAR;
    /**
     * {@snippet lang=c :
     * typedef uint64_t GDObjectInstanceID
     * }
     */
    public static final OfLong GDObjectInstanceID = gdextension_interface_h.C_LONG;
    /**
     * {@snippet lang=c :
     * typedef void *GDExtensionRefPtr
     * }
     */
    public static final AddressLayout GDExtensionRefPtr = gdextension_interface_h.C_POINTER;
    /**
     * {@snippet lang=c :
     * typedef const void *GDExtensionConstRefPtr
     * }
     */
    public static final AddressLayout GDExtensionConstRefPtr = gdextension_interface_h.C_POINTER;
    private static final int GDEXTENSION_CALL_OK = (int)0L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_CALL_OK = 0
     * }
     */
    public static int GDEXTENSION_CALL_OK() {
        return GDEXTENSION_CALL_OK;
    }
    private static final int GDEXTENSION_CALL_ERROR_INVALID_METHOD = (int)1L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_CALL_ERROR_INVALID_METHOD = 1
     * }
     */
    public static int GDEXTENSION_CALL_ERROR_INVALID_METHOD() {
        return GDEXTENSION_CALL_ERROR_INVALID_METHOD;
    }
    private static final int GDEXTENSION_CALL_ERROR_INVALID_ARGUMENT = (int)2L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_CALL_ERROR_INVALID_ARGUMENT = 2
     * }
     */
    public static int GDEXTENSION_CALL_ERROR_INVALID_ARGUMENT() {
        return GDEXTENSION_CALL_ERROR_INVALID_ARGUMENT;
    }
    private static final int GDEXTENSION_CALL_ERROR_TOO_MANY_ARGUMENTS = (int)3L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_CALL_ERROR_TOO_MANY_ARGUMENTS = 3
     * }
     */
    public static int GDEXTENSION_CALL_ERROR_TOO_MANY_ARGUMENTS() {
        return GDEXTENSION_CALL_ERROR_TOO_MANY_ARGUMENTS;
    }
    private static final int GDEXTENSION_CALL_ERROR_TOO_FEW_ARGUMENTS = (int)4L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_CALL_ERROR_TOO_FEW_ARGUMENTS = 4
     * }
     */
    public static int GDEXTENSION_CALL_ERROR_TOO_FEW_ARGUMENTS() {
        return GDEXTENSION_CALL_ERROR_TOO_FEW_ARGUMENTS;
    }
    private static final int GDEXTENSION_CALL_ERROR_INSTANCE_IS_NULL = (int)5L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_CALL_ERROR_INSTANCE_IS_NULL = 5
     * }
     */
    public static int GDEXTENSION_CALL_ERROR_INSTANCE_IS_NULL() {
        return GDEXTENSION_CALL_ERROR_INSTANCE_IS_NULL;
    }
    private static final int GDEXTENSION_CALL_ERROR_METHOD_NOT_CONST = (int)6L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_CALL_ERROR_METHOD_NOT_CONST = 6
     * }
     */
    public static int GDEXTENSION_CALL_ERROR_METHOD_NOT_CONST() {
        return GDEXTENSION_CALL_ERROR_METHOD_NOT_CONST;
    }
    /**
     * {@snippet lang=c :
     * typedef void *GDExtensionClassInstancePtr
     * }
     */
    public static final AddressLayout GDExtensionClassInstancePtr = gdextension_interface_h.C_POINTER;
    /**
     * {@snippet lang=c :
     * typedef void *GDExtensionClassLibraryPtr
     * }
     */
    public static final AddressLayout GDExtensionClassLibraryPtr = gdextension_interface_h.C_POINTER;
    private static final int GDEXTENSION_METHOD_FLAG_NORMAL = (int)1L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_METHOD_FLAG_NORMAL = 1
     * }
     */
    public static int GDEXTENSION_METHOD_FLAG_NORMAL() {
        return GDEXTENSION_METHOD_FLAG_NORMAL;
    }
    private static final int GDEXTENSION_METHOD_FLAG_EDITOR = (int)2L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_METHOD_FLAG_EDITOR = 2
     * }
     */
    public static int GDEXTENSION_METHOD_FLAG_EDITOR() {
        return GDEXTENSION_METHOD_FLAG_EDITOR;
    }
    private static final int GDEXTENSION_METHOD_FLAG_CONST = (int)4L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_METHOD_FLAG_CONST = 4
     * }
     */
    public static int GDEXTENSION_METHOD_FLAG_CONST() {
        return GDEXTENSION_METHOD_FLAG_CONST;
    }
    private static final int GDEXTENSION_METHOD_FLAG_VIRTUAL = (int)8L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_METHOD_FLAG_VIRTUAL = 8
     * }
     */
    public static int GDEXTENSION_METHOD_FLAG_VIRTUAL() {
        return GDEXTENSION_METHOD_FLAG_VIRTUAL;
    }
    private static final int GDEXTENSION_METHOD_FLAG_VARARG = (int)16L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_METHOD_FLAG_VARARG = 16
     * }
     */
    public static int GDEXTENSION_METHOD_FLAG_VARARG() {
        return GDEXTENSION_METHOD_FLAG_VARARG;
    }
    private static final int GDEXTENSION_METHOD_FLAG_STATIC = (int)32L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_METHOD_FLAG_STATIC = 32
     * }
     */
    public static int GDEXTENSION_METHOD_FLAG_STATIC() {
        return GDEXTENSION_METHOD_FLAG_STATIC;
    }
    private static final int GDEXTENSION_METHOD_FLAGS_DEFAULT = (int)1L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_METHOD_FLAGS_DEFAULT = 1
     * }
     */
    public static int GDEXTENSION_METHOD_FLAGS_DEFAULT() {
        return GDEXTENSION_METHOD_FLAGS_DEFAULT;
    }
    private static final int GDEXTENSION_METHOD_ARGUMENT_METADATA_NONE = (int)0L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_METHOD_ARGUMENT_METADATA_NONE = 0
     * }
     */
    public static int GDEXTENSION_METHOD_ARGUMENT_METADATA_NONE() {
        return GDEXTENSION_METHOD_ARGUMENT_METADATA_NONE;
    }
    private static final int GDEXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_INT8 = (int)1L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_INT8 = 1
     * }
     */
    public static int GDEXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_INT8() {
        return GDEXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_INT8;
    }
    private static final int GDEXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_INT16 = (int)2L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_INT16 = 2
     * }
     */
    public static int GDEXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_INT16() {
        return GDEXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_INT16;
    }
    private static final int GDEXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_INT32 = (int)3L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_INT32 = 3
     * }
     */
    public static int GDEXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_INT32() {
        return GDEXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_INT32;
    }
    private static final int GDEXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_INT64 = (int)4L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_INT64 = 4
     * }
     */
    public static int GDEXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_INT64() {
        return GDEXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_INT64;
    }
    private static final int GDEXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_UINT8 = (int)5L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_UINT8 = 5
     * }
     */
    public static int GDEXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_UINT8() {
        return GDEXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_UINT8;
    }
    private static final int GDEXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_UINT16 = (int)6L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_UINT16 = 6
     * }
     */
    public static int GDEXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_UINT16() {
        return GDEXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_UINT16;
    }
    private static final int GDEXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_UINT32 = (int)7L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_UINT32 = 7
     * }
     */
    public static int GDEXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_UINT32() {
        return GDEXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_UINT32;
    }
    private static final int GDEXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_UINT64 = (int)8L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_UINT64 = 8
     * }
     */
    public static int GDEXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_UINT64() {
        return GDEXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_UINT64;
    }
    private static final int GDEXTENSION_METHOD_ARGUMENT_METADATA_REAL_IS_FLOAT = (int)9L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_METHOD_ARGUMENT_METADATA_REAL_IS_FLOAT = 9
     * }
     */
    public static int GDEXTENSION_METHOD_ARGUMENT_METADATA_REAL_IS_FLOAT() {
        return GDEXTENSION_METHOD_ARGUMENT_METADATA_REAL_IS_FLOAT;
    }
    private static final int GDEXTENSION_METHOD_ARGUMENT_METADATA_REAL_IS_DOUBLE = (int)10L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_METHOD_ARGUMENT_METADATA_REAL_IS_DOUBLE = 10
     * }
     */
    public static int GDEXTENSION_METHOD_ARGUMENT_METADATA_REAL_IS_DOUBLE() {
        return GDEXTENSION_METHOD_ARGUMENT_METADATA_REAL_IS_DOUBLE;
    }
    private static final int GDEXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_CHAR16 = (int)11L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_CHAR16 = 11
     * }
     */
    public static int GDEXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_CHAR16() {
        return GDEXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_CHAR16;
    }
    private static final int GDEXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_CHAR32 = (int)12L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_CHAR32 = 12
     * }
     */
    public static int GDEXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_CHAR32() {
        return GDEXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_CHAR32;
    }
    /**
     * {@snippet lang=c :
     * typedef void *GDExtensionScriptInstanceDataPtr
     * }
     */
    public static final AddressLayout GDExtensionScriptInstanceDataPtr = gdextension_interface_h.C_POINTER;
    /**
     * {@snippet lang=c :
     * typedef void *GDExtensionScriptLanguagePtr
     * }
     */
    public static final AddressLayout GDExtensionScriptLanguagePtr = gdextension_interface_h.C_POINTER;
    /**
     * {@snippet lang=c :
     * typedef void *GDExtensionScriptInstancePtr
     * }
     */
    public static final AddressLayout GDExtensionScriptInstancePtr = gdextension_interface_h.C_POINTER;
    private static final int GDEXTENSION_INITIALIZATION_CORE = (int)0L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_INITIALIZATION_CORE = 0
     * }
     */
    public static int GDEXTENSION_INITIALIZATION_CORE() {
        return GDEXTENSION_INITIALIZATION_CORE;
    }
    private static final int GDEXTENSION_INITIALIZATION_SERVERS = (int)1L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_INITIALIZATION_SERVERS = 1
     * }
     */
    public static int GDEXTENSION_INITIALIZATION_SERVERS() {
        return GDEXTENSION_INITIALIZATION_SERVERS;
    }
    private static final int GDEXTENSION_INITIALIZATION_SCENE = (int)2L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_INITIALIZATION_SCENE = 2
     * }
     */
    public static int GDEXTENSION_INITIALIZATION_SCENE() {
        return GDEXTENSION_INITIALIZATION_SCENE;
    }
    private static final int GDEXTENSION_INITIALIZATION_EDITOR = (int)3L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_INITIALIZATION_EDITOR = 3
     * }
     */
    public static int GDEXTENSION_INITIALIZATION_EDITOR() {
        return GDEXTENSION_INITIALIZATION_EDITOR;
    }
    private static final int GDEXTENSION_MAX_INITIALIZATION_LEVEL = (int)4L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.GDEXTENSION_MAX_INITIALIZATION_LEVEL = 4
     * }
     */
    public static int GDEXTENSION_MAX_INITIALIZATION_LEVEL() {
        return GDEXTENSION_MAX_INITIALIZATION_LEVEL;
    }
    private static final MemorySegment NULL = MemorySegment.ofAddress(0L);
    /**
     * {@snippet lang=c :
     * #define NULL (void*) 0
     * }
     */
    public static MemorySegment NULL() {
        return NULL;
    }
    private static final long _POSIX_C_SOURCE = 200809L;
    /**
     * {@snippet lang=c :
     * #define _POSIX_C_SOURCE 200809
     * }
     */
    public static long _POSIX_C_SOURCE() {
        return _POSIX_C_SOURCE;
    }
    private static final int __TIMESIZE = (int)64L;
    /**
     * {@snippet lang=c :
     * #define __TIMESIZE 64
     * }
     */
    public static int __TIMESIZE() {
        return __TIMESIZE;
    }
    private static final long __STDC_IEC_60559_BFP__ = 201404L;
    /**
     * {@snippet lang=c :
     * #define __STDC_IEC_60559_BFP__ 201404
     * }
     */
    public static long __STDC_IEC_60559_BFP__() {
        return __STDC_IEC_60559_BFP__;
    }
    private static final long __STDC_IEC_60559_COMPLEX__ = 201404L;
    /**
     * {@snippet lang=c :
     * #define __STDC_IEC_60559_COMPLEX__ 201404
     * }
     */
    public static long __STDC_IEC_60559_COMPLEX__() {
        return __STDC_IEC_60559_COMPLEX__;
    }
    private static final long __STDC_ISO_10646__ = 201706L;
    /**
     * {@snippet lang=c :
     * #define __STDC_ISO_10646__ 201706
     * }
     */
    public static long __STDC_ISO_10646__() {
        return __STDC_ISO_10646__;
    }
    private static final int __WCHAR_MAX = (int)2147483647L;
    /**
     * {@snippet lang=c :
     * #define __WCHAR_MAX 2147483647
     * }
     */
    public static int __WCHAR_MAX() {
        return __WCHAR_MAX;
    }
    private static final int __WCHAR_MIN = (int)-2147483648L;
    /**
     * {@snippet lang=c :
     * #define __WCHAR_MIN -2147483648
     * }
     */
    public static int __WCHAR_MIN() {
        return __WCHAR_MIN;
    }
    private static final int INT8_MIN = (int)-128L;
    /**
     * {@snippet lang=c :
     * #define INT8_MIN -128
     * }
     */
    public static int INT8_MIN() {
        return INT8_MIN;
    }
    private static final int INT16_MIN = (int)-32768L;
    /**
     * {@snippet lang=c :
     * #define INT16_MIN -32768
     * }
     */
    public static int INT16_MIN() {
        return INT16_MIN;
    }
    private static final int INT32_MIN = (int)-2147483648L;
    /**
     * {@snippet lang=c :
     * #define INT32_MIN -2147483648
     * }
     */
    public static int INT32_MIN() {
        return INT32_MIN;
    }
    private static final long INT64_MIN = -9223372036854775808L;
    /**
     * {@snippet lang=c :
     * #define INT64_MIN -9223372036854775808
     * }
     */
    public static long INT64_MIN() {
        return INT64_MIN;
    }
    private static final int INT8_MAX = (int)127L;
    /**
     * {@snippet lang=c :
     * #define INT8_MAX 127
     * }
     */
    public static int INT8_MAX() {
        return INT8_MAX;
    }
    private static final int INT16_MAX = (int)32767L;
    /**
     * {@snippet lang=c :
     * #define INT16_MAX 32767
     * }
     */
    public static int INT16_MAX() {
        return INT16_MAX;
    }
    private static final int INT32_MAX = (int)2147483647L;
    /**
     * {@snippet lang=c :
     * #define INT32_MAX 2147483647
     * }
     */
    public static int INT32_MAX() {
        return INT32_MAX;
    }
    private static final long INT64_MAX = 9223372036854775807L;
    /**
     * {@snippet lang=c :
     * #define INT64_MAX 9223372036854775807
     * }
     */
    public static long INT64_MAX() {
        return INT64_MAX;
    }
    private static final int UINT8_MAX = (int)255L;
    /**
     * {@snippet lang=c :
     * #define UINT8_MAX 255
     * }
     */
    public static int UINT8_MAX() {
        return UINT8_MAX;
    }
    private static final int UINT16_MAX = (int)65535L;
    /**
     * {@snippet lang=c :
     * #define UINT16_MAX 65535
     * }
     */
    public static int UINT16_MAX() {
        return UINT16_MAX;
    }
    private static final int UINT32_MAX = (int)4294967295L;
    /**
     * {@snippet lang=c :
     * #define UINT32_MAX 4294967295
     * }
     */
    public static int UINT32_MAX() {
        return UINT32_MAX;
    }
    private static final long UINT64_MAX = -1L;
    /**
     * {@snippet lang=c :
     * #define UINT64_MAX -1
     * }
     */
    public static long UINT64_MAX() {
        return UINT64_MAX;
    }
    private static final int INT_LEAST8_MIN = (int)-128L;
    /**
     * {@snippet lang=c :
     * #define INT_LEAST8_MIN -128
     * }
     */
    public static int INT_LEAST8_MIN() {
        return INT_LEAST8_MIN;
    }
    private static final int INT_LEAST16_MIN = (int)-32768L;
    /**
     * {@snippet lang=c :
     * #define INT_LEAST16_MIN -32768
     * }
     */
    public static int INT_LEAST16_MIN() {
        return INT_LEAST16_MIN;
    }
    private static final int INT_LEAST32_MIN = (int)-2147483648L;
    /**
     * {@snippet lang=c :
     * #define INT_LEAST32_MIN -2147483648
     * }
     */
    public static int INT_LEAST32_MIN() {
        return INT_LEAST32_MIN;
    }
    private static final long INT_LEAST64_MIN = -9223372036854775808L;
    /**
     * {@snippet lang=c :
     * #define INT_LEAST64_MIN -9223372036854775808
     * }
     */
    public static long INT_LEAST64_MIN() {
        return INT_LEAST64_MIN;
    }
    private static final int INT_LEAST8_MAX = (int)127L;
    /**
     * {@snippet lang=c :
     * #define INT_LEAST8_MAX 127
     * }
     */
    public static int INT_LEAST8_MAX() {
        return INT_LEAST8_MAX;
    }
    private static final int INT_LEAST16_MAX = (int)32767L;
    /**
     * {@snippet lang=c :
     * #define INT_LEAST16_MAX 32767
     * }
     */
    public static int INT_LEAST16_MAX() {
        return INT_LEAST16_MAX;
    }
    private static final int INT_LEAST32_MAX = (int)2147483647L;
    /**
     * {@snippet lang=c :
     * #define INT_LEAST32_MAX 2147483647
     * }
     */
    public static int INT_LEAST32_MAX() {
        return INT_LEAST32_MAX;
    }
    private static final long INT_LEAST64_MAX = 9223372036854775807L;
    /**
     * {@snippet lang=c :
     * #define INT_LEAST64_MAX 9223372036854775807
     * }
     */
    public static long INT_LEAST64_MAX() {
        return INT_LEAST64_MAX;
    }
    private static final int UINT_LEAST8_MAX = (int)255L;
    /**
     * {@snippet lang=c :
     * #define UINT_LEAST8_MAX 255
     * }
     */
    public static int UINT_LEAST8_MAX() {
        return UINT_LEAST8_MAX;
    }
    private static final int UINT_LEAST16_MAX = (int)65535L;
    /**
     * {@snippet lang=c :
     * #define UINT_LEAST16_MAX 65535
     * }
     */
    public static int UINT_LEAST16_MAX() {
        return UINT_LEAST16_MAX;
    }
    private static final int UINT_LEAST32_MAX = (int)4294967295L;
    /**
     * {@snippet lang=c :
     * #define UINT_LEAST32_MAX 4294967295
     * }
     */
    public static int UINT_LEAST32_MAX() {
        return UINT_LEAST32_MAX;
    }
    private static final long UINT_LEAST64_MAX = -1L;
    /**
     * {@snippet lang=c :
     * #define UINT_LEAST64_MAX -1
     * }
     */
    public static long UINT_LEAST64_MAX() {
        return UINT_LEAST64_MAX;
    }
    private static final int INT_FAST8_MIN = (int)-128L;
    /**
     * {@snippet lang=c :
     * #define INT_FAST8_MIN -128
     * }
     */
    public static int INT_FAST8_MIN() {
        return INT_FAST8_MIN;
    }
    private static final long INT_FAST16_MIN = -9223372036854775808L;
    /**
     * {@snippet lang=c :
     * #define INT_FAST16_MIN -9223372036854775808
     * }
     */
    public static long INT_FAST16_MIN() {
        return INT_FAST16_MIN;
    }
    private static final long INT_FAST32_MIN = -9223372036854775808L;
    /**
     * {@snippet lang=c :
     * #define INT_FAST32_MIN -9223372036854775808
     * }
     */
    public static long INT_FAST32_MIN() {
        return INT_FAST32_MIN;
    }
    private static final long INT_FAST64_MIN = -9223372036854775808L;
    /**
     * {@snippet lang=c :
     * #define INT_FAST64_MIN -9223372036854775808
     * }
     */
    public static long INT_FAST64_MIN() {
        return INT_FAST64_MIN;
    }
    private static final int INT_FAST8_MAX = (int)127L;
    /**
     * {@snippet lang=c :
     * #define INT_FAST8_MAX 127
     * }
     */
    public static int INT_FAST8_MAX() {
        return INT_FAST8_MAX;
    }
    private static final long INT_FAST16_MAX = 9223372036854775807L;
    /**
     * {@snippet lang=c :
     * #define INT_FAST16_MAX 9223372036854775807
     * }
     */
    public static long INT_FAST16_MAX() {
        return INT_FAST16_MAX;
    }
    private static final long INT_FAST32_MAX = 9223372036854775807L;
    /**
     * {@snippet lang=c :
     * #define INT_FAST32_MAX 9223372036854775807
     * }
     */
    public static long INT_FAST32_MAX() {
        return INT_FAST32_MAX;
    }
    private static final long INT_FAST64_MAX = 9223372036854775807L;
    /**
     * {@snippet lang=c :
     * #define INT_FAST64_MAX 9223372036854775807
     * }
     */
    public static long INT_FAST64_MAX() {
        return INT_FAST64_MAX;
    }
    private static final int UINT_FAST8_MAX = (int)255L;
    /**
     * {@snippet lang=c :
     * #define UINT_FAST8_MAX 255
     * }
     */
    public static int UINT_FAST8_MAX() {
        return UINT_FAST8_MAX;
    }
    private static final long UINT_FAST16_MAX = -1L;
    /**
     * {@snippet lang=c :
     * #define UINT_FAST16_MAX -1
     * }
     */
    public static long UINT_FAST16_MAX() {
        return UINT_FAST16_MAX;
    }
    private static final long UINT_FAST32_MAX = -1L;
    /**
     * {@snippet lang=c :
     * #define UINT_FAST32_MAX -1
     * }
     */
    public static long UINT_FAST32_MAX() {
        return UINT_FAST32_MAX;
    }
    private static final long UINT_FAST64_MAX = -1L;
    /**
     * {@snippet lang=c :
     * #define UINT_FAST64_MAX -1
     * }
     */
    public static long UINT_FAST64_MAX() {
        return UINT_FAST64_MAX;
    }
    private static final long INTPTR_MIN = -9223372036854775808L;
    /**
     * {@snippet lang=c :
     * #define INTPTR_MIN -9223372036854775808
     * }
     */
    public static long INTPTR_MIN() {
        return INTPTR_MIN;
    }
    private static final long INTPTR_MAX = 9223372036854775807L;
    /**
     * {@snippet lang=c :
     * #define INTPTR_MAX 9223372036854775807
     * }
     */
    public static long INTPTR_MAX() {
        return INTPTR_MAX;
    }
    private static final long UINTPTR_MAX = -1L;
    /**
     * {@snippet lang=c :
     * #define UINTPTR_MAX -1
     * }
     */
    public static long UINTPTR_MAX() {
        return UINTPTR_MAX;
    }
    private static final long INTMAX_MIN = -9223372036854775808L;
    /**
     * {@snippet lang=c :
     * #define INTMAX_MIN -9223372036854775808
     * }
     */
    public static long INTMAX_MIN() {
        return INTMAX_MIN;
    }
    private static final long INTMAX_MAX = 9223372036854775807L;
    /**
     * {@snippet lang=c :
     * #define INTMAX_MAX 9223372036854775807
     * }
     */
    public static long INTMAX_MAX() {
        return INTMAX_MAX;
    }
    private static final long UINTMAX_MAX = -1L;
    /**
     * {@snippet lang=c :
     * #define UINTMAX_MAX -1
     * }
     */
    public static long UINTMAX_MAX() {
        return UINTMAX_MAX;
    }
    private static final long PTRDIFF_MIN = -9223372036854775808L;
    /**
     * {@snippet lang=c :
     * #define PTRDIFF_MIN -9223372036854775808
     * }
     */
    public static long PTRDIFF_MIN() {
        return PTRDIFF_MIN;
    }
    private static final long PTRDIFF_MAX = 9223372036854775807L;
    /**
     * {@snippet lang=c :
     * #define PTRDIFF_MAX 9223372036854775807
     * }
     */
    public static long PTRDIFF_MAX() {
        return PTRDIFF_MAX;
    }
    private static final int SIG_ATOMIC_MIN = (int)-2147483648L;
    /**
     * {@snippet lang=c :
     * #define SIG_ATOMIC_MIN -2147483648
     * }
     */
    public static int SIG_ATOMIC_MIN() {
        return SIG_ATOMIC_MIN;
    }
    private static final int SIG_ATOMIC_MAX = (int)2147483647L;
    /**
     * {@snippet lang=c :
     * #define SIG_ATOMIC_MAX 2147483647
     * }
     */
    public static int SIG_ATOMIC_MAX() {
        return SIG_ATOMIC_MAX;
    }
    private static final long SIZE_MAX = -1L;
    /**
     * {@snippet lang=c :
     * #define SIZE_MAX -1
     * }
     */
    public static long SIZE_MAX() {
        return SIZE_MAX;
    }
    private static final int WCHAR_MIN = (int)-2147483648L;
    /**
     * {@snippet lang=c :
     * #define WCHAR_MIN -2147483648
     * }
     */
    public static int WCHAR_MIN() {
        return WCHAR_MIN;
    }
    private static final int WCHAR_MAX = (int)2147483647L;
    /**
     * {@snippet lang=c :
     * #define WCHAR_MAX 2147483647
     * }
     */
    public static int WCHAR_MAX() {
        return WCHAR_MAX;
    }
    private static final int WINT_MIN = (int)0L;
    /**
     * {@snippet lang=c :
     * #define WINT_MIN 0
     * }
     */
    public static int WINT_MIN() {
        return WINT_MIN;
    }
    private static final int WINT_MAX = (int)4294967295L;
    /**
     * {@snippet lang=c :
     * #define WINT_MAX 4294967295
     * }
     */
    public static int WINT_MAX() {
        return WINT_MAX;
    }
}

