package io.github.kingg22.godot.codegen.impl.extensionapi.stubs

import io.github.kingg22.godot.codegen.impl.extensionapi.Backend
import io.github.kingg22.godot.codegen.impl.extensionapi.CodeImplGenerator
import io.github.kingg22.godot.codegen.impl.extensionapi.TypeResolver

/**
 * Backend for **Kotlin** stubs.
 *
 * - Stubs: generated by [KotlinStubGenerator] with [KotlinStubTypeResolver]
 *
 * @param packageName Base package for generated code (e.g. `"godot"`).
 */
class KotlinStubBackend(
    packageName: String,
    override val typeResolver: TypeResolver = KotlinStubTypeResolver(packageName),
    override val codeImplGenerator: CodeImplGenerator = KotlinStubGenerator(typeResolver, packageName),
) : Backend {
    override val name: String get() = "kotlin-stub"
    init {
        println("WARNING: Using Kotlin stub backend.")
    }
}
