// Generated by jextract

package io.github.kingg22.godot.internal.ffm;

import java.lang.foreign.AddressLayout;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.GroupLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.MemoryLayout;
import java.lang.foreign.PaddingLayout;
import java.lang.foreign.SequenceLayout;
import java.lang.foreign.StructLayout;
import java.lang.foreign.ValueLayout;
import java.lang.invoke.MethodHandle;
import java.lang.invoke.MethodHandles;
import java.util.Arrays;
import java.util.stream.Collectors;

import static java.util.Objects.requireNonNull;

final class FFMUtils {
    private FFMUtils() {
        throw new UnsupportedOperationException();
    }

    static final ValueLayout.OfBoolean C_BOOL;
    static final ValueLayout.OfByte C_CHAR;
    static final ValueLayout.OfShort C_SHORT;
    static final ValueLayout.OfInt C_INT;
    static final ValueLayout.OfLong C_LONG_LONG;
    static final ValueLayout.OfFloat C_FLOAT;
    static final ValueLayout.OfDouble C_DOUBLE;
    static final AddressLayout C_POINTER;
    static final ValueLayout.OfLong C_LONG;

    static final boolean TRACE_DOWNCALLS = Boolean.getBoolean("jextract.trace.downcalls");

    static {
        final var layouts = Linker.nativeLinker().canonicalLayouts();

        C_BOOL = (ValueLayout.OfBoolean)
                requireNonNull(layouts.get("bool"), "Missing canonical layout for C type: bool");

        C_CHAR = (ValueLayout.OfByte) requireNonNull(layouts.get("char"), "Missing canonical layout for C type: char");

        C_SHORT = (ValueLayout.OfShort)
                requireNonNull(layouts.get("short"), "Missing canonical layout for C type: short");

        C_INT = (ValueLayout.OfInt) requireNonNull(layouts.get("int"), "Missing canonical layout for C type: int");

        C_LONG_LONG = (ValueLayout.OfLong)
                requireNonNull(layouts.get("long long"), "Missing canonical layout for C type: long long");

        C_FLOAT = (ValueLayout.OfFloat)
                requireNonNull(layouts.get("float"), "Missing canonical layout for C type: float");

        C_DOUBLE = (ValueLayout.OfDouble)
                requireNonNull(layouts.get("double"), "Missing canonical layout for C type: double");

        final var basePointer =
                (AddressLayout) requireNonNull(layouts.get("void*"), "Missing canonical layout for C type: void*");

        C_POINTER = basePointer.withTargetLayout(MemoryLayout.sequenceLayout(Long.MAX_VALUE, C_CHAR));

        C_LONG = (ValueLayout.OfLong) requireNonNull(layouts.get("long"), "Missing canonical layout for C type: long");
    }

    static void traceDowncall(final String name, final Object... args) {
        final var traceArgs = Arrays.stream(args).map(Object::toString).collect(Collectors.joining(", "));
        System.out.printf("%s(%s)\n", name, traceArgs);
    }

    static MethodHandle upcallHandle(
            final Class<?> clazz, final String name, final FunctionDescriptor functionDescriptor) {
        try {
            return MethodHandles.lookup().findVirtual(clazz, name, functionDescriptor.toMethodType());
        } catch (ReflectiveOperationException ex) {
            throw new LinkageError(ex.getMessage(), ex);
        }
    }

    static MemoryLayout align(final MemoryLayout layout, final long align) {
        return switch (layout) {
            case PaddingLayout p -> p;
            case ValueLayout v -> v.withByteAlignment(align);
            case GroupLayout g -> {
                final var alignedMembers =
                        g.memberLayouts().stream().map(m -> align(m, align)).toArray(MemoryLayout[]::new);
                yield g instanceof StructLayout
                        ? MemoryLayout.structLayout(alignedMembers)
                        : MemoryLayout.unionLayout(alignedMembers);
            }
            case SequenceLayout s -> MemoryLayout.sequenceLayout(s.elementCount(), align(s.elementLayout(), align));
        };
    }
}
