// Generated by jextract

package io.github.kingg22.godot.internal.ffm;

import java.lang.foreign.Arena;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.Linker;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

import static io.github.kingg22.godot.internal.ffm.FFMUtils.C_POINTER;
import static io.github.kingg22.godot.internal.ffm.FFMUtils.upcallHandle;

/// ```C
/// typedef void (*GDExtensionInterfaceClassdbRegisterExtensionClass5)(GDExtensionClassLibraryPtr,
/// GDExtensionConstStringNamePtr, GDExtensionConstStringNamePtr, const GDExtensionClassCreationInfo5 *)
/// ```
public final class GDExtensionInterfaceClassdbRegisterExtensionClass5 {

    private GDExtensionInterfaceClassdbRegisterExtensionClass5() {
        // Should not be called directly
    }

    /** The function pointer signature, expressed as a functional interface */
    public interface Function {
        void apply(
                MemorySegment p_library,
                MemorySegment p_class_name,
                MemorySegment p_parent_class_name,
                MemorySegment p_extension_funcs);
    }

    private static final FunctionDescriptor $DESC =
            FunctionDescriptor.ofVoid(C_POINTER, C_POINTER, C_POINTER, C_POINTER);

    /** The descriptor of this function pointer */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH =
            upcallHandle(GDExtensionInterfaceClassdbRegisterExtensionClass5.Function.class, $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}. The lifetime of the returned segment
     * is managed by {@code arena}
     */
    public static MemorySegment allocate(GDExtensionInterfaceClassdbRegisterExtensionClass5.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    public static void invoke(
            MemorySegment funcPtr,
            MemorySegment p_library,
            String p_class_name,
            String p_parent_class_name,
            MemorySegment p_extension_funcs) {
        var arena = Arena.ofAuto();
        invoke(
                funcPtr,
                p_library,
                arena.allocateFrom(p_class_name),
                arena.allocateFrom(p_parent_class_name),
                p_extension_funcs);
    }

    /** Invoke the upcall stub {@code funcPtr}, with given parameters */
    public static void invoke(
            MemorySegment funcPtr,
            MemorySegment p_library,
            MemorySegment p_class_name,
            MemorySegment p_parent_class_name,
            MemorySegment p_extension_funcs) {
        try {
            DOWN$MH.invokeExact(funcPtr, p_library, p_class_name, p_parent_class_name, p_extension_funcs);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}
