// Generated by jextract

package io.github.kingg22.godot.internal.ffm;

import java.lang.foreign.*;
import java.lang.invoke.*;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.MemoryLayout.PathElement.*;
import static java.lang.foreign.ValueLayout.*;

/**
 * {@snippet lang=c :
 * typedef GDExtensionBool (*GDExtensionInterfaceVariantIterInit)(GDExtensionConstVariantPtr, GDExtensionUninitializedVariantPtr, GDExtensionBool *)
 * }
 */
public final class GDExtensionInterfaceVariantIterInit {

    private GDExtensionInterfaceVariantIterInit() {
        throw new UnsupportedOperationException();
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        byte apply(MemorySegment p_self, MemorySegment r_iter, MemorySegment r_valid);
    }

    private static final FunctionDescriptor $DESC =
            FunctionDescriptor.of(FFMUtils.C_CHAR, FFMUtils.C_POINTER, FFMUtils.C_POINTER, FFMUtils.C_POINTER);

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH =
            FFMUtils.upcallHandle(GDExtensionInterfaceVariantIterInit.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(GDExtensionInterfaceVariantIterInit.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static byte invoke(
            MemorySegment funcPtr, MemorySegment p_self, MemorySegment r_iter, MemorySegment r_valid) {
        try {
            return (byte) DOWN$MH.invokeExact(funcPtr, p_self, r_iter, r_valid);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}
