// Generated by jextract

package io.github.kingg22.godot.internal.ffm;

import java.lang.foreign.Arena;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.Linker;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

/**
 * {@snippet lang = c: typedef void (*GDExtensionScriptInstanceFreePropertyList2)(GDExtensionScriptInstanceDataPtr,
 * const GDExtensionPropertyInfo *, uint32_t) }
 */
public final class GDExtensionScriptInstanceFreePropertyList2 {

    private GDExtensionScriptInstanceFreePropertyList2() {
        // Should not be called directly
    }

    /** The function pointer signature, expressed as a functional interface */
    public interface Function {
        void apply(MemorySegment p_instance, MemorySegment p_list, int p_count);
    }

    private static final FunctionDescriptor $DESC =
            FunctionDescriptor.ofVoid(FFMUtils.C_POINTER, FFMUtils.C_POINTER, FFMUtils.C_INT);

    /** The descriptor of this function pointer */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH =
            FFMUtils.upcallHandle(GDExtensionScriptInstanceFreePropertyList2.Function.class, $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}. The lifetime of the returned segment
     * is managed by {@code arena}
     */
    public static MemorySegment allocate(GDExtensionScriptInstanceFreePropertyList2.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /** Invoke the upcall stub {@code funcPtr}, with given parameters */
    public static void invoke(MemorySegment funcPtr, MemorySegment p_instance, MemorySegment p_list, int p_count) {
        try {
            DOWN$MH.invokeExact(funcPtr, p_instance, p_list, p_count);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}
