// Generated by jextract

package io.github.kingg22.godot.internal.ffm;

import java.lang.foreign.AddressLayout;
import java.lang.foreign.Arena;
import java.lang.foreign.GroupLayout;
import java.lang.foreign.MemoryLayout;
import java.lang.foreign.MemorySegment;
import java.lang.foreign.SegmentAllocator;
import java.util.function.Consumer;

import static java.lang.foreign.MemoryLayout.PathElement.groupElement;
import static java.lang.foreign.ValueLayout.OfByte;

/**
 * {@snippet lang=c :
 * struct {
 *     GDExtensionBool is_virtual;
 *     GDExtensionBool is_abstract;
 *     GDExtensionClassSet set_func;
 *     GDExtensionClassGet get_func;
 *     GDExtensionClassGetPropertyList get_property_list_func;
 *     GDExtensionClassFreePropertyList free_property_list_func;
 *     GDExtensionClassPropertyCanRevert property_can_revert_func;
 *     GDExtensionClassPropertyGetRevert property_get_revert_func;
 *     GDExtensionClassNotification notification_func;
 *     GDExtensionClassToString to_string_func;
 *     GDExtensionClassReference reference_func;
 *     GDExtensionClassUnreference unreference_func;
 *     GDExtensionClassCreateInstance create_instance_func;
 *     GDExtensionClassFreeInstance free_instance_func;
 *     GDExtensionClassGetVirtual get_virtual_func;
 *     GDExtensionClassGetRID get_rid_func;
 *     void *class_userdata;
 * }
 * }
 */
@Deprecated(since = "4.2")
public final class GDExtensionClassCreationInfo {

    GDExtensionClassCreationInfo() {
        throw new UnsupportedOperationException();
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
                    FFMUtils.C_CHAR.withName("is_virtual"),
                    FFMUtils.C_CHAR.withName("is_abstract"),
                    MemoryLayout.paddingLayout(6),
                    FFMUtils.C_POINTER.withName("set_func"),
                    FFMUtils.C_POINTER.withName("get_func"),
                    FFMUtils.C_POINTER.withName("get_property_list_func"),
                    FFMUtils.C_POINTER.withName("free_property_list_func"),
                    FFMUtils.C_POINTER.withName("property_can_revert_func"),
                    FFMUtils.C_POINTER.withName("property_get_revert_func"),
                    FFMUtils.C_POINTER.withName("notification_func"),
                    FFMUtils.C_POINTER.withName("to_string_func"),
                    FFMUtils.C_POINTER.withName("reference_func"),
                    FFMUtils.C_POINTER.withName("unreference_func"),
                    FFMUtils.C_POINTER.withName("create_instance_func"),
                    FFMUtils.C_POINTER.withName("free_instance_func"),
                    FFMUtils.C_POINTER.withName("get_virtual_func"),
                    FFMUtils.C_POINTER.withName("get_rid_func"),
                    FFMUtils.C_POINTER.withName("class_userdata"))
            .withName("GDExtensionClassCreationInfo");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfByte is_virtual$LAYOUT = (OfByte) $LAYOUT.select(groupElement("is_virtual"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * GDExtensionBool is_virtual
     * }
     */
    public static final OfByte is_virtual$layout() {
        return is_virtual$LAYOUT;
    }

    private static final long is_virtual$OFFSET = $LAYOUT.byteOffset(groupElement("is_virtual"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * GDExtensionBool is_virtual
     * }
     */
    public static final long is_virtual$offset() {
        return is_virtual$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * GDExtensionBool is_virtual
     * }
     */
    public static byte is_virtual(MemorySegment struct) {
        return struct.get(is_virtual$LAYOUT, is_virtual$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * GDExtensionBool is_virtual
     * }
     */
    public static void is_virtual(MemorySegment struct, byte fieldValue) {
        struct.set(is_virtual$LAYOUT, is_virtual$OFFSET, fieldValue);
    }

    private static final OfByte is_abstract$LAYOUT = (OfByte) $LAYOUT.select(groupElement("is_abstract"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * GDExtensionBool is_abstract
     * }
     */
    public static final OfByte is_abstract$layout() {
        return is_abstract$LAYOUT;
    }

    private static final long is_abstract$OFFSET = $LAYOUT.byteOffset(groupElement("is_abstract"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * GDExtensionBool is_abstract
     * }
     */
    public static final long is_abstract$offset() {
        return is_abstract$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * GDExtensionBool is_abstract
     * }
     */
    public static byte is_abstract(MemorySegment struct) {
        return struct.get(is_abstract$LAYOUT, is_abstract$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * GDExtensionBool is_abstract
     * }
     */
    public static void is_abstract(MemorySegment struct, byte fieldValue) {
        struct.set(is_abstract$LAYOUT, is_abstract$OFFSET, fieldValue);
    }

    private static final AddressLayout set_func$LAYOUT = (AddressLayout) $LAYOUT.select(groupElement("set_func"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * GDExtensionClassSet set_func
     * }
     */
    public static final AddressLayout set_func$layout() {
        return set_func$LAYOUT;
    }

    private static final long set_func$OFFSET = $LAYOUT.byteOffset(groupElement("set_func"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * GDExtensionClassSet set_func
     * }
     */
    public static final long set_func$offset() {
        return set_func$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * GDExtensionClassSet set_func
     * }
     */
    public static MemorySegment set_func(MemorySegment struct) {
        return struct.get(set_func$LAYOUT, set_func$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * GDExtensionClassSet set_func
     * }
     */
    public static void set_func(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(set_func$LAYOUT, set_func$OFFSET, fieldValue);
    }

    private static final AddressLayout get_func$LAYOUT = (AddressLayout) $LAYOUT.select(groupElement("get_func"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * GDExtensionClassGet get_func
     * }
     */
    public static final AddressLayout get_func$layout() {
        return get_func$LAYOUT;
    }

    private static final long get_func$OFFSET = $LAYOUT.byteOffset(groupElement("get_func"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * GDExtensionClassGet get_func
     * }
     */
    public static final long get_func$offset() {
        return get_func$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * GDExtensionClassGet get_func
     * }
     */
    public static MemorySegment get_func(MemorySegment struct) {
        return struct.get(get_func$LAYOUT, get_func$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * GDExtensionClassGet get_func
     * }
     */
    public static void get_func(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(get_func$LAYOUT, get_func$OFFSET, fieldValue);
    }

    private static final AddressLayout get_property_list_func$LAYOUT =
            (AddressLayout) $LAYOUT.select(groupElement("get_property_list_func"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * GDExtensionClassGetPropertyList get_property_list_func
     * }
     */
    public static final AddressLayout get_property_list_func$layout() {
        return get_property_list_func$LAYOUT;
    }

    private static final long get_property_list_func$OFFSET =
            $LAYOUT.byteOffset(groupElement("get_property_list_func"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * GDExtensionClassGetPropertyList get_property_list_func
     * }
     */
    public static final long get_property_list_func$offset() {
        return get_property_list_func$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * GDExtensionClassGetPropertyList get_property_list_func
     * }
     */
    public static MemorySegment get_property_list_func(MemorySegment struct) {
        return struct.get(get_property_list_func$LAYOUT, get_property_list_func$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * GDExtensionClassGetPropertyList get_property_list_func
     * }
     */
    public static void get_property_list_func(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(get_property_list_func$LAYOUT, get_property_list_func$OFFSET, fieldValue);
    }

    private static final AddressLayout free_property_list_func$LAYOUT =
            (AddressLayout) $LAYOUT.select(groupElement("free_property_list_func"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * GDExtensionClassFreePropertyList free_property_list_func
     * }
     */
    public static final AddressLayout free_property_list_func$layout() {
        return free_property_list_func$LAYOUT;
    }

    private static final long free_property_list_func$OFFSET =
            $LAYOUT.byteOffset(groupElement("free_property_list_func"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * GDExtensionClassFreePropertyList free_property_list_func
     * }
     */
    public static final long free_property_list_func$offset() {
        return free_property_list_func$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * GDExtensionClassFreePropertyList free_property_list_func
     * }
     */
    public static MemorySegment free_property_list_func(MemorySegment struct) {
        return struct.get(free_property_list_func$LAYOUT, free_property_list_func$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * GDExtensionClassFreePropertyList free_property_list_func
     * }
     */
    public static void free_property_list_func(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(free_property_list_func$LAYOUT, free_property_list_func$OFFSET, fieldValue);
    }

    private static final AddressLayout property_can_revert_func$LAYOUT =
            (AddressLayout) $LAYOUT.select(groupElement("property_can_revert_func"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * GDExtensionClassPropertyCanRevert property_can_revert_func
     * }
     */
    public static final AddressLayout property_can_revert_func$layout() {
        return property_can_revert_func$LAYOUT;
    }

    private static final long property_can_revert_func$OFFSET =
            $LAYOUT.byteOffset(groupElement("property_can_revert_func"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * GDExtensionClassPropertyCanRevert property_can_revert_func
     * }
     */
    public static final long property_can_revert_func$offset() {
        return property_can_revert_func$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * GDExtensionClassPropertyCanRevert property_can_revert_func
     * }
     */
    public static MemorySegment property_can_revert_func(MemorySegment struct) {
        return struct.get(property_can_revert_func$LAYOUT, property_can_revert_func$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * GDExtensionClassPropertyCanRevert property_can_revert_func
     * }
     */
    public static void property_can_revert_func(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(property_can_revert_func$LAYOUT, property_can_revert_func$OFFSET, fieldValue);
    }

    private static final AddressLayout property_get_revert_func$LAYOUT =
            (AddressLayout) $LAYOUT.select(groupElement("property_get_revert_func"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * GDExtensionClassPropertyGetRevert property_get_revert_func
     * }
     */
    public static final AddressLayout property_get_revert_func$layout() {
        return property_get_revert_func$LAYOUT;
    }

    private static final long property_get_revert_func$OFFSET =
            $LAYOUT.byteOffset(groupElement("property_get_revert_func"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * GDExtensionClassPropertyGetRevert property_get_revert_func
     * }
     */
    public static final long property_get_revert_func$offset() {
        return property_get_revert_func$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * GDExtensionClassPropertyGetRevert property_get_revert_func
     * }
     */
    public static MemorySegment property_get_revert_func(MemorySegment struct) {
        return struct.get(property_get_revert_func$LAYOUT, property_get_revert_func$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * GDExtensionClassPropertyGetRevert property_get_revert_func
     * }
     */
    public static void property_get_revert_func(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(property_get_revert_func$LAYOUT, property_get_revert_func$OFFSET, fieldValue);
    }

    private static final AddressLayout notification_func$LAYOUT =
            (AddressLayout) $LAYOUT.select(groupElement("notification_func"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * GDExtensionClassNotification notification_func
     * }
     */
    public static final AddressLayout notification_func$layout() {
        return notification_func$LAYOUT;
    }

    private static final long notification_func$OFFSET = $LAYOUT.byteOffset(groupElement("notification_func"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * GDExtensionClassNotification notification_func
     * }
     */
    public static final long notification_func$offset() {
        return notification_func$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * GDExtensionClassNotification notification_func
     * }
     */
    public static MemorySegment notification_func(MemorySegment struct) {
        return struct.get(notification_func$LAYOUT, notification_func$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * GDExtensionClassNotification notification_func
     * }
     */
    public static void notification_func(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(notification_func$LAYOUT, notification_func$OFFSET, fieldValue);
    }

    private static final AddressLayout to_string_func$LAYOUT =
            (AddressLayout) $LAYOUT.select(groupElement("to_string_func"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * GDExtensionClassToString to_string_func
     * }
     */
    public static final AddressLayout to_string_func$layout() {
        return to_string_func$LAYOUT;
    }

    private static final long to_string_func$OFFSET = $LAYOUT.byteOffset(groupElement("to_string_func"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * GDExtensionClassToString to_string_func
     * }
     */
    public static final long to_string_func$offset() {
        return to_string_func$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * GDExtensionClassToString to_string_func
     * }
     */
    public static MemorySegment to_string_func(MemorySegment struct) {
        return struct.get(to_string_func$LAYOUT, to_string_func$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * GDExtensionClassToString to_string_func
     * }
     */
    public static void to_string_func(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(to_string_func$LAYOUT, to_string_func$OFFSET, fieldValue);
    }

    private static final AddressLayout reference_func$LAYOUT =
            (AddressLayout) $LAYOUT.select(groupElement("reference_func"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * GDExtensionClassReference reference_func
     * }
     */
    public static final AddressLayout reference_func$layout() {
        return reference_func$LAYOUT;
    }

    private static final long reference_func$OFFSET = $LAYOUT.byteOffset(groupElement("reference_func"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * GDExtensionClassReference reference_func
     * }
     */
    public static final long reference_func$offset() {
        return reference_func$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * GDExtensionClassReference reference_func
     * }
     */
    public static MemorySegment reference_func(MemorySegment struct) {
        return struct.get(reference_func$LAYOUT, reference_func$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * GDExtensionClassReference reference_func
     * }
     */
    public static void reference_func(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(reference_func$LAYOUT, reference_func$OFFSET, fieldValue);
    }

    private static final AddressLayout unreference_func$LAYOUT =
            (AddressLayout) $LAYOUT.select(groupElement("unreference_func"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * GDExtensionClassUnreference unreference_func
     * }
     */
    public static final AddressLayout unreference_func$layout() {
        return unreference_func$LAYOUT;
    }

    private static final long unreference_func$OFFSET = $LAYOUT.byteOffset(groupElement("unreference_func"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * GDExtensionClassUnreference unreference_func
     * }
     */
    public static final long unreference_func$offset() {
        return unreference_func$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * GDExtensionClassUnreference unreference_func
     * }
     */
    public static MemorySegment unreference_func(MemorySegment struct) {
        return struct.get(unreference_func$LAYOUT, unreference_func$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * GDExtensionClassUnreference unreference_func
     * }
     */
    public static void unreference_func(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(unreference_func$LAYOUT, unreference_func$OFFSET, fieldValue);
    }

    private static final AddressLayout create_instance_func$LAYOUT =
            (AddressLayout) $LAYOUT.select(groupElement("create_instance_func"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * GDExtensionClassCreateInstance create_instance_func
     * }
     */
    public static final AddressLayout create_instance_func$layout() {
        return create_instance_func$LAYOUT;
    }

    private static final long create_instance_func$OFFSET = $LAYOUT.byteOffset(groupElement("create_instance_func"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * GDExtensionClassCreateInstance create_instance_func
     * }
     */
    public static final long create_instance_func$offset() {
        return create_instance_func$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * GDExtensionClassCreateInstance create_instance_func
     * }
     */
    public static MemorySegment create_instance_func(MemorySegment struct) {
        return struct.get(create_instance_func$LAYOUT, create_instance_func$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * GDExtensionClassCreateInstance create_instance_func
     * }
     */
    public static void create_instance_func(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(create_instance_func$LAYOUT, create_instance_func$OFFSET, fieldValue);
    }

    private static final AddressLayout free_instance_func$LAYOUT =
            (AddressLayout) $LAYOUT.select(groupElement("free_instance_func"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * GDExtensionClassFreeInstance free_instance_func
     * }
     */
    public static final AddressLayout free_instance_func$layout() {
        return free_instance_func$LAYOUT;
    }

    private static final long free_instance_func$OFFSET = $LAYOUT.byteOffset(groupElement("free_instance_func"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * GDExtensionClassFreeInstance free_instance_func
     * }
     */
    public static final long free_instance_func$offset() {
        return free_instance_func$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * GDExtensionClassFreeInstance free_instance_func
     * }
     */
    public static MemorySegment free_instance_func(MemorySegment struct) {
        return struct.get(free_instance_func$LAYOUT, free_instance_func$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * GDExtensionClassFreeInstance free_instance_func
     * }
     */
    public static void free_instance_func(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(free_instance_func$LAYOUT, free_instance_func$OFFSET, fieldValue);
    }

    private static final AddressLayout get_virtual_func$LAYOUT =
            (AddressLayout) $LAYOUT.select(groupElement("get_virtual_func"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * GDExtensionClassGetVirtual get_virtual_func
     * }
     */
    public static final AddressLayout get_virtual_func$layout() {
        return get_virtual_func$LAYOUT;
    }

    private static final long get_virtual_func$OFFSET = $LAYOUT.byteOffset(groupElement("get_virtual_func"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * GDExtensionClassGetVirtual get_virtual_func
     * }
     */
    public static final long get_virtual_func$offset() {
        return get_virtual_func$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * GDExtensionClassGetVirtual get_virtual_func
     * }
     */
    public static MemorySegment get_virtual_func(MemorySegment struct) {
        return struct.get(get_virtual_func$LAYOUT, get_virtual_func$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * GDExtensionClassGetVirtual get_virtual_func
     * }
     */
    public static void get_virtual_func(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(get_virtual_func$LAYOUT, get_virtual_func$OFFSET, fieldValue);
    }

    private static final AddressLayout get_rid_func$LAYOUT =
            (AddressLayout) $LAYOUT.select(groupElement("get_rid_func"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * GDExtensionClassGetRID get_rid_func
     * }
     */
    public static final AddressLayout get_rid_func$layout() {
        return get_rid_func$LAYOUT;
    }

    private static final long get_rid_func$OFFSET = $LAYOUT.byteOffset(groupElement("get_rid_func"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * GDExtensionClassGetRID get_rid_func
     * }
     */
    public static final long get_rid_func$offset() {
        return get_rid_func$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * GDExtensionClassGetRID get_rid_func
     * }
     */
    public static MemorySegment get_rid_func(MemorySegment struct) {
        return struct.get(get_rid_func$LAYOUT, get_rid_func$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * GDExtensionClassGetRID get_rid_func
     * }
     */
    public static void get_rid_func(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(get_rid_func$LAYOUT, get_rid_func$OFFSET, fieldValue);
    }

    private static final AddressLayout class_userdata$LAYOUT =
            (AddressLayout) $LAYOUT.select(groupElement("class_userdata"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void *class_userdata
     * }
     */
    public static final AddressLayout class_userdata$layout() {
        return class_userdata$LAYOUT;
    }

    private static final long class_userdata$OFFSET = $LAYOUT.byteOffset(groupElement("class_userdata"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void *class_userdata
     * }
     */
    public static final long class_userdata$offset() {
        return class_userdata$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void *class_userdata
     * }
     */
    public static MemorySegment class_userdata(MemorySegment struct) {
        return struct.get(class_userdata$LAYOUT, class_userdata$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void *class_userdata
     * }
     */
    public static void class_userdata(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(class_userdata$LAYOUT, class_userdata$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() {
        return layout().byteSize();
    }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(
            MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}
