// Generated by jextract

package io.github.kingg22.godot.internal.ffm;

import java.lang.foreign.AddressLayout;
import java.lang.foreign.Arena;
import java.lang.foreign.GroupLayout;
import java.lang.foreign.MemoryLayout;
import java.lang.foreign.MemorySegment;
import java.lang.foreign.SegmentAllocator;
import java.util.function.Consumer;

import static java.lang.foreign.MemoryLayout.PathElement.groupElement;
import static java.lang.foreign.ValueLayout.OfInt;
import static java.lang.foreign.ValueLayout.OfLong;

/**
 * {@snippet lang=c :
 * struct {
 *     uint32_t major;
 *     uint32_t minor;
 *     uint32_t patch;
 *     uint32_t hex;
 *     const char *status;
 *     const char *build;
 *     const char *hash;
 *     uint64_t timestamp;
 *     const char *string;
 * }
 * }
 */
public final class GDExtensionGodotVersion2 {

    private GDExtensionGodotVersion2() {
        throw new UnsupportedOperationException();
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
                    FFMUtils.C_INT.withName("major"),
                    FFMUtils.C_INT.withName("minor"),
                    FFMUtils.C_INT.withName("patch"),
                    FFMUtils.C_INT.withName("hex"),
                    FFMUtils.C_POINTER.withName("status"),
                    FFMUtils.C_POINTER.withName("build"),
                    FFMUtils.C_POINTER.withName("hash"),
                    FFMUtils.C_LONG.withName("timestamp"),
                    FFMUtils.C_POINTER.withName("string"))
            .withName("GDExtensionGodotVersion2");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt major$LAYOUT = (OfInt) $LAYOUT.select(groupElement("major"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t major
     * }
     */
    public static final OfInt major$layout() {
        return major$LAYOUT;
    }

    private static final long major$OFFSET = $LAYOUT.byteOffset(groupElement("major"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t major
     * }
     */
    public static final long major$offset() {
        return major$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t major
     * }
     */
    public static int major(MemorySegment struct) {
        return struct.get(major$LAYOUT, major$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t major
     * }
     */
    public static void major(MemorySegment struct, int fieldValue) {
        struct.set(major$LAYOUT, major$OFFSET, fieldValue);
    }

    private static final OfInt minor$LAYOUT = (OfInt) $LAYOUT.select(groupElement("minor"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t minor
     * }
     */
    public static final OfInt minor$layout() {
        return minor$LAYOUT;
    }

    private static final long minor$OFFSET = $LAYOUT.byteOffset(groupElement("minor"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t minor
     * }
     */
    public static final long minor$offset() {
        return minor$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t minor
     * }
     */
    public static int minor(MemorySegment struct) {
        return struct.get(minor$LAYOUT, minor$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t minor
     * }
     */
    public static void minor(MemorySegment struct, int fieldValue) {
        struct.set(minor$LAYOUT, minor$OFFSET, fieldValue);
    }

    private static final OfInt patch$LAYOUT = (OfInt) $LAYOUT.select(groupElement("patch"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t patch
     * }
     */
    public static final OfInt patch$layout() {
        return patch$LAYOUT;
    }

    private static final long patch$OFFSET = $LAYOUT.byteOffset(groupElement("patch"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t patch
     * }
     */
    public static final long patch$offset() {
        return patch$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t patch
     * }
     */
    public static int patch(MemorySegment struct) {
        return struct.get(patch$LAYOUT, patch$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t patch
     * }
     */
    public static void patch(MemorySegment struct, int fieldValue) {
        struct.set(patch$LAYOUT, patch$OFFSET, fieldValue);
    }

    private static final OfInt hex$LAYOUT = (OfInt) $LAYOUT.select(groupElement("hex"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t hex
     * }
     */
    public static final OfInt hex$layout() {
        return hex$LAYOUT;
    }

    private static final long hex$OFFSET = $LAYOUT.byteOffset(groupElement("hex"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t hex
     * }
     */
    public static final long hex$offset() {
        return hex$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t hex
     * }
     */
    public static int hex(MemorySegment struct) {
        return struct.get(hex$LAYOUT, hex$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t hex
     * }
     */
    public static void hex(MemorySegment struct, int fieldValue) {
        struct.set(hex$LAYOUT, hex$OFFSET, fieldValue);
    }

    private static final AddressLayout status$LAYOUT = (AddressLayout) $LAYOUT.select(groupElement("status"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *status
     * }
     */
    public static final AddressLayout status$layout() {
        return status$LAYOUT;
    }

    private static final long status$OFFSET = $LAYOUT.byteOffset(groupElement("status"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *status
     * }
     */
    public static final long status$offset() {
        return status$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *status
     * }
     */
    public static MemorySegment status(MemorySegment struct) {
        return struct.get(status$LAYOUT, status$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *status
     * }
     */
    public static void status(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(status$LAYOUT, status$OFFSET, fieldValue);
    }

    private static final AddressLayout build$LAYOUT = (AddressLayout) $LAYOUT.select(groupElement("build"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *build
     * }
     */
    public static final AddressLayout build$layout() {
        return build$LAYOUT;
    }

    private static final long build$OFFSET = $LAYOUT.byteOffset(groupElement("build"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *build
     * }
     */
    public static final long build$offset() {
        return build$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *build
     * }
     */
    public static MemorySegment build(MemorySegment struct) {
        return struct.get(build$LAYOUT, build$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *build
     * }
     */
    public static void build(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(build$LAYOUT, build$OFFSET, fieldValue);
    }

    private static final AddressLayout hash$LAYOUT = (AddressLayout) $LAYOUT.select(groupElement("hash"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *hash
     * }
     */
    public static final AddressLayout hash$layout() {
        return hash$LAYOUT;
    }

    private static final long hash$OFFSET = $LAYOUT.byteOffset(groupElement("hash"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *hash
     * }
     */
    public static final long hash$offset() {
        return hash$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *hash
     * }
     */
    public static MemorySegment hash(MemorySegment struct) {
        return struct.get(hash$LAYOUT, hash$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *hash
     * }
     */
    public static void hash(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(hash$LAYOUT, hash$OFFSET, fieldValue);
    }

    private static final OfLong timestamp$LAYOUT = (OfLong) $LAYOUT.select(groupElement("timestamp"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t timestamp
     * }
     */
    public static final OfLong timestamp$layout() {
        return timestamp$LAYOUT;
    }

    private static final long timestamp$OFFSET = $LAYOUT.byteOffset(groupElement("timestamp"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t timestamp
     * }
     */
    public static final long timestamp$offset() {
        return timestamp$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t timestamp
     * }
     */
    public static long timestamp(MemorySegment struct) {
        return struct.get(timestamp$LAYOUT, timestamp$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t timestamp
     * }
     */
    public static void timestamp(MemorySegment struct, long fieldValue) {
        struct.set(timestamp$LAYOUT, timestamp$OFFSET, fieldValue);
    }

    private static final AddressLayout string$LAYOUT = (AddressLayout) $LAYOUT.select(groupElement("string"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *string
     * }
     */
    public static final AddressLayout string$layout() {
        return string$LAYOUT;
    }

    private static final long string$OFFSET = $LAYOUT.byteOffset(groupElement("string"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *string
     * }
     */
    public static final long string$offset() {
        return string$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *string
     * }
     */
    public static MemorySegment string(MemorySegment struct) {
        return struct.get(string$LAYOUT, string$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *string
     * }
     */
    public static void string(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(string$LAYOUT, string$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() {
        return layout().byteSize();
    }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(
            MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}
