// Generated by jextract

package io.github.kingg22.godot.internal.ffm;

import java.lang.foreign.Arena;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.Linker;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

import static io.github.kingg22.godot.internal.ffm.FFMUtils.C_CHAR;
import static io.github.kingg22.godot.internal.ffm.FFMUtils.C_INT;
import static io.github.kingg22.godot.internal.ffm.FFMUtils.upcallHandle;

/**
 * {@snippet lang = c: typedef GDExtensionBool (*GDExtensionInterfaceVariantCanConvert)(GDExtensionVariantType,
 * GDExtensionVariantType) }
 */
public final class GDExtensionInterfaceVariantCanConvert {

    private GDExtensionInterfaceVariantCanConvert() {
        throw new UnsupportedOperationException();
    }

    /** The function pointer signature, expressed as a functional interface */
    public interface Function {
        byte apply(int p_from, int p_to);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.of(C_CHAR, C_INT, C_INT);

    /** The descriptor of this function pointer */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH =
            upcallHandle(GDExtensionInterfaceVariantCanConvert.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}. The lifetime of the returned segment
     * is managed by {@code arena}
     */
    public static MemorySegment allocate(GDExtensionInterfaceVariantCanConvert.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /** Invoke the upcall stub {@code funcPtr}, with given parameters */
    public static byte invoke(MemorySegment funcPtr, int p_from, int p_to) {
        try {
            return (byte) DOWN$MH.invokeExact(funcPtr, p_from, p_to);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}
