// Generated by jextract

package io.github.kingg22.godot.internal.ffm;

import java.lang.foreign.Arena;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.Linker;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

/**
 * {@snippet lang=c :
 * typedef void (*GDExtensionInterfaceClassdbRegisterExtensionClassSignal)(GDExtensionClassLibraryPtr, GDExtensionConstStringNamePtr, GDExtensionConstStringNamePtr, const GDExtensionPropertyInfo *, GDExtensionInt)
 * }
 */
public final class GDExtensionInterfaceClassdbRegisterExtensionClassSignal {

    private GDExtensionInterfaceClassdbRegisterExtensionClassSignal() {
        throw new UnsupportedOperationException();
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        void apply(
                MemorySegment p_library,
                MemorySegment p_class_name,
                MemorySegment p_signal_name,
                MemorySegment p_argument_info,
                long p_argument_count);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            FFMUtils.C_POINTER, FFMUtils.C_POINTER, FFMUtils.C_POINTER, FFMUtils.C_POINTER, FFMUtils.C_LONG);

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = FFMUtils.upcallHandle(
            GDExtensionInterfaceClassdbRegisterExtensionClassSignal.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(
            GDExtensionInterfaceClassdbRegisterExtensionClassSignal.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static void invoke(
            MemorySegment funcPtr,
            MemorySegment p_library,
            MemorySegment p_class_name,
            MemorySegment p_signal_name,
            MemorySegment p_argument_info,
            long p_argument_count) {
        try {
            DOWN$MH.invokeExact(funcPtr, p_library, p_class_name, p_signal_name, p_argument_info, p_argument_count);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}
