// Generated by jextract

package io.github.kingg22.godot.internal.ffm;

import java.lang.foreign.Arena;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.Linker;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

import static io.github.kingg22.godot.internal.ffm.FFMUtils.C_INT;
import static io.github.kingg22.godot.internal.ffm.FFMUtils.C_POINTER;
import static io.github.kingg22.godot.internal.ffm.FFMUtils.upcallHandle;

/**
 * {@snippet lang = c: typedef GDExtensionPtrSetter (*GDExtensionInterfaceVariantGetPtrSetter)(GDExtensionVariantType,
 * GDExtensionConstStringNamePtr) }
 */
public final class GDExtensionInterfaceVariantGetPtrSetter {

    private GDExtensionInterfaceVariantGetPtrSetter() {
        throw new UnsupportedOperationException();
    }

    /** The function pointer signature, expressed as a functional interface */
    public interface Function {
        MemorySegment apply(int p_type, MemorySegment p_member);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.of(C_POINTER, C_INT, C_POINTER);

    /** The descriptor of this function pointer */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH =
            upcallHandle(GDExtensionInterfaceVariantGetPtrSetter.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}. The lifetime of the returned segment
     * is managed by {@code arena}
     */
    public static MemorySegment allocate(GDExtensionInterfaceVariantGetPtrSetter.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /** Invoke the upcall stub {@code funcPtr}, with given parameters */
    public static MemorySegment invoke(MemorySegment funcPtr, int p_type, MemorySegment p_member) {
        try {
            return (MemorySegment) DOWN$MH.invokeExact(funcPtr, p_type, p_member);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}
