// Generated by jextract

package io.github.kingg22.godot.internal.ffm;

import java.lang.foreign.*;
import java.lang.invoke.*;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.MemoryLayout.PathElement.*;
import static java.lang.foreign.ValueLayout.*;

/**
 * {@snippet lang=c :
 * typedef void (*GDExtensionPtrIndexedGetter)(GDExtensionConstTypePtr, GDExtensionInt, GDExtensionTypePtr)
 * }
 */
public final class GDExtensionPtrIndexedGetter {

    private GDExtensionPtrIndexedGetter() {
        throw new UnsupportedOperationException();
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        void apply(MemorySegment p_base, long p_index, MemorySegment r_value);
    }

    private static final FunctionDescriptor $DESC =
            FunctionDescriptor.ofVoid(FFMUtils.C_POINTER, FFMUtils.C_LONG, FFMUtils.C_POINTER);

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH =
            FFMUtils.upcallHandle(GDExtensionPtrIndexedGetter.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(GDExtensionPtrIndexedGetter.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static void invoke(MemorySegment funcPtr, MemorySegment p_base, long p_index, MemorySegment r_value) {
        try {
            DOWN$MH.invokeExact(funcPtr, p_base, p_index, r_value);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}
