// Generated by jextract

package io.github.kingg22.godot.internal.ffm;

import java.lang.foreign.Arena;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.Linker;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

/**
 * {@snippet lang = c: typedef GDExtensionBool (*GDExtensionInstanceBindingReferenceCallback)(void *, void *,
 * GDExtensionBool) }
 */
public final class GDExtensionInstanceBindingReferenceCallback {

    private GDExtensionInstanceBindingReferenceCallback() {
        // Should not be called directly
    }

    /** The function pointer signature, expressed as a functional interface */
    public interface Function {
        byte apply(MemorySegment p_token, MemorySegment p_binding, byte p_reference);
    }

    private static final FunctionDescriptor $DESC =
            FunctionDescriptor.of(FFMUtils.C_CHAR, FFMUtils.C_POINTER, FFMUtils.C_POINTER, FFMUtils.C_CHAR);

    /** The descriptor of this function pointer */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH =
            FFMUtils.upcallHandle(GDExtensionInstanceBindingReferenceCallback.Function.class, $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}. The lifetime of the returned segment
     * is managed by {@code arena}
     */
    public static MemorySegment allocate(GDExtensionInstanceBindingReferenceCallback.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /** Invoke the upcall stub {@code funcPtr}, with given parameters */
    public static byte invoke(MemorySegment funcPtr, MemorySegment p_token, MemorySegment p_binding, byte p_reference) {
        try {
            return (byte) DOWN$MH.invokeExact(funcPtr, p_token, p_binding, p_reference);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}
