// Generated by jextract

package io.github.kingg22.godot.internal.ffm;

import java.lang.foreign.Arena;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.Linker;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

/**
 * {@snippet lang = c: typedef int64_t (*GDExtensionInterfaceWorkerThreadPoolAddNativeTask)(GDExtensionObjectPtr,
 * GDExtensionWorkerThreadPoolTask, void *, GDExtensionBool, GDExtensionConstStringPtr) }
 */
public final class GDExtensionInterfaceWorkerThreadPoolAddNativeTask {

    private GDExtensionInterfaceWorkerThreadPoolAddNativeTask() {
        // Should not be called directly
    }

    /** The function pointer signature, expressed as a functional interface */
    public interface Function {
        long apply(
                MemorySegment p_instance,
                MemorySegment p_func,
                MemorySegment p_userdata,
                byte p_high_priority,
                MemorySegment p_description);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            FFMUtils.C_LONG,
            FFMUtils.C_POINTER,
            FFMUtils.C_POINTER,
            FFMUtils.C_POINTER,
            FFMUtils.C_CHAR,
            FFMUtils.C_POINTER);

    /** The descriptor of this function pointer */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH =
            FFMUtils.upcallHandle(GDExtensionInterfaceWorkerThreadPoolAddNativeTask.Function.class, $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}. The lifetime of the returned segment
     * is managed by {@code arena}
     */
    public static MemorySegment allocate(GDExtensionInterfaceWorkerThreadPoolAddNativeTask.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /** Invoke the upcall stub {@code funcPtr}, with given parameters */
    public static long invoke(
            MemorySegment funcPtr,
            MemorySegment p_instance,
            MemorySegment p_func,
            MemorySegment p_userdata,
            byte p_high_priority,
            MemorySegment p_description) {
        try {
            return (long) DOWN$MH.invokeExact(funcPtr, p_instance, p_func, p_userdata, p_high_priority, p_description);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}
