// Generated by jextract

package io.github.kingg22.godot.internal.ffm;

import java.lang.foreign.Arena;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.Linker;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

/**
 * {@snippet lang = c: typedef uint32_t (*GDExtensionPtrKeyedChecker)(GDExtensionConstVariantPtr,
 * GDExtensionConstVariantPtr) }
 */
public final class GDExtensionPtrKeyedChecker {

    private GDExtensionPtrKeyedChecker() {
        // Should not be called directly
    }

    /** The function pointer signature, expressed as a functional interface */
    public interface Function {
        int apply(MemorySegment p_base, MemorySegment p_key);
    }

    private static final FunctionDescriptor $DESC =
            FunctionDescriptor.of(FFMUtils.C_INT, FFMUtils.C_POINTER, FFMUtils.C_POINTER);

    /** The descriptor of this function pointer */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = FFMUtils.upcallHandle(GDExtensionPtrKeyedChecker.Function.class, $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}. The lifetime of the returned segment
     * is managed by {@code arena}
     */
    public static MemorySegment allocate(GDExtensionPtrKeyedChecker.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /** Invoke the upcall stub {@code funcPtr}, with given parameters */
    public static int invoke(MemorySegment funcPtr, MemorySegment p_base, MemorySegment p_key) {
        try {
            return (int) DOWN$MH.invokeExact(funcPtr, p_base, p_key);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}
