// Generated by jextract

package io.github.kingg22.godot.internal.ffm;

import java.lang.foreign.Arena;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.Linker;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

import static io.github.kingg22.godot.internal.ffm.FFMUtils.C_INT;
import static io.github.kingg22.godot.internal.ffm.FFMUtils.C_POINTER;
import static io.github.kingg22.godot.internal.ffm.FFMUtils.upcallHandle;

/**
 * {@snippet lang = c: typedef void (*GDExtensionClassNotification)(GDExtensionClassInstancePtr, int32_t) }
 *
 * @deprecated Use GDExtensionClassNotification2 instead
 */
@Deprecated
public final class GDExtensionClassNotification {

    private GDExtensionClassNotification() {
        // Should not be called directly
    }

    /** The function pointer signature, expressed as a functional interface */
    public interface Function {
        void apply(MemorySegment p_instance, int p_what);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(C_POINTER, C_INT);

    /** The descriptor of this function pointer */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = upcallHandle(GDExtensionClassNotification.Function.class, $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}. The lifetime of the returned segment
     * is managed by {@code arena}
     */
    public static MemorySegment allocate(GDExtensionClassNotification.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /** Invoke the upcall stub {@code funcPtr}, with given parameters */
    public static void invoke(MemorySegment funcPtr, MemorySegment p_instance, int p_what) {
        try {
            DOWN$MH.invokeExact(funcPtr, p_instance, p_what);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}
