// Generated by jextract

package io.github.kingg22.godot.internal.ffm;

import java.lang.foreign.*;
import java.lang.invoke.*;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.MemoryLayout.PathElement.*;
import static java.lang.foreign.ValueLayout.*;

/**
 * {@snippet lang=c :
 * typedef GDExtensionVariantType (*GDExtensionScriptInstanceGetPropertyType)(GDExtensionScriptInstanceDataPtr, GDExtensionConstStringNamePtr, GDExtensionBool *)
 * }
 */
public final class GDExtensionScriptInstanceGetPropertyType {

    private GDExtensionScriptInstanceGetPropertyType() {
        throw new UnsupportedOperationException();
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        int apply(MemorySegment p_instance, MemorySegment p_name, MemorySegment r_is_valid);
    }

    private static final FunctionDescriptor $DESC =
            FunctionDescriptor.of(FFMUtils.C_INT, FFMUtils.C_POINTER, FFMUtils.C_POINTER, FFMUtils.C_POINTER);

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH =
            FFMUtils.upcallHandle(GDExtensionScriptInstanceGetPropertyType.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(GDExtensionScriptInstanceGetPropertyType.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static int invoke(
            MemorySegment funcPtr, MemorySegment p_instance, MemorySegment p_name, MemorySegment r_is_valid) {
        try {
            return (int) DOWN$MH.invokeExact(funcPtr, p_instance, p_name, r_is_valid);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}
