// Generated by jextract

package io.github.kingg22.godot.internal.ffm;

import java.lang.foreign.AddressLayout;
import java.lang.foreign.Arena;
import java.lang.foreign.GroupLayout;
import java.lang.foreign.MemoryLayout;
import java.lang.foreign.MemorySegment;
import java.lang.foreign.SegmentAllocator;
import java.util.function.Consumer;

import static io.github.kingg22.godot.internal.ffm.FFMUtils.C_POINTER;
import static java.lang.foreign.MemoryLayout.PathElement.groupElement;

/// ```c++
/// struct {
///     // Will be called after Godot is started and is fully initialized.
///     GDExtensionMainLoopStartupCallback startup_func;
///     // Will be called before Godot is shutdown when it is still fully initialized.
///     GDExtensionMainLoopShutdownCallback shutdown_func;
///     // Will be called for each process frame. This will run after all `_process()` methods on Node,
///     // and before `ScriptServer::frame()`.
///     // This is intended to be the equivalent of `ScriptLanguage::frame()` for GDExtension language bindings that
///     // don't use the script API.
///     GDExtensionMainLoopFrameCallback frame_func;
/// }
/// ```
public final class GDExtensionMainLoopCallbacks {

    private GDExtensionMainLoopCallbacks() {
        throw new UnsupportedOperationException();
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
                    C_POINTER.withName("startup_func"),
                    C_POINTER.withName("shutdown_func"),
                    C_POINTER.withName("frame_func"))
            .withName("$anon$825:9");

    /** The layout of this struct */
    public static GroupLayout layout() {
        return $LAYOUT;
    }

    /// Create a new [GDExtensionMainLoopCallbacks] instance.
    /// See the class documentation for more information.
    /// @return A pointer to instance
    /// @see GDExtensionMainLoopStartupCallback
    /// @see GDExtensionMainLoopShutdownCallback
    /// @see GDExtensionMainLoopFrameCallback
    public static MemorySegment create(
            final MemorySegment startup_func, final MemorySegment shutdown_func, final MemorySegment frame_func) {
        final var arena = Arena.ofAuto();
        final var struct = allocate(arena);
        startup_func(struct, startup_func);
        shutdown_func(struct, shutdown_func);
        frame_func(struct, frame_func);
        return struct;
    }

    private static final AddressLayout startup_func$LAYOUT =
            (AddressLayout) $LAYOUT.select(groupElement("startup_func"));

    /** Layout for field: {@snippet lang = c: GDExtensionMainLoopStartupCallback startup_func } */
    public static AddressLayout startup_func$layout() {
        return startup_func$LAYOUT;
    }

    private static final long startup_func$OFFSET = $LAYOUT.byteOffset(groupElement("startup_func"));

    /** Offset for field: {@snippet lang = c: GDExtensionMainLoopStartupCallback startup_func } */
    public static long startup_func$offset() {
        return startup_func$OFFSET;
    }

    /** Getter for field: {@snippet lang = c: GDExtensionMainLoopStartupCallback startup_func } */
    public static MemorySegment startup_func(MemorySegment struct) {
        return struct.get(startup_func$LAYOUT, startup_func$OFFSET);
    }

    /** Setter for field: {@snippet lang = c: GDExtensionMainLoopStartupCallback startup_func } */
    public static void startup_func(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(startup_func$LAYOUT, startup_func$OFFSET, fieldValue);
    }

    private static final AddressLayout shutdown_func$LAYOUT =
            (AddressLayout) $LAYOUT.select(groupElement("shutdown_func"));

    /** Layout for field: {@snippet lang = c: GDExtensionMainLoopShutdownCallback shutdown_func } */
    public static AddressLayout shutdown_func$layout() {
        return shutdown_func$LAYOUT;
    }

    private static final long shutdown_func$OFFSET = $LAYOUT.byteOffset(groupElement("shutdown_func"));

    /** Offset for field: {@snippet lang = c: GDExtensionMainLoopShutdownCallback shutdown_func } */
    public static long shutdown_func$offset() {
        return shutdown_func$OFFSET;
    }

    /** Getter for field: {@snippet lang = c: GDExtensionMainLoopShutdownCallback shutdown_func } */
    public static MemorySegment shutdown_func(MemorySegment struct) {
        return struct.get(shutdown_func$LAYOUT, shutdown_func$OFFSET);
    }

    /** Setter for field: {@snippet lang = c: GDExtensionMainLoopShutdownCallback shutdown_func } */
    public static void shutdown_func(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(shutdown_func$LAYOUT, shutdown_func$OFFSET, fieldValue);
    }

    private static final AddressLayout frame_func$LAYOUT = (AddressLayout) $LAYOUT.select(groupElement("frame_func"));

    /** Layout for field: {@snippet lang = c: GDExtensionMainLoopFrameCallback frame_func } */
    public static AddressLayout frame_func$layout() {
        return frame_func$LAYOUT;
    }

    private static final long frame_func$OFFSET = $LAYOUT.byteOffset(groupElement("frame_func"));

    /** Offset for field: {@snippet lang = c: GDExtensionMainLoopFrameCallback frame_func } */
    public static long frame_func$offset() {
        return frame_func$OFFSET;
    }

    /** Getter for field: {@snippet lang = c: GDExtensionMainLoopFrameCallback frame_func } */
    public static MemorySegment frame_func(MemorySegment struct) {
        return struct.get(frame_func$LAYOUT, frame_func$OFFSET);
    }

    /** Setter for field: {@snippet lang = c: GDExtensionMainLoopFrameCallback frame_func } */
    public static void frame_func(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(frame_func$LAYOUT, frame_func$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}. The returned segment has
     * address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /** The size (in bytes) of this struct */
    public static long sizeof() {
        return layout().byteSize();
    }

    /** Allocate a segment of size {@code layout().byteSize()} using {@code allocator} */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}. The returned segment has size
     * {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any). The returned segment has
     * size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any). The returned segment has
     * size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(
            MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}
