// Generated by jextract

package io.github.kingg22.godot.internal.ffm;

import java.lang.foreign.Arena;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.Linker;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

/**
 * {@snippet lang = c: typedef void (*GDExtensionInterfaceVariantGetConstantValue)(GDExtensionVariantType,
 * GDExtensionConstStringNamePtr, GDExtensionUninitializedVariantPtr) }
 */
public final class GDExtensionInterfaceVariantGetConstantValue {

    private GDExtensionInterfaceVariantGetConstantValue() {
        // Should not be called directly
    }

    /** The function pointer signature, expressed as a functional interface */
    public interface Function {
        void apply(int p_type, MemorySegment p_constant, MemorySegment r_ret);
    }

    private static final FunctionDescriptor $DESC =
            FunctionDescriptor.ofVoid(FFMUtils.C_INT, FFMUtils.C_POINTER, FFMUtils.C_POINTER);

    /** The descriptor of this function pointer */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH =
            FFMUtils.upcallHandle(GDExtensionInterfaceVariantGetConstantValue.Function.class, $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}. The lifetime of the returned segment
     * is managed by {@code arena}
     */
    public static MemorySegment allocate(GDExtensionInterfaceVariantGetConstantValue.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /** Invoke the upcall stub {@code funcPtr}, with given parameters */
    public static void invoke(MemorySegment funcPtr, int p_type, MemorySegment p_constant, MemorySegment r_ret) {
        try {
            DOWN$MH.invokeExact(funcPtr, p_type, p_constant, r_ret);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}
