// Generated by jextract

package io.github.kingg22.godot.internal.ffm;

import java.lang.foreign.Arena;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.Linker;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

import static io.github.kingg22.godot.internal.ffm.FFMUtils.C_POINTER;
import static io.github.kingg22.godot.internal.ffm.FFMUtils.upcallHandle;

/**
 * {@snippet lang = c: typedef void (*GDExtensionInterfaceObjectMethodBindPtrcall)(GDExtensionMethodBindPtr,
 * GDExtensionObjectPtr, const GDExtensionConstTypePtr *, GDExtensionTypePtr) }
 */
public final class GDExtensionInterfaceObjectMethodBindPtrcall {

    private GDExtensionInterfaceObjectMethodBindPtrcall() {
        throw new UnsupportedOperationException();
    }

    /** The function pointer signature, expressed as a functional interface */
    public interface Function {
        void apply(MemorySegment p_method_bind, MemorySegment p_instance, MemorySegment p_args, MemorySegment r_ret);
    }

    private static final FunctionDescriptor $DESC =
            FunctionDescriptor.ofVoid(C_POINTER, C_POINTER, C_POINTER, C_POINTER);

    /** The descriptor of this function pointer */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH =
            upcallHandle(GDExtensionInterfaceObjectMethodBindPtrcall.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}. The lifetime of the returned segment
     * is managed by {@code arena}
     */
    public static MemorySegment allocate(GDExtensionInterfaceObjectMethodBindPtrcall.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /** Invoke the upcall stub {@code funcPtr}, with given parameters */
    public static void invoke(
            MemorySegment funcPtr,
            MemorySegment p_method_bind,
            MemorySegment p_instance,
            MemorySegment p_args,
            MemorySegment r_ret) {
        try {
            DOWN$MH.invokeExact(funcPtr, p_method_bind, p_instance, p_args, r_ret);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}
