package io.github.kingg22.godot.api.builtin.internal

import io.github.kingg22.godot.api.builtin.Variant
import io.github.kingg22.godot.internal.ffi.GDExtensionVariantOperator
import io.github.kingg22.godot.internal.ffi.GDExtensionVariantType
import org.jetbrains.annotations.ApiStatus

@ApiStatus.Internal
public fun Variant.Operator.toGDExtensionVariantOperator(): GDExtensionVariantOperator = when (this) {
    EQUAL -> GDEXTENSION_VARIANT_OP_EQUAL
    NOT_EQUAL -> GDEXTENSION_VARIANT_OP_NOT_EQUAL
    LESS -> GDEXTENSION_VARIANT_OP_LESS
    LESS_EQUAL -> GDEXTENSION_VARIANT_OP_LESS_EQUAL
    GREATER -> GDEXTENSION_VARIANT_OP_GREATER
    GREATER_EQUAL -> GDEXTENSION_VARIANT_OP_GREATER_EQUAL
    ADD -> GDEXTENSION_VARIANT_OP_ADD
    SUBTRACT -> GDEXTENSION_VARIANT_OP_SUBTRACT
    MULTIPLY -> GDEXTENSION_VARIANT_OP_MULTIPLY
    DIVIDE -> GDEXTENSION_VARIANT_OP_DIVIDE
    NEGATE -> GDEXTENSION_VARIANT_OP_NEGATE
    POSITIVE -> GDEXTENSION_VARIANT_OP_POSITIVE
    MODULE -> GDEXTENSION_VARIANT_OP_MODULE
    POWER -> GDEXTENSION_VARIANT_OP_POWER
    SHIFT_LEFT -> GDEXTENSION_VARIANT_OP_SHIFT_LEFT
    SHIFT_RIGHT -> GDEXTENSION_VARIANT_OP_SHIFT_RIGHT
    BIT_AND -> GDEXTENSION_VARIANT_OP_BIT_AND
    BIT_OR -> GDEXTENSION_VARIANT_OP_BIT_OR
    BIT_XOR -> GDEXTENSION_VARIANT_OP_BIT_XOR
    BIT_NEGATE -> GDEXTENSION_VARIANT_OP_BIT_NEGATE
    AND -> GDEXTENSION_VARIANT_OP_AND
    OR -> GDEXTENSION_VARIANT_OP_OR
    XOR -> GDEXTENSION_VARIANT_OP_XOR
    NOT -> GDEXTENSION_VARIANT_OP_NOT
    IN -> GDEXTENSION_VARIANT_OP_IN
    MAX -> GDEXTENSION_VARIANT_OP_MAX
}

@ApiStatus.Internal
public fun Variant.Type.toGDExtensionVariantType(): GDExtensionVariantType = when (this) {
    NIL -> GDEXTENSION_VARIANT_TYPE_NIL
    BOOL -> GDEXTENSION_VARIANT_TYPE_BOOL
    INT -> GDEXTENSION_VARIANT_TYPE_INT
    FLOAT -> GDEXTENSION_VARIANT_TYPE_FLOAT
    STRING -> GDEXTENSION_VARIANT_TYPE_STRING
    VECTOR2 -> GDEXTENSION_VARIANT_TYPE_VECTOR2
    VECTOR2I -> GDEXTENSION_VARIANT_TYPE_VECTOR2I
    RECT2 -> GDEXTENSION_VARIANT_TYPE_RECT2
    RECT2I -> GDEXTENSION_VARIANT_TYPE_RECT2I
    VECTOR3 -> GDEXTENSION_VARIANT_TYPE_VECTOR3
    VECTOR3I -> GDEXTENSION_VARIANT_TYPE_VECTOR3I
    TRANSFORM2D -> GDEXTENSION_VARIANT_TYPE_TRANSFORM2D
    VECTOR4 -> GDEXTENSION_VARIANT_TYPE_VECTOR4
    VECTOR4I -> GDEXTENSION_VARIANT_TYPE_VECTOR4I
    PLANE -> GDEXTENSION_VARIANT_TYPE_PLANE
    QUATERNION -> GDEXTENSION_VARIANT_TYPE_QUATERNION
    AABB -> GDEXTENSION_VARIANT_TYPE_AABB
    BASIS -> GDEXTENSION_VARIANT_TYPE_BASIS
    TRANSFORM3D -> GDEXTENSION_VARIANT_TYPE_TRANSFORM3D
    PROJECTION -> GDEXTENSION_VARIANT_TYPE_PROJECTION
    COLOR -> GDEXTENSION_VARIANT_TYPE_COLOR
    STRING_NAME -> GDEXTENSION_VARIANT_TYPE_STRING_NAME
    NODE_PATH -> GDEXTENSION_VARIANT_TYPE_NODE_PATH
    RID -> GDEXTENSION_VARIANT_TYPE_RID
    OBJECT -> GDEXTENSION_VARIANT_TYPE_OBJECT
    CALLABLE -> GDEXTENSION_VARIANT_TYPE_CALLABLE
    SIGNAL -> GDEXTENSION_VARIANT_TYPE_SIGNAL
    DICTIONARY -> GDEXTENSION_VARIANT_TYPE_DICTIONARY
    ARRAY -> GDEXTENSION_VARIANT_TYPE_ARRAY
    PACKED_BYTE_ARRAY -> GDEXTENSION_VARIANT_TYPE_PACKED_BYTE_ARRAY
    PACKED_INT32_ARRAY -> GDEXTENSION_VARIANT_TYPE_PACKED_INT32_ARRAY
    PACKED_INT64_ARRAY -> GDEXTENSION_VARIANT_TYPE_PACKED_INT64_ARRAY
    PACKED_FLOAT32_ARRAY -> GDEXTENSION_VARIANT_TYPE_PACKED_FLOAT32_ARRAY
    PACKED_FLOAT64_ARRAY -> GDEXTENSION_VARIANT_TYPE_PACKED_FLOAT64_ARRAY
    PACKED_STRING_ARRAY -> GDEXTENSION_VARIANT_TYPE_PACKED_STRING_ARRAY
    PACKED_VECTOR2_ARRAY -> GDEXTENSION_VARIANT_TYPE_PACKED_VECTOR2_ARRAY
    PACKED_VECTOR3_ARRAY -> GDEXTENSION_VARIANT_TYPE_PACKED_VECTOR3_ARRAY
    PACKED_COLOR_ARRAY -> GDEXTENSION_VARIANT_TYPE_PACKED_COLOR_ARRAY
    PACKED_VECTOR4_ARRAY -> GDEXTENSION_VARIANT_TYPE_PACKED_VECTOR4_ARRAY
    MAX -> GDEXTENSION_VARIANT_TYPE_VARIANT_MAX
}
