package io.github.kingg22.godot.codegen.impl.extensionapi.knative.generators

import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.TypeSpec
import io.github.kingg22.godot.codegen.impl.createFile
import io.github.kingg22.godot.codegen.impl.extensionapi.Context
import io.github.kingg22.godot.codegen.impl.extensionapi.knative.impl.VariantImplGen
import io.github.kingg22.godot.codegen.impl.withExceptionContext
import io.github.kingg22.godot.codegen.models.extensionapi.domain.ResolvedEnum

/**
 * Generates the `Variant` class and its nested `Type` / `Operator` enums.
 *
 * ## Design
 *
 * `Variant` is a **single final class** — no subclasses, no inheritance hierarchy.
 * It owns a Godot Variant allocation (opaque N-byte buffer on `nativeHeap`) and exposes:
 *
 * - A zero-arg primary constructor that produces a NIL variant (zero-initialised storage)
 * - Typed conversion constructors: `Boolean`, `Long`, `Int`, `Double`, and all builtin types
 * - All `variant_*` GDExtension operations as instance methods
 * - Typed extractors: `asXOrNull()` (nullable) and `asX()` (throws on mismatch)
 * - A companion object with static-style helpers (`hasMember`, `canConvert`, `canConvertStrict`)
 * - Commented-out `operator fun invoke` stubs for dynamic reassignment
 *
 * ## File layout
 *
 * ```
 * Variant.kt
 * ├── class Variant                     ← final, owns native storage
 * │   ├── constructor()                 ← NIL (zero-init)
 * │   ├── constructor(from: COpaquePointer)
 * │   ├── constructor(value: Boolean)
 * │   ├── constructor(value: Long)
 * │   ├── constructor(value: Int)       ← synthetic, delegates to Long
 * │   ├── constructor(value: Double)
 * │   ├── constructor(value: GodotString) … constructor(value: PackedVector4Array)
 * │   ├── getType() / isNil()
 * │   ├── evaluate / set / get / setNamed / getNamed / setKeyed / getKeyed / setIndexed / getIndexed
 * │   ├── hasMethod / hasKey
 * │   ├── iterInit / iterNext / iterGet
 * │   ├── call / callStatic
 * │   ├── booleanize / stringify / hashVariant / duplicate
 * │   ├── asBoolOrNull / asBool
 * │   ├── asLongOrNull / asLong
 * │   ├── asDoubleOrNull / asDouble
 * │   ├── asGodotStringOrNull / asGodotString … asPackedVector4ArrayOrNull / asPackedVector4Array
 * │   ├── companion object { hasMember / canConvert / canConvertStrict }
 * │   ├── // operator fun invoke stubs (commented)
 * │   └── enum class Type / enum class Operator
 * ├── fun Boolean.asVariant() … fun PackedVector4Array?.asVariant()   (top-level extensions)
 * ├── private val fromTypeFptr_BOOL … fromTypeFptr_PACKED_VECTOR4_ARRAY  (top-level lazy)
 * └── private val toTypeFptr_BOOL  … toTypeFptr_PACKED_VECTOR4_ARRAY    (top-level lazy)
 * ```
 */
class NativeVariantGenerator(private val enumGenerator: NativeEnumGenerator, private val implGen: VariantImplGen) {

    context(ctx: Context)
    fun generateFile(variantEnums: List<ResolvedEnum>): FileSpec = withExceptionContext({
        "Generating Variant class"
    }) {
        val variantTypes = requireNotNull(variantEnums.firstOrNull { it.name == "Variant.Type" }) {
            "Variant.Type enum not found; available: [${variantEnums.joinToString { it.name }}]"
        }
        val variantClassName = ctx.classNameForOrDefault("Variant")
        val classSpec = generateSpec(variantClassName, variantTypes)

        // nested enums (Type + Operator) — generated by NativeEnumGenerator as before
        val enums = variantEnums.map { enumGenerator.generateSpec(it) }
        classSpec.addTypes(enums)

        // companion object with static helpers
        implGen.buildCompanion(classSpec, variantClassName)

        // commented invoke operator stubs
        implGen.buildInvokeOperatorStub(classSpec, variantTypes)

        createFile("Variant", ctx.packageForOrDefault("Variant")) {
            addType(classSpec.build())

            // top-level asVariant() extensions
            addFunctions(implGen.buildAsVariantExtensions(variantClassName, variantTypes))

            // top-level lazy fptr properties (from + to, one pair per type)
            addProperties(implGen.buildTopLevelFptrProperties(variantTypes))
        }
    }

    context(_: Context)
    fun generateSpec(variantClassName: ClassName, variantTypes: ResolvedEnum): TypeSpec.Builder {
        val typeBuilder = TypeSpec.classBuilder(variantClassName)

        // Empty primary constructor → NIL (zero-init storage)
        typeBuilder.primaryConstructor(FunSpec.constructorBuilder().build())

        // ── Storage, rawPtr, close(), copy constructor ─────────────────────
        implGen.configureVariantClass(typeBuilder)

        // ── Typed conversion constructors ──────────────────────────────────
        implGen.buildConversionConstructors(typeBuilder, variantTypes)

        // ── All variant_* instance operations ──────────────────────────────
        implGen.buildVariantOperations(typeBuilder, variantClassName)

        // ── Typed extractors: asXOrNull + asX ─────────────────────────────
        implGen.buildExtractors(typeBuilder, variantClassName, variantTypes)

        return typeBuilder
    }
}
