// Generated by jextract

package io.github.kingg22.godot.internal.ffm;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     GDExtensionVariantType type;
 *     GDExtensionStringNamePtr name;
 *     GDExtensionStringNamePtr class_name;
 *     uint32_t hint;
 *     GDExtensionStringPtr hint_string;
 *     uint32_t usage;
 * }
 * }
 */
public class GDExtensionPropertyInfo {

    GDExtensionPropertyInfo() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        FFMUtils.C_INT.withName("type"),
        MemoryLayout.paddingLayout(4),
        FFMUtils.C_POINTER.withName("name"),
        FFMUtils.C_POINTER.withName("class_name"),
        FFMUtils.C_INT.withName("hint"),
        MemoryLayout.paddingLayout(4),
        FFMUtils.C_POINTER.withName("hint_string"),
        FFMUtils.C_INT.withName("usage"),
        MemoryLayout.paddingLayout(4)
    ).withName("$anon$235:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt type$LAYOUT = (OfInt)$LAYOUT.select(groupElement("type"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * GDExtensionVariantType type
     * }
     */
    public static final OfInt type$layout() {
        return type$LAYOUT;
    }

    private static final long type$OFFSET = $LAYOUT.byteOffset(groupElement("type"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * GDExtensionVariantType type
     * }
     */
    public static final long type$offset() {
        return type$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * GDExtensionVariantType type
     * }
     */
    public static int type(MemorySegment struct) {
        return struct.get(type$LAYOUT, type$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * GDExtensionVariantType type
     * }
     */
    public static void type(MemorySegment struct, int fieldValue) {
        struct.set(type$LAYOUT, type$OFFSET, fieldValue);
    }

    private static final AddressLayout name$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("name"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * GDExtensionStringNamePtr name
     * }
     */
    public static final AddressLayout name$layout() {
        return name$LAYOUT;
    }

    private static final long name$OFFSET = $LAYOUT.byteOffset(groupElement("name"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * GDExtensionStringNamePtr name
     * }
     */
    public static final long name$offset() {
        return name$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * GDExtensionStringNamePtr name
     * }
     */
    public static MemorySegment name(MemorySegment struct) {
        return struct.get(name$LAYOUT, name$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * GDExtensionStringNamePtr name
     * }
     */
    public static void name(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(name$LAYOUT, name$OFFSET, fieldValue);
    }

    private static final AddressLayout class_name$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("class_name"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * GDExtensionStringNamePtr class_name
     * }
     */
    public static final AddressLayout class_name$layout() {
        return class_name$LAYOUT;
    }

    private static final long class_name$OFFSET = $LAYOUT.byteOffset(groupElement("class_name"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * GDExtensionStringNamePtr class_name
     * }
     */
    public static final long class_name$offset() {
        return class_name$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * GDExtensionStringNamePtr class_name
     * }
     */
    public static MemorySegment class_name(MemorySegment struct) {
        return struct.get(class_name$LAYOUT, class_name$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * GDExtensionStringNamePtr class_name
     * }
     */
    public static void class_name(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(class_name$LAYOUT, class_name$OFFSET, fieldValue);
    }

    private static final OfInt hint$LAYOUT = (OfInt)$LAYOUT.select(groupElement("hint"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t hint
     * }
     */
    public static final OfInt hint$layout() {
        return hint$LAYOUT;
    }

    private static final long hint$OFFSET = $LAYOUT.byteOffset(groupElement("hint"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t hint
     * }
     */
    public static final long hint$offset() {
        return hint$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t hint
     * }
     */
    public static int hint(MemorySegment struct) {
        return struct.get(hint$LAYOUT, hint$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t hint
     * }
     */
    public static void hint(MemorySegment struct, int fieldValue) {
        struct.set(hint$LAYOUT, hint$OFFSET, fieldValue);
    }

    private static final AddressLayout hint_string$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("hint_string"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * GDExtensionStringPtr hint_string
     * }
     */
    public static final AddressLayout hint_string$layout() {
        return hint_string$LAYOUT;
    }

    private static final long hint_string$OFFSET = $LAYOUT.byteOffset(groupElement("hint_string"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * GDExtensionStringPtr hint_string
     * }
     */
    public static final long hint_string$offset() {
        return hint_string$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * GDExtensionStringPtr hint_string
     * }
     */
    public static MemorySegment hint_string(MemorySegment struct) {
        return struct.get(hint_string$LAYOUT, hint_string$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * GDExtensionStringPtr hint_string
     * }
     */
    public static void hint_string(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(hint_string$LAYOUT, hint_string$OFFSET, fieldValue);
    }

    private static final OfInt usage$LAYOUT = (OfInt)$LAYOUT.select(groupElement("usage"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t usage
     * }
     */
    public static final OfInt usage$layout() {
        return usage$LAYOUT;
    }

    private static final long usage$OFFSET = $LAYOUT.byteOffset(groupElement("usage"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t usage
     * }
     */
    public static final long usage$offset() {
        return usage$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t usage
     * }
     */
    public static int usage(MemorySegment struct) {
        return struct.get(usage$LAYOUT, usage$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t usage
     * }
     */
    public static void usage(MemorySegment struct, int fieldValue) {
        struct.set(usage$LAYOUT, usage$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

