// Generated by jextract

package io.github.kingg22.godot.internal.ffm;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef void (*GDExtensionInterfaceClassdbRegisterExtensionClassIntegerConstant)(GDExtensionClassLibraryPtr, GDExtensionConstStringNamePtr, GDExtensionConstStringNamePtr, GDExtensionConstStringNamePtr, GDExtensionInt, GDExtensionBool)
 * }
 */
public final class GDExtensionInterfaceClassdbRegisterExtensionClassIntegerConstant {

    private GDExtensionInterfaceClassdbRegisterExtensionClassIntegerConstant() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        void apply(MemorySegment p_library, MemorySegment p_class_name, MemorySegment p_enum_name, MemorySegment p_constant_name, long p_constant_value, byte p_is_bitfield);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
        FFMUtils.C_POINTER,
        FFMUtils.C_POINTER,
        FFMUtils.C_POINTER,
        FFMUtils.C_POINTER,
        FFMUtils.C_LONG,
        FFMUtils.C_CHAR
    );

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = FFMUtils.upcallHandle(GDExtensionInterfaceClassdbRegisterExtensionClassIntegerConstant.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(GDExtensionInterfaceClassdbRegisterExtensionClassIntegerConstant.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static void invoke(MemorySegment funcPtr, MemorySegment p_library, MemorySegment p_class_name, MemorySegment p_enum_name, MemorySegment p_constant_name, long p_constant_value, byte p_is_bitfield) {
        try {
             DOWN$MH.invokeExact(funcPtr, p_library, p_class_name, p_enum_name, p_constant_name, p_constant_value, p_is_bitfield);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

