// Generated by jextract

package io.github.kingg22.godot.internal.ffm;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef void (*GDExtensionsInterfaceEditorHelpLoadXmlFromUtf8CharsAndLen)(const char *, GDExtensionInt)
 * }
 */
public final class GDExtensionsInterfaceEditorHelpLoadXmlFromUtf8CharsAndLen {

    private GDExtensionsInterfaceEditorHelpLoadXmlFromUtf8CharsAndLen() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        void apply(MemorySegment p_data, long p_size);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
        FFMUtils.C_POINTER,
        FFMUtils.C_LONG
    );

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = FFMUtils.upcallHandle(GDExtensionsInterfaceEditorHelpLoadXmlFromUtf8CharsAndLen.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(GDExtensionsInterfaceEditorHelpLoadXmlFromUtf8CharsAndLen.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static void invoke(MemorySegment funcPtr, MemorySegment p_data, long p_size) {
        try {
             DOWN$MH.invokeExact(funcPtr, p_data, p_size);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

