// Generated by jextract

package io.github.kingg22.godot.internal.ffm;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef GDExtensionClassCreationInfo4 GDExtensionClassCreationInfo5
 * }
 */
public class GDExtensionClassCreationInfo5 extends GDExtensionClassCreationInfo4 {

    GDExtensionClassCreationInfo5() {
        // Should not be called directly
    }
}

