// Generated by jextract

package io.github.kingg22.godot.internal.ffm;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef void (*GDExtensionInterfaceVariantCallStatic)(GDExtensionVariantType, GDExtensionConstStringNamePtr, const GDExtensionConstVariantPtr *, GDExtensionInt, GDExtensionUninitializedVariantPtr, GDExtensionCallError *)
 * }
 */
public final class GDExtensionInterfaceVariantCallStatic {

    private GDExtensionInterfaceVariantCallStatic() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        void apply(int p_type, MemorySegment p_method, MemorySegment p_args, long p_argument_count, MemorySegment r_return, MemorySegment r_error);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
        FFMUtils.C_INT,
        FFMUtils.C_POINTER,
        FFMUtils.C_POINTER,
        FFMUtils.C_LONG,
        FFMUtils.C_POINTER,
        FFMUtils.C_POINTER
    );

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = FFMUtils.upcallHandle(GDExtensionInterfaceVariantCallStatic.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(GDExtensionInterfaceVariantCallStatic.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static void invoke(MemorySegment funcPtr, int p_type, MemorySegment p_method, MemorySegment p_args, long p_argument_count, MemorySegment r_return, MemorySegment r_error) {
        try {
             DOWN$MH.invokeExact(funcPtr, p_type, p_method, p_args, p_argument_count, r_return, r_error);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

