// Generated by jextract

package io.github.kingg22.godot.internal.ffm;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     GDExtensionStringNamePtr name;
 *     GDExtensionPropertyInfo return_value;
 *     uint32_t flags;
 *     int32_t id;
 *     uint32_t argument_count;
 *     GDExtensionPropertyInfo *arguments;
 *     uint32_t default_argument_count;
 *     GDExtensionVariantPtr *default_arguments;
 * }
 * }
 */
public class GDExtensionMethodInfo {

    GDExtensionMethodInfo() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        FFMUtils.C_POINTER.withName("name"),
        GDExtensionPropertyInfo.layout().withName("return_value"),
        FFMUtils.C_INT.withName("flags"),
        FFMUtils.C_INT.withName("id"),
        FFMUtils.C_INT.withName("argument_count"),
        MemoryLayout.paddingLayout(4),
        FFMUtils.C_POINTER.withName("arguments"),
        FFMUtils.C_INT.withName("default_argument_count"),
        MemoryLayout.paddingLayout(4),
        FFMUtils.C_POINTER.withName("default_arguments")
    ).withName("$anon$219:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout name$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("name"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * GDExtensionStringNamePtr name
     * }
     */
    public static final AddressLayout name$layout() {
        return name$LAYOUT;
    }

    private static final long name$OFFSET = $LAYOUT.byteOffset(groupElement("name"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * GDExtensionStringNamePtr name
     * }
     */
    public static final long name$offset() {
        return name$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * GDExtensionStringNamePtr name
     * }
     */
    public static MemorySegment name(MemorySegment struct) {
        return struct.get(name$LAYOUT, name$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * GDExtensionStringNamePtr name
     * }
     */
    public static void name(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(name$LAYOUT, name$OFFSET, fieldValue);
    }

    private static final GroupLayout return_value$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("return_value"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * GDExtensionPropertyInfo return_value
     * }
     */
    public static final GroupLayout return_value$layout() {
        return return_value$LAYOUT;
    }

    private static final long return_value$OFFSET = $LAYOUT.byteOffset(groupElement("return_value"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * GDExtensionPropertyInfo return_value
     * }
     */
    public static final long return_value$offset() {
        return return_value$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * GDExtensionPropertyInfo return_value
     * }
     */
    public static MemorySegment return_value(MemorySegment struct) {
        return struct.asSlice(return_value$OFFSET, return_value$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * GDExtensionPropertyInfo return_value
     * }
     */
    public static void return_value(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, return_value$OFFSET, return_value$LAYOUT.byteSize());
    }

    private static final OfInt flags$LAYOUT = (OfInt)$LAYOUT.select(groupElement("flags"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t flags
     * }
     */
    public static final OfInt flags$layout() {
        return flags$LAYOUT;
    }

    private static final long flags$OFFSET = $LAYOUT.byteOffset(groupElement("flags"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t flags
     * }
     */
    public static final long flags$offset() {
        return flags$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t flags
     * }
     */
    public static int flags(MemorySegment struct) {
        return struct.get(flags$LAYOUT, flags$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t flags
     * }
     */
    public static void flags(MemorySegment struct, int fieldValue) {
        struct.set(flags$LAYOUT, flags$OFFSET, fieldValue);
    }

    private static final OfInt id$LAYOUT = (OfInt)$LAYOUT.select(groupElement("id"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int32_t id
     * }
     */
    public static final OfInt id$layout() {
        return id$LAYOUT;
    }

    private static final long id$OFFSET = $LAYOUT.byteOffset(groupElement("id"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int32_t id
     * }
     */
    public static final long id$offset() {
        return id$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int32_t id
     * }
     */
    public static int id(MemorySegment struct) {
        return struct.get(id$LAYOUT, id$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int32_t id
     * }
     */
    public static void id(MemorySegment struct, int fieldValue) {
        struct.set(id$LAYOUT, id$OFFSET, fieldValue);
    }

    private static final OfInt argument_count$LAYOUT = (OfInt)$LAYOUT.select(groupElement("argument_count"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t argument_count
     * }
     */
    public static final OfInt argument_count$layout() {
        return argument_count$LAYOUT;
    }

    private static final long argument_count$OFFSET = $LAYOUT.byteOffset(groupElement("argument_count"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t argument_count
     * }
     */
    public static final long argument_count$offset() {
        return argument_count$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t argument_count
     * }
     */
    public static int argument_count(MemorySegment struct) {
        return struct.get(argument_count$LAYOUT, argument_count$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t argument_count
     * }
     */
    public static void argument_count(MemorySegment struct, int fieldValue) {
        struct.set(argument_count$LAYOUT, argument_count$OFFSET, fieldValue);
    }

    private static final AddressLayout arguments$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("arguments"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * GDExtensionPropertyInfo *arguments
     * }
     */
    public static final AddressLayout arguments$layout() {
        return arguments$LAYOUT;
    }

    private static final long arguments$OFFSET = $LAYOUT.byteOffset(groupElement("arguments"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * GDExtensionPropertyInfo *arguments
     * }
     */
    public static final long arguments$offset() {
        return arguments$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * GDExtensionPropertyInfo *arguments
     * }
     */
    public static MemorySegment arguments(MemorySegment struct) {
        return struct.get(arguments$LAYOUT, arguments$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * GDExtensionPropertyInfo *arguments
     * }
     */
    public static void arguments(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(arguments$LAYOUT, arguments$OFFSET, fieldValue);
    }

    private static final OfInt default_argument_count$LAYOUT = (OfInt)$LAYOUT.select(groupElement("default_argument_count"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t default_argument_count
     * }
     */
    public static final OfInt default_argument_count$layout() {
        return default_argument_count$LAYOUT;
    }

    private static final long default_argument_count$OFFSET = $LAYOUT.byteOffset(groupElement("default_argument_count"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t default_argument_count
     * }
     */
    public static final long default_argument_count$offset() {
        return default_argument_count$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t default_argument_count
     * }
     */
    public static int default_argument_count(MemorySegment struct) {
        return struct.get(default_argument_count$LAYOUT, default_argument_count$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t default_argument_count
     * }
     */
    public static void default_argument_count(MemorySegment struct, int fieldValue) {
        struct.set(default_argument_count$LAYOUT, default_argument_count$OFFSET, fieldValue);
    }

    private static final AddressLayout default_arguments$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("default_arguments"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * GDExtensionVariantPtr *default_arguments
     * }
     */
    public static final AddressLayout default_arguments$layout() {
        return default_arguments$LAYOUT;
    }

    private static final long default_arguments$OFFSET = $LAYOUT.byteOffset(groupElement("default_arguments"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * GDExtensionVariantPtr *default_arguments
     * }
     */
    public static final long default_arguments$offset() {
        return default_arguments$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * GDExtensionVariantPtr *default_arguments
     * }
     */
    public static MemorySegment default_arguments(MemorySegment struct) {
        return struct.get(default_arguments$LAYOUT, default_arguments$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * GDExtensionVariantPtr *default_arguments
     * }
     */
    public static void default_arguments(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(default_arguments$LAYOUT, default_arguments$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

