# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Kotlin CI with Gradle

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.sha }}
    cancel-in-progress: true

jobs:
  build:
    if: false # Disable until we have a better solution for Native computation time of KMP
    timeout-minutes: 15
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    # Free GitHub Actions Environment Disk Space
    - name: Maximize Build Space
      uses: jlumbroso/free-disk-space@v1.3.1
      with:
        tool-cache: false
        large-packages: false

    - uses: actions/checkout@v6
      #with:
        #fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis

    - name: Set up JDK
      uses: actions/setup-java@v5
      with:
        java-version: '24'
        distribution: 'temurin'
        cache: 'gradle'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Cache konan
      uses: actions/cache@v5
      with:
        path: |
          ~/.konan/dependencies
        key: ${{ runner.os }}-konan
        restore-keys: ${{ runner.os }}-konan

#    - name: Cache SonarQube packages
#      uses: actions/cache@v5
#      if: >
#        ${{
#          github.actor != 'app/renovate' &&
#          (
#            (github.event_name == 'pull_request' &&
#                github.event.pull_request.base.ref == 'main' &&
#                github.event.pull_request.user.login != 'app/dependabot') ||
#            (github.event_name == 'push' && github.ref == 'refs/heads/main')
#          )
#        }}
#      with:
#        path: ~/.sonar/cache
#        key: ${{ runner.os }}-sonar
#        restore-keys: ${{ runner.os }}-sonar

    - name: Change wrapper permissions
      run: chmod +x ./gradlew

    # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v6.1.0
      with:
          cache-read-only: false
          validate-wrappers: true

    - name: Build with Gradle Wrapper
      # Run without a daemon when only run one task
      run: ./gradlew build --no-daemon --stacktrace --no-parallel

#    # With configuration cache parallel, the KMP plugin fails with ConcurrentModificationException
#    - name: Sonar analyze
#      run: ./gradlew sonar --info -Dsonar.verbose=true
#      if: >
#        ${{
#          github.actor != 'app/renovate' &&
#          (
#            (github.event_name == 'pull_request' &&
#                github.event.pull_request.base.ref == 'main' &&
#                github.event.pull_request.user.login != 'app/dependabot') ||
#            (github.event_name == 'push' && github.ref == 'refs/heads/main')
#          )
#        }}
#      env:
#        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Upload reports (if build failed)
      uses: actions/upload-artifact@v7
      if: failure()
      with:
        name: reports
        path: './**/build/reports/'

    # NOTE: The Gradle Wrapper is the default and recommended way to run Gradle (https://docs.gradle.org/current/userguide/gradle_wrapper.html).
    # If your project does not have the Gradle Wrapper configured, you can use the following configuration to run Gradle with a specified version.
    #
    # - name: Setup Gradle
    #   uses: gradle/actions/setup-gradle@v4
    #   with:
    #     gradle-version: '8.9'
    #
    # - name: Build with Gradle 8.9
    #   run: gradle build

  dependency-submission:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v6
    - name: Set up JDK
      uses: actions/setup-java@v5
      with:
        java-version: '24'
        distribution: 'temurin'
        cache: 'gradle'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Change wrapper permissions
      run: chmod +x ./gradlew

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v6.1.0
      with:
          validate-wrappers: false
          cache-read-only: true

    # Generates and submits a dependency graph, enabling Dependabot Alerts for all project dependencies.
    # See: https://github.com/gradle/actions/blob/main/dependency-submission/README.md
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v6.1.0
