package io.github.kingg22.godot.codegen.impl

import com.squareup.kotlinpoet.AnnotationSpec
import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.Documentable
import com.squareup.kotlinpoet.FileSpec

private val NAME_REGEX = Regex("[^A-Za-z0-9_]")
private val K_JVM_NAME = ClassName("kotlin.jvm", "JvmName")
private val K_JVM_STATIC = ClassName("kotlin.jvm", "JvmStatic")
val K_DEPRECATED = ClassName("kotlin", "Deprecated")
val K_REPLACE_WITH = ClassName("kotlin", "ReplaceWith")
val K_SUPPRESS = ClassName("kotlin", "Suppress")

internal inline fun <T> withExceptionContext(metadata: () -> String, block: () -> T): T = try {
    block()
} catch (e: Exception) {
    throw RuntimeException(metadata(), e)
}

fun FileSpec.Builder.commonConfiguration() = apply {
    indent("    ") // use 4 spaces https://pinterest.github.io/ktlint/latest/rules/standard/#indentation
    addFileComment("Generated by the Godot JVM/Java/Kotlin Code Generator. DO NOT EDIT!")
    addAnnotation(
        AnnotationSpec
            .builder(K_SUPPRESS)
            .addMember("%S", "ktlint")
            .addMember("%S", "detekt:all")
            .addMember("%S", "FunctionName")
            .addMember("%S", "RemoveRedundantQualifierName")
            .build(),
    )
}

fun <T : Documentable.Builder<*>> T.addKdocForBitfield(returnType: String?, prefixKdoc: String? = null): T {
    if (returnType == null) return this
    if (returnType.startsWith("bitfield::")) {
        val prefix = if (prefixKdoc != null) "$prefixKdoc " else ""
        addKdoc("$prefix`bitfield` for [%L]", returnType.removePrefix("bitfield::"))
    }
    return this
}

fun buildKdoc(
    description: List<String> = emptyList(),
    see: List<String> = emptyList(),
    paramDocs: Map<String, List<String>> = emptyMap(),
    since: String? = null,
): String {
    val lines = StringBuilder()
    if (description.isNotEmpty()) {
        description.forEach { lines.appendLine(it) }
    }
    if (!since.isNullOrBlank()) {
        lines.appendLine("@since $since")
    }
    paramDocs.forEach { (name, docs) ->
        val text = if (docs.isEmpty()) "" else docs.joinToString(" ")
        lines.appendLine("@param $name $text")
        lines.appendLine()
    }
    see.forEach { entry ->
        lines.appendLine("@see $entry")
    }
    return lines.toString()
}

fun jvmNameAnnotation(name: String): AnnotationSpec.Builder = AnnotationSpec
    .builder(K_JVM_NAME)
    .addMember("%S", name)

fun jvmStaticAnnotation() = AnnotationSpec.builder(K_JVM_STATIC).build()

/**
 * Produces a safe Kotlin identifier for a **method/property/parameter** name.
 *
 * - Replaces illegal characters with `_`
 * - Prepends `_` if starts with a digit
 * - Converts snake_case → camelCase
 * - Backtick-escapes Kotlin keywords
 */
fun safeIdentifier(name: String): String {
    val trimmed = name.trim()
    if (trimmed.isBlank()) return "_"
    val sanitized = trimmed.replace(NAME_REGEX, "_")
    val fixed = if (sanitized.first().isDigit()) "_$sanitized" else sanitized
    val camelCase = fixed.snakeCaseToCamelCase()
    return if (isKotlinKeyword(camelCase)) "`$camelCase`" else camelCase
}

/**
 * Produces a safe Kotlin identifier for a **type name** (class, enum constant).
 *
 * Same rules as [safeIdentifier] but appends `_` instead of backtick-escaping,
 * because type names in KotlinPoet don't support backtick escaping.
 */
fun sanitizeTypeName(name: String): String {
    val trimmed = name.trim()
    check(trimmed.isNotBlank()) { "Type name cannot be blank, '$name' given" }
    val sanitized = trimmed.replace(NAME_REGEX, "_")
    val fixed = if (sanitized.first().isDigit()) "_$sanitized" else sanitized
    return if (isKotlinKeyword(fixed)) "${fixed}_" else fixed
}

/**
 * Renames Godot built-in class names that clash with core Kotlin/JVM types.
 *
 * Keeping these in one place makes future additions trivial.
 */
fun String.renameGodotClass(): String = when (this.lowercase()) {
    "object" -> "GodotObject"
    "error" -> "GodotError"
    "string" -> "GodotString"
    else -> this
}

fun String.snakeCaseToCamelCase(): String {
    val prefix = takeWhile { it == '_' }
    val core = drop(prefix.length)
    return buildString {
        append(prefix)
        var upperNext = false
        for (c in core) {
            when {
                c == '_' -> upperNext = true

                upperNext -> {
                    append(c.uppercaseChar())
                    upperNext = false
                }

                else -> append(c)
            }
        }
    }
}

// ── Kotlin keyword list ───────────────────────────────────────────────────────

fun isKotlinKeyword(name: String): Boolean = name in KOTLIN_KEYWORDS

fun checkAndNormalizeTypeName(rawType: String): String {
    val type = rawType.trim()
    if (type.any { it in ILLEGAL_CHARACTERS_TO_ESCAPE }) {
        error(
            "FATAL: Type '$rawType' contains " +
                ILLEGAL_CHARACTERS_TO_ESCAPE.intersect(rawType.toSet()).joinToString("") +
                ", which is not supported by KotlinPoet.",
        )
    }
    check(!type.isBlank()) { "Type name cannot be blank, '$rawType' given" }
    return type
}

// https://github.com/JetBrains/kotlin/blob/master/compiler/frontend.java/src/org/jetbrains/kotlin/resolve/jvm/checkers/JvmSimpleNameBacktickChecker.kt
// '.', special handle
private val ILLEGAL_CHARACTERS_TO_ESCAPE = setOf(';', '[', ']', '/', '<', '>', ':', '\\')

// https://kotlinlang.org/docs/keyword-reference.html
private val KOTLIN_KEYWORDS = setOf(
    // Hard keywords
    "as", "break", "class", "continue", "do", "else", "false", "for", "fun",
    "if", "in", "interface", "is", "null", "object", "package", "return",
    "super", "this", "throw", "true", "try", "typealias", "typeof", "val",
    "var", "when", "while",
    // Soft keywords
    "by", "catch", "constructor", "delegate", "dynamic", "field", "file",
    "finally", "get", "import", "init", "param", "property", "receiver",
    "set", "setparam", "where",
    // Modifier keywords
    "actual", "abstract", "annotation", "companion", "const", "crossinline",
    "data", "enum", "expect", "external", "final", "infix", "inline", "inner",
    "internal", "lateinit", "noinline", "open", "operator", "out", "override",
    "private", "protected", "public", "reified", "sealed", "suspend",
    "tailrec", "value", "vararg",
    // Legacy / still problematic
    "header", "impl", "yield",
)
